### PR TITLE
Fix using grpc.WithBalancerName("grpclb") explicitly (#2778)

### PR DESCRIPTION
**Pull request by wjywbs**

### CODE REVIEW

**Comment by wjywbs** [comment]
@lyuxuan I think this is a fix to #2778. Marking ready for review for ci.

**Comment by lyuxuan** [comment]
I am not sure how this is solving your problem. Can you explain more? Thanks!

**Comment by wjywbs** [comment]
From #2778: "If I pass grpc.WithBalancerName("grpclb") explicitly in grpc.Dial(), the "grpclb: no remote balancer address is available, should never happen" error is reported.

The curBalancerName is only set when ClientConn.switchBalancer() is called. When balancerBuilder is not nil, switchBalancer is not called and curBalancerName is not set to grpclb.

https://github.com/grpc/grpc-go/blob/v1.20.0/balancer_conn_wrappers.go#L182
https://github.com/grpc/grpc-go/blob/v1.20.0/clientconn.go#L517"

Here it will set curBalancerName to the provided cc.dopts.balancerBuilder's name, so grpclb addresses in dns response will not be removed and the "grpclb: no remote balancer address is available" error will not occur.

**Comment by dfawley** [comment]
@wjywbs you're right that the current behavior seems dubious, and this fix looks reasonable - but why do you want to manually specify the grpclb balancer?  The design of grpclb is that it will be selected automatically whenever balancer addresses are returned by the resolver.

**Comment by wjywbs** [comment]
I'm currently using this pattern:
```
balancer := "round_robin"
if ...
  balancer = "grpclb"
grpc.Dial(grpc.WithBalancerName(balancer)...)
```
Otherwise I need to find out how to switch to round_robin via dns service config.

**Comment by lyuxuan** [comment]
Besides dns service config, another way is to set default service config through [WithDefaultServiceConfig](https://godoc.org/google.golang.org/grpc#WithDefaultServiceConfig). 

Thanks for the fix. I am approving it.

**Pull request merged**
