### PR TITLE
stats: add WireLength to stats.InPayload

### PR DESCRIPTION
**Pull request by ilylia**
fixes #2692

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by ilylia** [comment]
github user fixed.

**Comment by menghanl** [comment]
Thanks for the fix!

Can you sign the CLA? If you already did, can you try to post "I signed it"?

**Comment by ilylia** [comment]
I signed it.

**Comment by ilylia** [comment]
@menghanl I have already signed the CLA with ID ilylia and email ilylia@126.com, the same as the commit, what else do I need to do?

**Comment by menghanl** [comment]
Thanks for the change!

**Pull request merged**
