### PR TITLE
transport/http2_server : Move up streamID validation in operate headers

### PR DESCRIPTION
**Pull request by uds5501**
Fixes : #4779 

Moved stream ID validation as mentioned in the issue and ensured illegal streamIDs are not used for new stream object creation.

RELEASE NOTES:
- TBD

### CODE REVIEW

**Comment by uds5501** [comment]
@menghanl @easwars can you please help me in assigning milestones and labels to this PR?

**Comment by uds5501** [comment]
@easwars Could you please start the tests and review the PR? Thank you :D

**Comment by uds5501** [comment]
@dfawley I actually did forget to push the atomic commits (Few tests were locally failing because of that commit so didn't push).
Also, yes you are right we are going to need a lock for that particular use case.

For now, I have just put the unlock before the assignment of the buffer.

**Comment by dfawley** [comment]
> For now, I have just put the unlock before the assignment of the buffer.

I believe this still has the race, then.  It was avoided before by checking the state of the transport after taking the lock and before deciding whether to allow the stream ID.  Now the checks have been broken apart with an unlock between them.

**Comment by uds5501** [comment]
> FWIW I believe the fix is as simple as including the transport state check along with the (now earlier) stream ID check, but I may be missing something else that makes that incorrect for another reason.

@dfawley  I was thinking on similar lines.
I had one more idea though, what if we keep the transport state where it is and add another layer that if state is `draining` and `maxUserId == current Id` then it should still process this stream.

Ultimately making that check to be - 

```go

if t.state != reachable && !(t.state == draining && maxStreamID == streamID) {
    t.mu.Unlock()
    s.cancel()
    return false
}
```

This can keep the check right there if it's really important.
Otherwise clubbing streamId and transport state validation doesn't seem to be a bad idea either (at least from the surface level)

**Comment by uds5501** [comment]
@dfawley Gotcha, then will update the logic accordingly.

**Comment by dfawley** [comment]
> Just one small doubt, in handling the GOAWAY, would it be contesting for nested locks?? First the transport layer lock and then to get the sid, this max stream ID lock?

Yes.  You will need to make sure you always take `t.maxStreamMu` _without_ holding `t.mu` already.  If you do that, you know that if you are able to take `t.maxStreamMu`, you will eventually be able to take `t.mu`.  So, I believe you'll need to change the outgoing goaway function to take `t.maxStreamMu` at the top.

**Pull request merged**
