### PR TITLE
client: Implement gRFC A6: configurable client-side retry support

### PR DESCRIPTION
**Pull request by dfawley**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2111)

### CODE REVIEW

**Comment by menghanl** [comment]
Still looking at main retry logic in `stream.go`.

---

Reviewed 6 of 10 files at r1, 1 of 2 files at r2.
Review status: 7 of 10 files reviewed at latest revision, all discussions resolved.

---

*[clientconn.go, line 445 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEBwvX_8aJXmqzzkxcw:-LEBwvX_8aJXmqzzkxcx:bjs5jwo) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/clientconn.go#L445)):*
> ```Go
> }
> 
> // WithEnableRetry returns a DialOption that enables retries if the service
> ```

How about moving this to an environment variable instead?
The advantage would be, no code change will be needed when we enable retry in the future.

---

*[clientconn.go, line 1054 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEC0NYf0lQ2xnCc2G3A:-LEC0NYf0lQ2xnCc2G3B:b9ad0i5) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/clientconn.go#L1054)):*
> ```Go
> 	if sc.RetryThrottling != nil {
> 		cc.retryMu.Lock()
> 		cc.retryTokens = sc.RetryThrottling.MaxTokens
> ```

There are things similar to this done in `handleServiceConfig`.

Move those to this function, too? Or add `TODO`?

---

*[clientconn.go, line 1633 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEC3ejj8nl1ztRKe6ot:-LEC3ejj8nl1ztRKe6ou:bnhi871) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/clientconn.go#L1633)):*
> ```Go
> }
> 
> // throttleRetry subtracts a retry token from the pool and returns whether a
> ```

Make a util struct for `retryTokens` and the following functions?

---

*[service_config.go, line 100 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEC5dgS7M_Ii4C3SrC5:-LEC5dgS7M_Ii4C3SrC6:b37s35i) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/service_config.go#L100)):*
> ```Go
> 	// If token_count is less than or equal to maxTokens / 2, then RPCs will not
> 	// be retried and hedged RPCs will not be sent.
> 	RetryThrottling *RetryThrottlingPolicy
> ```

unexport this field. The only reason to export fields in this struct is to use `WithServiceConfig`, but we don't want users to use that.

---

*[service_config.go, line 106 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEG5nOG6WwtUFtuxLX6:-LEG5nOG6WwtUFtuxLX7:b-1s9em6) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/service_config.go#L106)):*
> ```Go
> // service config here:
> // https://github.com/grpc/proposal/blob/master/A6-client-retries.md#integration-with-service-config
> type RetryPolicy struct {
> ```

This type doesn't need to be exported, either. Unless we want to provide another way to config retry other than service config.

---

*[stream.go, line 433 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LERV_523er8mzdxB7Dp:-LERV_523er8mzdxB7Dq:b-gh0tlu) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/stream.go#L433)):*
> ```Go
> 	// TODO(retry): Move down if the spec changes to not check code before
> 	// considering this a failure.
> 	pushback := 0
> ```

Not sure if this is what the TODO is talking about.

This variable is not used until line 463. Move this down after the `if`s?

---

*[stream.go, line 439 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LERWtOY1D70QQLe61mD:-LERWtOY1D70QQLe61mE:b32fswx) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/stream.go#L439)):*
> ```Go
> 		var e error
> 		if pushback, e = strconv.Atoi(sps[0]); e != nil || pushback < 0 {
> 			grpclog.Infof("Server retry pushback specified to abort (%q).", sps[0])
> ```

This is inaccurate if `e != nil`.

---

*[stream.go, line 468 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LERtM9d6dWZKYh-p8Yf:-LERtM9d6dWZKYh-p8Yg:b-woqm57) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/stream.go#L468)):*
> ```Go
> 		max := float64(rp.MaxBackoff)
> 		cur := float64(rp.InitialBackoff)
> 		for i := 0; i < cs.numRetriesSincePushback; i++ {
> ```

To avoid the for loop, how about comparing
  `cs.numRetriesSincePushback` with
  `\log_{multipler}\frac{max}{init}` [math link](http://mathurl.com/yakbzxss)

The latter value can be calculated every time service config gets updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2111#-:-LEWYiUoB1SZrws2OLwo:b-7ude27)*

**Comment by dfawley** [comment]
Review status: 7 of 10 files reviewed, 8 unresolved discussions (waiting on @menghanl)

---

*[clientconn.go, line 445 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEBwvX_8aJXmqzzkxcw:-LEkicay46gzu73iDnIC:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/clientconn.go#L445)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

How about moving this to an environment variable instead?
The advantage would be, no code change will be needed when we enable retry in the future.
</blockquote></details>

Done.

---

*[clientconn.go, line 1054 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEC0NYf0lQ2xnCc2G3A:-LEl3o652joqA3LpHbth:bda6ll) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/clientconn.go#L1054)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

There are things similar to this done in `handleServiceConfig`.

Move those to this function, too? Or add `TODO`?
</blockquote></details>

Deleted setSC after unexporting retry configuration fields from service config structs.

---

*[clientconn.go, line 1633 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEC3ejj8nl1ztRKe6ot:-LEowwmMDkEI0w3lHmtX:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/clientconn.go#L1633)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Make a util struct for `retryTokens` and the following functions?
</blockquote></details>

Done.

---

*[service_config.go, line 100 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEC5dgS7M_Ii4C3SrC5:-LEl8VFHD3cuV-MlfTwl:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/service_config.go#L100)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

unexport this field. The only reason to export fields in this struct is to use `WithServiceConfig`, but we don't want users to use that.
</blockquote></details>

Done.

---

*[service_config.go, line 106 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LEG5nOG6WwtUFtuxLX6:-LEl8WC-2ysDmPeHZ4Nu:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/service_config.go#L106)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

This type doesn't need to be exported, either. Unless we want to provide another way to config retry other than service config.
</blockquote></details>

Done.

---

*[stream.go, line 433 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LERV_523er8mzdxB7Dp:-LEl9s4265OgngUDxyl4:b1f5h0t) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/stream.go#L433)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Not sure if this is what the TODO is talking about.

This variable is not used until line 463. Move this down after the `if`s?
</blockquote></details>

I meant to write "not check pushback" instead.  It is important to check the server pushback value *before* calling `throttleRetry()` (which has side-effects), but there was talk of changing the spec to call throttleRetry() first instead.  Comment updated.

---

*[stream.go, line 439 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LERWtOY1D70QQLe61mD:-LEl8hobB-_OyHUpTRIa:bxtt8mf) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/stream.go#L439)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

This is inaccurate if `e != nil`.
</blockquote></details>

If e != nil, that means a non-numeric response was provided, which the spec says is a valid way for the server to indicate retry should not be performed.

---

*[stream.go, line 468 at r2](https://reviewable.io/reviews/grpc/grpc-go/2111#-LERtM9d6dWZKYh-p8Yf:-LEp0HDYCH6G0hVqXRnu:b-9bmooj) ([raw file](https://github.com/grpc/grpc-go/blob/3a36f2b8c2d66a374f8b6171fa981acb368bd923/stream.go#L468)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

To avoid the for loop, how about comparing
  `cs.numRetriesSincePushback` with
  `\log_{multipler}\frac{max}{init}` [math link](http://mathurl.com/yakbzxss)

The latter value can be calculated every time service config gets updated.
</blockquote></details>

I removed the loop and replaced it by math.Pow(), but left out the optimization that avoids the need to call Pow() when we've hit the max backoff, since it should be quite rare and a minor win.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2111)*

**Comment by dfawley** [comment]
This should be ready to review again, thanks!

**Comment by dfawley** [comment]
Review status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @menghanl and @dfawley)

---

*[stream.go, line 329 at r9](https://reviewable.io/reviews/grpc/grpc-go/2111#-LFx4M0fAlUmOewntnRe:-LG14g2100j08owyBKER:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/3ce06547aa033d0e4ec4a8c77bbd7a982ed34f28/stream.go#L329)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Delete this struct.
</blockquote></details>

Done.

---

*[stream.go, line 339 at r9](https://reviewable.io/reviews/grpc/grpc-go/2111#-LFx5rf3BHBNz8QPnhL9:-LG15MKe5xE2rqgyIeH0:bldegug) ([raw file](https://github.com/grpc/grpc-go/blob/3ce06547aa033d0e4ec4a8c77bbd7a982ed34f28/stream.go#L339)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

`newStream()` could be retried, so it shouldn't call `done`

`done` is already called by `finish`.
</blockquote></details>

This actually was necessary, because I wasn't calling `finish` on the attempt in retry, which is another bug.  Done.

---

*[stream.go, line 427 at r9](https://reviewable.io/reviews/grpc/grpc-go/2111#-LFx6oX-8zFme9RZxBPn:-LG15ktZESCTU2s70UFN:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/3ce06547aa033d0e4ec4a8c77bbd7a982ed34f28/stream.go#L427)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

This comment is inappropriate. The wait happens in the `TrailersOnly` call.
</blockquote></details>

Done.

---

*[stream.go, line 444 at r9](https://reviewable.io/reviews/grpc/grpc-go/2111#-LFx8c3h75eifFEm9RwX:-LG15wcL0L5Q3jsPgkb9:b-5b8eqf) ([raw file](https://github.com/grpc/grpc-go/blob/3ce06547aa033d0e4ec4a8c77bbd7a982ed34f28/stream.go#L444)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

`TrailersOnly` also returns `true` when there's a connection error. But the stream is not necessary trailers only.
</blockquote></details>

I know, but names are hard.  `NoHeaders`?

---

*[stream.go, line 581 at r9](https://reviewable.io/reviews/grpc/grpc-go/2111#-LFxBv9o0HqeTWFxhHCF:-LG16T1XBOlAu5MZvKfS:b-rrhl6d) ([raw file](https://github.com/grpc/grpc-go/blob/3ce06547aa033d0e4ec4a8c77bbd7a982ed34f28/stream.go#L581)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Could `s` be nil?
</blockquote></details>

Yes, if the latest `newStream` attempt failed.  Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2111)*

**Comment by menghanl** [comment]
Reviewed 6 of 8 files at r10.
Review status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @dfawley and @menghanl)

---

*[stream.go, line 266 at r10](https://reviewable.io/reviews/grpc/grpc-go/2111#-LG2NMjn80zu9wNb8ohY:-LG2NMjn80zu9wNb8ohZ:bhjvadk) ([raw file](https://github.com/grpc/grpc-go/blob/0dc7ea5036a2fe469bc304bddb8f7b52df2e6d4f/stream.go#L266)):*
> ```Go
> 	// finish() will affect stats and tracing.
> 	// TODO(dfawley): move to newAttempt when per-attempt stats are implemented.
> 	cs.attempt.statsHandler = sh
> ```

Move statsHandler and traceInfo as parameters for `newAttemptLocked()`

---

*[stream.go, line 560 at r10](https://reviewable.io/reviews/grpc/grpc-go/2111#-LG2NFXd6-KozHoChtzS:-LG2NFXd6-KozHoChtzT:b-9otqmx) ([raw file](https://github.com/grpc/grpc-go/blob/0dc7ea5036a2fe469bc304bddb8f7b52df2e6d4f/stream.go#L560)):*
> ```Go
> 	// We would have retried earlier if necessary.
> 	if cs.attempt.s == nil {
> 		return nil
> ```

Should this return the previous received trailer?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2111)*

**Comment by dfawley** [comment]
Review status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @menghanl)

---

*[stream.go, line 266 at r10](https://reviewable.io/reviews/grpc/grpc-go/2111#-LG2NMjn80zu9wNb8ohY:-LG2QXKe9_z2d-Aj_h-A:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/0dc7ea5036a2fe469bc304bddb8f7b52df2e6d4f/stream.go#L266)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Move statsHandler and traceInfo as parameters for `newAttemptLocked()`
</blockquote></details>

Done.

---

*[stream.go, line 560 at r10](https://reviewable.io/reviews/grpc/grpc-go/2111#-LG2NFXd6-KozHoChtzS:-LG2QXfD9VFsW7AObHD1:bkvb975) ([raw file](https://github.com/grpc/grpc-go/blob/0dc7ea5036a2fe469bc304bddb8f7b52df2e6d4f/stream.go#L560)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Should this return the previous received trailer?
</blockquote></details>

No...but I added a commitAttempt here since it will prevent races when users don't use the API correctly.  And updated the comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2111)*

**Comment by menghanl** [comment]
Reviewed 1 of 7 files at r3, 1 of 8 files at r10, 1 of 1 files at r11.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2111)*

**Comment by dfawley** [comment]
:relieved:

**Comment by annismckenzie** [comment]
@dfawley I'm having a hard time understanding how this is implemented and supposed to be used. Setting the env variable will turn retry support on? Or does that only work when using a Service Config which is also not documented anywhere? I love gRPC but the docs stop right after the basic tutorial. 🙈 (as a sidenote: we've been using gRPC in production for over two years now so I'm not a first-time user and have read the source to some degree; the stab at the docs also isn't meant to be condescending) Any pointers would be appreciated.

**Comment by dfawley** [comment]
@annismckenzie 

> Setting the env variable will turn retry support on? Or does that only work when using a Service Config which is also not documented anywhere?

Yes, you will need to do both (set environment and enable in service config).  Service configs are documented generally [here](https://github.com/grpc/grpc/blob/master/doc/service_config.md), and in Go are set via the resolver (by calling [ClientConn](https://godoc.org/google.golang.org/grpc/resolver#ClientConn).NewServiceConfig).  Our default DNS resolver will provide a service config if one exists in your TXT records (more info in the [SC-in-DNS gRFC](https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md)).  Note that for backward compatibility reasons, the DNS resolver is not the default resolver in grpc-go, so you need to use `grpc.Dial("dns:///<target>")` to use it if you decide to go that route vs. making a custom resolver.  The retry settings of service config are documented the the [retry gRFC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md).  Let us know if anything isn't clear or you need more specific help.

> the stab at the docs also isn't meant to be condescending

It's totally fair.  We know our documentation is not ideal.  Any specific suggestions you have about places where we can improve them and how to do so (e.g. what's better: godoc or our repo's Documentation directory or grpc.io) would be appreciated.

**Pull request merged**
