### PR TITLE
oauth: mark `NewOauthAccess` as deprecated and update examples to use `TokenSource`

### LINKED ISSUE #5415: credentials/oauth: mark oauth.NewOauthAccess as deprecated and point users to oauth.TokenSource
See follow-up AIs in: https://github.com/grpc/grpc-go/issues/5390#issuecomment-1149014738

### PR DESCRIPTION
**Pull request by buzzsurfr**
Fixes #5415

SUMMARY OF CHANGES
* Mark `oauth.NewOauthAccess` as deprecated, pointing to `oauth.TokenSource`
* Change authentication and interceptor example clients to use `oauth.TokenSource`
* Change interop to use `oauth.TokenSource`

RELEASE NOTES:
* Mark `oauth.NewOauthAccess` as deprecated

### CODE REVIEW

**Comment by buzzsurfr** [comment]
FYI, go's parser gives a warning one of the files in interop, stating:
```
"io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
```

The offending line is:
https://github.com/grpc/grpc-go/blob/v1.51.0/interop/client/client.go#L156

Should I file a new issue and fix it with a new PR, or loop it into this one?

**Review by easwars — APPROVED** [review]

**Comment by easwars** [comment]
> Should I file a new issue and fix it with a new PR, or loop it into this one?

> UPDATE: I found 42 references to ioutil.ReadFile in the repo, so would also need to know whether to fix one or all.

Given that we have so many references, a separate issue would be more appropriate. Thanks.

**Review by arvindbr8 — APPROVED** [review]
LGTM

**Comment by easwars** [comment]
@buzzsurfr : Thank you for your contribution !!

**Pull request merged**
