### PR TITLE
streams: Stop cleaning up after orphaned streams

### PR DESCRIPTION
**Pull request by dfawley**
This change introduces some behavior changes that should not impact users that are following the proper stream protocol.  Specifically, one of the following conditions must be satisfied:

1. The user calls `Close` on the `ClientConn`.
1. The user cancels the context provided to `NewClientStream`, or its deadline expires.  (Note that it if the context is no longer needed before the deadline expires, it is still recommended to call `cancel` to prevent bloat.)  **It is *always* recommended to cancel contexts when they are no longer needed, and to never use the background context directly, so all users should always be doing this.**
1. The user calls `RecvMsg` (or `Recv` in generated code) until a non-nil error is returned.
1. The user receives any error from `Header` or `SendMsg` (or `Send` in generated code) besides `io.EOF`.

If none of the above happen, this will leak a goroutine and a context, and grpc will not call the optionally-configured stats handler with a `stats.End` message.

Before this change, if a user created a stream and the server ended the stream, the stats handler would be invoked with a `stats.End` containing the final status of the stream.  Subsequent calls to `RecvMsg` would then trigger the stats handler with `InPayload`s, which may be unexpected by stats handlers.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/1854)

### CODE REVIEW

**Comment by menghanl** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[clientconn.go, line 1384 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4mw3t6Cky1zYmn4-uD:-L4mw3t6Cky1zYmn4-uE:b3cein5) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/clientconn.go#L1384)):*
> ```Go
> // Deprecated: This error is never returned by grpc and should not be
> // referenced by users.
> var ErrClientConnTimeout = errors.New("grpc: timed out when dialing")
> ```

Why is this error moved here?

---

*[stream.go, line 131 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4mwXrh8HfvWvfYxyUn:-L4mwXri5yNuSe76pf54:b4ox69r) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L131)):*
> ```Go
> 	if mc.Timeout != nil && *mc.Timeout >= 0 {
> 		// The cancel function for this context will only be called when RecvMsg
> 		// returns non-nil error or another error is encountered, which means the
> ```

What does this mean?

Also move the comment to where `cancel` is defined? (And move the definition of `cancel` closer to `if`?)

---

*[stream.go, line 419 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n-1ucy6qtn34ufnyZ:-L4n-1ucy6qtn34ufny_:b-puz62x) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L419)):*
> ```Go
> 			// because the generated code requires it.
> 			if err == io.EOF && !cs.desc.ServerStreams {
> 				err = nil
> ```

`return nil` in the second `if err == io.EOF` on line 481 instead of setting it back to `nil` here?
So you can save this `if`, and `finish()` will always be called with `io.EOF` in the successful case.

---

*[stream.go, line 421 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4myjIsN8sXFrGCcqUV:-L4myjIsN8sXFrGCcqUW:b-mcm9ka) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L421)):*
> ```Go
> 				err = nil
> 			}
> 			cs.finish(err)
> ```

So we will call finish() with `nil` in some cases. It should be OK though.

---

*[stream.go, line 491 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n-j0m02HfRrWC9dC7:-L4n-j0m02HfRrWC9dC8:bvgz67y) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L491)):*
> ```Go
> 	}
> 	cs.sentLast = true
> 	cs.t.Write(cs.s, nil, nil, &transport.Options{Last: true})
> ```

Add comment why we don't care the returned error.

---

*[stats/stats_test.go, line 1228 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n0pZVIgBmv2hrcwqK:-L4n0pZVIgBmv2hrcwqL:b-g61xxz) ([raw file](https://github.com/grpc/grpc-go/blob/104054ade91776e67c9f85ea34c4984f2b5f5026/stats/stats_test.go#L1228)):*
> ```Go
> func TestClientStatsFullDuplexRPCNotCallingLastRecv(t *testing.T) {
> 	count := 1
> 	testClientStats(t, &testConfig{compress: "gzip"}, &rpcConfig{count: count, success: true, failfast: false, callType: fullDuplexStreamRPC, noLastRecv: true}, map[int]*checkFuncWithCount{
> ```

Also delete `noLastRecv` field from `rpcConfig`.

---

*[test/end2end_test.go, line 1167 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n2v4-vqEJV7x5C8_d:-L4n2v4-vqEJV7x5C8_e:bij9o4a) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/test/end2end_test.go#L1167)):*
> ```Go
> 		Payload:            payload,
> 	}
> 	if err := stream.Send(req); err != nil && err != io.EOF {
> ```

Should we send multiple times and expect `io.EOF` eventually?

---

*[test/end2end_test.go, line 3800 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n4-INY8c1jGtJ_rpk:-L4n4-INY8c1jGtJ_rpl:b-ytt5yu) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/test/end2end_test.go#L3800)):*
> ```Go
> 	cc := te.clientConn()
> 	tc := testpb.NewTestServiceClient(cc)
> 	ctx, cancel := context.WithCancel(context.Background())
> ```

Consider also `defer`ing this cancel? Otherwise a `fatal` below may cause this to be leaked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc-go/1854)*

**Comment by dfawley** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[clientconn.go, line 1384 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4mw3t6Cky1zYmn4-uD:-L4nbyQzmKCfqzKJD_DW:b-rinm0j) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/clientconn.go#L1384)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Why is this error moved here?
</blockquote></details>

I was tired of looking at it.  I'd delete it, but it's possible it would break somebody, so I don't think we should (and it's harmless).

---

*[stream.go, line 131 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4mwXrh8HfvWvfYxyUn:-L4ncWhB8NWrKbkyQrLP:bb71pro) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L131)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

What does this mean?

Also move the comment to where `cancel` is defined? (And move the definition of `cancel` closer to `if`?)
</blockquote></details>

PTAL

---

*[stream.go, line 419 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n-1ucy6qtn34ufnyZ:-L4neBzrZ6JJejlUG8Hs:b-m4zi2p) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L419)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

`return nil` in the second `if err == io.EOF` on line 481 instead of setting it back to `nil` here?
So you can save this `if`, and `finish()` will always be called with `io.EOF` in the successful case.
</blockquote></details>

I can do this, but it needs an explicit finish() call below in that case, too, because the defer can only finish() on error.  Changed to reflect.  It's maybe cleaner because the special-case stuff is closer together now?

---

*[stream.go, line 421 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4myjIsN8sXFrGCcqUV:-L4neDpVA5gXW3ey5NFo:b-hhz7xw) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L421)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

So we will call finish() with `nil` in some cases. It should be OK though.
</blockquote></details>

Yes, that's fine. finish() converts io.EOF to nil anyway.

---

*[stream.go, line 491 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n-j0m02HfRrWC9dC7:-L4neHqRXMr-MCSrc1Lh:bb6un1j) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/stream.go#L491)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Add comment why we don't care the returned error.
</blockquote></details>

Done

---

*[stats/stats_test.go, line 1228 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n0pZVIgBmv2hrcwqK:-L4nesflDjiKg_MyUWTs:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/104054ade91776e67c9f85ea34c4984f2b5f5026/stats/stats_test.go#L1228)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Also delete `noLastRecv` field from `rpcConfig`.
</blockquote></details>

Done.

---

*[test/end2end_test.go, line 1167 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n2v4-vqEJV7x5C8_d:-L4ngktukFrp99uCLEKA:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/test/end2end_test.go#L1167)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Should we send multiple times and expect `io.EOF` eventually?
</blockquote></details>

Done.

---

*[test/end2end_test.go, line 3800 at r1](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-L4n4-INY8c1jGtJ_rpk:-L4ngCTkT7KbVQC0NqFW:b-e8wcpn) ([raw file](https://github.com/grpc/grpc-go/blob/5863757bfa59188e026f8f9d54e9e0b86d97b5a2/test/end2end_test.go#L3800)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Consider also `defer`ing this cancel? Otherwise a `fatal` below may cause this to be leaked.
</blockquote></details>

I had a defer here once, where did it go?  Re-added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc-go/1854)*

**Comment by menghanl** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc-go/1854#-:-L4qbkaKq5pJr9Ljuj-b:bnfp4nl)*

**Comment by vitalyisaev2** [comment]
@dfawley Could you please clarify if the example of client-side streaming is following the proper stream protocol? Because ```context.Background()``` is used to create stream, and it's not cancelled explicitly.

https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L59

**Comment by menghanl** [comment]
@vitalyisaev2 Thanks for pointing this out!

The route_guide example does `Recv` until a non-nil error is returned, so it follows that

> 3. The user calls RecvMsg (or Recv in generated code) until a non-nil error is returned.


Using `context.Background()` is not something we would recommend, so I filed #1877 to add timeout to all context in the examples, please take a look.

I also filed #1878 to check other `background` context used.

**Comment by vitalyisaev2** [comment]
@menghanl thank you, now examples look much more idiomatic.

**Pull request merged**
