### PR TITLE
health: generate health proto from grpc-proto

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
PTAL @MakMukhi

### CODE REVIEW

**Comment by menghanl** [comment]
The build failure was fixed by #2085. Please rebase and try again. Thanks!

**Comment by carl-mastrangelo** [comment]
@menghanl done

**Comment by carl-mastrangelo** [comment]
@menghanl done

**Comment by menghanl** [comment]
@carl-mastrangelo  Thanks!

**Pull request merged**
