### PR TITLE
Updating the test SSL certs.

### PR DESCRIPTION
**Pull request by jboeuf**
- For interoperability testing, we need the same certs everywhere.
- This was not possible before because Go could not deal with some field
  being encoded as PRINTABLESTRING in the CA and UTF8STRING in the
  server1 cert. However, the certs have been fixed in:
  https://github.com/grpc/grpc/pull/4096
- Also changed the go root testdata cert to avoid confusion (maybe there
  should not be that many copy of the certs in the repo but I will leave
  this to the repo maintainers).

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
And the certs in test/testdata/ ?

**Comment by carl-mastrangelo** [comment]
Actually, are the ones here fine?

test/testdata/ca.pem
transport/testdata/ca.pem
examples/route_guide/testdata/ca.pem
test/testdata/server1.pem
examples/route_guide/testdata/server1.pem

**Comment by jboeuf** [comment]
You're right, I'll fix them all.

**Comment by carl-mastrangelo** [comment]
@jboeuf LGTM

**Comment by iamqizhao** [comment]
If I were here, I would tell you to update the certs for interop tests only. There is no reason to update the others. :)

**Pull request merged**
