### PR TITLE
test: enable xDS CSDS test

### PR DESCRIPTION
**Pull request by lidizheng**
As title.

https://fusion2.corp.google.com/invocations/52d6253f-797f-4490-8100-030b3bddee97/targets

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4354)

### CODE REVIEW

**Comment by dfawley** [comment]
@lidizheng is there a reason you left this as a draft?

**Comment by lidizheng** [comment]
@dfawley The test setup was wrong a few times in grpc/grpc (I didn't create a matching branch there). Now, this PR is passing. We should be good. PTAL.

**Comment by dfawley** [comment]
@lidizheng can you update your branch? It looks like you took it at a time when our build was broken due to a merge (non-)conflict.

**Comment by dfawley** [comment]
Actually, nevermind. The file you changed doesn't matter for anything we test here.  I'll just force the merge.

**Review by dfawley — APPROVED** [review]

**Pull request merged**
