### PR TITLE
Call put if getTransport returns error

### PR DESCRIPTION
**Pull request by menghanl**

### CODE REVIEW

**Comment by menghanl** [comment]
@xiang90 @heyitsanthony

**Comment by tamird** [comment]
Does this need a test?

**Comment by menghanl** [comment]
Will add tests for put().

**Comment by iamqizhao** [comment]
@xiang90 In this case, the entire ClientConn is closing (and Balancer is closing too). I do not think put is required in this case. Any particular reason you need this?

**Pull request closed without merging**
