### PR TITLE
Fix panic 'close of closed channel' when there is no address available to dial.

### PR DESCRIPTION
**Pull request by yhhann**
Fix panic 'close of closed channel' when there is no address available to dial.

### CODE REVIEW

**Comment by yhhann** [comment]
This request fix panic 'close of closed channel' when there is no address available to dial, merge it please.

**Comment by menghanl** [comment]
What do you mean by "no address available to dial"?
Can you provide a small example to reproduce the panic?

**Comment by yhhann** [comment]
Thanks for  menghanl's comment.

"no address available to dial" means the logic hit a grpc error 'errNoAddr'.

**Comment by yhhann** [comment]
Here is the stack.

E1130 17:52:11.822574    8270 client.go:91] Failed to dial service "vexillary-demo", grpc: there is no address available to dial
panic: close of closed channel

goroutine 1 [running]:
panic(0x820b00, 0xc420190b90)
        .../src/runtime/panic.go:500 +0x1a1
		
google.golang.org/grpc.(*roundRobin).Close(0xc4201c6540, 0x0, 0x0)
        mytest/third-party-go/vendor/google.golang.org/grpc/go_default_library.a.dir/jingoal.com/third-party-go/vendor/google.golang.org/grpc/balancer.go:396 +0xc9
		
google.golang.org/grpc.(*ClientConn).Close(0xc420210000, 0x0, 0x0)
        mytest/third-party-go/vendor/google.golang.org/grpc/go_default_library.a.dir/jingoal.com/third-party-go/vendor/google.golang.org/grpc/clientconn.go:577 +0x172
		
google.golang.org/grpc.DialContext.func1(0xac5120, 0xc420014510, 0xc420167da0, 0xc420167da8, 0xc420210000)
        mytest/third-party-go/vendor/google.golang.org/grpc/go_default_library.a.dir/jingoal.com/third-party-go/vendor/google.golang.org/grpc/clientconn.go:258 +0x86google.golang.org/grpc.DialContext(0xac5120, 0xc420014510, 0xc420128fa0, 0xe, 0xc420167e98, 0x4, 0x4, 0x0, 0xabd060, 0xc420015e40)

		mytest/third-party-go/vendor/google.golang.org/grpc/go_default_library.a.dir/jingoal.com/third-party-go/vendor/google.golang.org/grpc/clientconn.go:331 +0x59f
google.golang.org/grpc.Dial(0xc420128fa0, 0xe, 0xc420167e98, 0x4, 0x4, 0x0, 0xabd060, 0xc420015ed0)
		mytest/third-party-go/vendor/google.golang.org/grpc/go_default_library.a.dir/jingoal.com/third-party-go/vendor/google.golang.org/grpc/clientconn.go:236 +0x72
		
...

my main func.

I implement a Resolver which work with roundRobin together, when my resolver find out an empty server list, the logic will hit 'errNoAddr', and then it will close the roundrobin twice, so panic.

			} else {
				addrs, ok = <-ch
				if !ok || len(addrs) == 0 {
					waitC <- errNoAddr
					return
				}
			}

**Comment by menghanl** [comment]
My guess is that `addrCh` is closed twice because `balancer.Close()` is called twice.
This should not happen if `balancer.Close()` is only called by gRPC internals.
Did you call `balancer.Close()` in your code?

**Comment by yhhann** [comment]
I think so too, but I do not call balancer.Close().

**Comment by menghanl** [comment]
Can you provide a test to reproduce this?

**Comment by dfawley** [comment]
This problem was fixed by #1139.  Thanks.

**Pull request closed without merging**
