### PR TITLE
stats/opentelemetry: Add RLS Metrics e2e tests

### PR DESCRIPTION
**Pull request by zasweq**
This PR adds e2e tests for RLS Metrics, with verifications of the OpenTelemetry metrics atoms emitted.

RELEASE NOTES:
* stats/opentelemetry: De-experimentalize OpenTelemetry instrumentation component and CSM Observability

### CODE REVIEW

**Comment by easwars** [comment]
@zasweq : I'm not going to be able to get to this for at least a week. Please find another reviewer if you want it reviewed sooner. Thanks.

**Comment by dfawley** [comment]
As discussed offline: RLS's tests should go with RLS, not with OTel, and this PR is about testing RLS not OTel.

That also prevents the need to fork a copy of / move the testing helper code around.

**Comment by zasweq** [comment]
Moved to balancer/rls. Thanks.

**Comment by zasweq** [comment]
Fixed the go.mods due to moving it by deleting the stats/opentelemetry go.mod.

**Review by dfawley — APPROVED** [review]
This change makes us release the opentelemetry package and also CSM.  We should make sure the release notes mention that.  And make sure all the APIs contained in both are either marked as experimental or are believed to be stable.

**Comment by zasweq** [comment]
Due to merge conflicts from updating repository dependencies opened #7759.

**Pull request closed without merging**
