### PR TITLE
balancer: support custom strategy for balancer build option.

### PR DESCRIPTION
**Pull request by imxyb**

### CODE REVIEW

**Comment by dfawley** [comment]
The dial option you are passing here is for controlling reconnecting behavior within a subchannel, not for the LB policy.

What are your motivations for this change?

**Comment by imxyb** [comment]
I see this code:
```
b := sbc.builder.Build(sbc, balancer.BuildOptions{})
```
 in the `startBalancer` method in the `subBalancerWrapper`, so there is no way for the subchannel to set the corresponding strategy?

**Comment by dfawley** [comment]
> The dial option you are passing here is for controlling reconnecting behavior within a subchannel, not for the LB policy.

Sorry, please ignore this comment; I misunderstood the change.

> is no way for the subchannel to set the corresponding strategy?

Yes, I don't think there's any way to actually set this strategy you've added.

Do you need this feature?  Or were you just trying to fix a TODO you saw?  I think the way this would be done is by changing the LB config in the service config (which would be cross-language and require a gRFC).

**Comment by imxyb** [comment]
> > The dial option you are passing here is for controlling reconnecting behavior within a subchannel, not for the LB policy.
> 
> Sorry, please ignore this comment; I misunderstood the change.
> 
> > is no way for the subchannel to set the corresponding strategy?
> 
> Yes, I don't think there's any way to actually set this strategy you've added.
> 
> Do you need this feature? Or were you just trying to fix a TODO you saw? I think the way this would be done is by changing the LB config in the service config (which would be cross-language and require a gRFC).

yes, i only want fix this TODO

**Comment by dfawley** [comment]
> yes, i only want fix this TODO

Frankly I'm not sure why this TODO is here.  Maybe just delete it?  Making this configurable would mean it needs to be done cross-language, require a gRFC, and grpclb is deprecated now.

**Comment by imxyb** [comment]
> > yes, i only want fix this TODO
> 
> Frankly I'm not sure why this TODO is here. Maybe just delete it? Making this configurable would mean it needs to be done cross-language, require a gRFC, and grpclb is deprecated now.

ok, may be need a better method to solve it, i close it now, thanks!

**Pull request closed without merging**
