### PR TITLE
Remove OAuth support from `credentials`

### LINKED ISSUE #219: grpc-go should not depend on oauth2
There is no real harm here, but go-grpc ought to maintain a slim set of dependencies to reduce the cost of integrating it into an application.

https://github.com/grpc/grpc-go/blob/master/credentials/credentials.go defines all the necessary interfaces; the `oauth2` implementations can (and should) be put into a separate package to allow people to opt-out.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #219.

### CODE REVIEW

**Comment by iamqizhao** [comment]
LGTM, but it might break some existing users. Let me check.

**Comment by tamird** [comment]
Er, I meant to ping here.

**Comment by iamqizhao** [comment]
Hi Tamir,

Sorry about the delay. Since this PR will probably break google cloud
bigtable in GO (
https://github.com/GoogleCloudPlatform/gcloud-golang/tree/master/bigtable)
which is in Beta. Please talk to @dsymonds to reach agreement before we
proceed here.

On Thu, Jun 11, 2015 at 11:43 AM, Tamir Duberstein <notifications@github.com

**Comment by tamird** [comment]
To avoid breaking bigtable, we can make this change in 3 stages:
- add a new empty package `credentials/oauth/oauth`
- import that package in bigtable
- merge this PR

@dsymonds @iamqizhao what do you think?

**Comment by tamird** [comment]
@dsymonds does the above sound reasonable to you?

**Comment by tamird** [comment]
@dsymonds this should be ready whenever you are.

**Comment by tamird** [comment]
@dsymonds ping

**Comment by tamird** [comment]
@iamqizhao this should be safe to merge now that https://github.com/GoogleCloudPlatform/gcloud-golang/commit/95c332f94e6766fa122231c0a95ddf15ac26bf70 is in.

**Pull request merged**
