### PR TITLE
xds: Remove usages of grpc.WithInsecure().

### PR DESCRIPTION
**Pull request by easwars**

### CODE REVIEW

**Comment by menghanl** [comment]
What's the purpose of this change? I thought the main reason the `insecure.New()` is for the xds creds to set as the fallback?
And are we going to change the other non-xds code the same? If we are going to change everything, can we just change how `grpc.WithInsecure()` works?

**Comment by easwars** [comment]
> What's the purpose of this change? I thought the main reason the `insecure.New()` is for the xds creds to set as the fallback?
> And are we going to change the other non-xds code the same? If we are going to change everything, can we just change how `grpc.WithInsecure()` works?

We could change how `grpc.WithInsecure()` works, but I thought the plan was to deprecate it.

**Comment by menghanl** [comment]
We can deprecate `WithInsecure()` and change its implementation in the same PR. We could probably also simplify `grpc.Dial` a bit at the same time.

And, is there any specific reason that you sent this change only to update xds code? Do you need this for xds security? From the changes, I don't see how they are different from the non-xds usage of `WithInsecure()`.

**Comment by easwars** [comment]
> And, is there any specific reason that you sent this change only to update xds code? Do you need this for xds security? From the changes, I don't see how they are different from the non-xds usage of WithInsecure().

This was easier (and I just did this while I was blocked on something else) and I didn't want to get into the big change at this point. I thought changing usages separately and incrementally and then doing the deprecation and required simplification to `grpc.Dial` might be easier.

**Comment by easwars** [comment]
> Do you need this for xds security? From the changes, I don't see how they are different from the non-xds usage of WithInsecure().

Not required for security. As I mentioned in the other comment, I just did this when I was blocked on something else, and thought it would be better to do this incrementally than one giant change.

**Review by menghanl — APPROVED** [review]

**Comment by easwars** [comment]
Rebased after #4015

**Pull request merged**
