### PR TITLE
[roundrobin] fix race between Start and Notify

### PR DESCRIPTION
**Pull request by LK4D4**
There is no harm in the precreating channel in the constructor.
And there is no point in calling Start twice as I see.

### CODE REVIEW

**Comment by dfawley** [comment]
Could you please look into the test failures?  Thanks!

**Comment by LK4D4** [comment]
@dfawley I think I've fixed problem. Added a comment to clarify what's going on.
I think grpclb has the same problem, maybe material for another PR.
Thanks!

**Comment by dfawley** [comment]
Can you provide a little more background into why this change is necessary?  grpc should be ensuring Start() is called and completes before calling Notify() -- and if it's not, that's a bug.

**Comment by LK4D4** [comment]
@dfawley Notify can be called outside of grpc(that's what happened in our code).

**Comment by dfawley** [comment]
Notify is not intended for use outside gRPC.  Otherwise, updates from the resolver could be lost.  Why do you need access to this channel?

**Comment by LK4D4** [comment]
@dfawley Okay, I got it. I don't know why we did it, but we're not gonna do it again. Thanks!

**Pull request closed without merging**
