### PR TITLE
Fix handleStream read map panic

### PR DESCRIPTION
**Pull request by moypray**
Description:
In golang, if we read/write map in different goroutine, it may panic.
We need to add lock to protect the map data when read/write the map.

Now the `server.m` write operation is protected, but read operation in
handleStream is not protected. And this may cause panic.

Panic Message:

```
2017-07-11T20:31:04.314920+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: fatal error: concurrent map read and map write
2017-07-11T20:31:04.317240+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: goroutine 333 [running]:
2017-07-11T20:31:04.317557+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: runtime.throw(0x95c9a4, 0x21)
2017-07-11T20:31:04.318100+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: /usr/lib/golang/src/runtime/panic.go:566 +0x95 fp=0xc4206a3540 sp=0xc4206a3520
2017-07-11T20:31:04.318410+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: runtime.mapaccess2_faststr(0x8c6160, 0xc42015f920, 0xc4204ef701, 0x9,0x9, 0x0)
2017-07-11T20:31:04.318735+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: /usr/lib/golang/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4206a35a0 sp=0xc4206a3540
2017-07-11T20:31:04.319109+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: google.golang.org/grpc.(*Server).handleStream(0xc4201ac0c0, 0xd98060,0xc420079cb0, 0xc4207a3950, 0xc42015df20)
2017-07-11T20:31:04.319453+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: /home/abuild/rpmbuild/BUILD/containerd/vendor/src/google.golang.org/grpc/server.go:776+0x604 fp=0xc4206a3760 sp=0xc4206a35a0
2017-07-11T20:31:04.319815+00:00 V2R1C00B026-GUESTOS-FS-KVM-X64 docker: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420594cf0,
0xc4201ac0c0, 0xd98060, 0xc420079cb0, 0xc4207a3950)

```

Signed-off-by: Wentao Zhang <zhangwentao234@huawei.com>

### CODE REVIEW

**Comment by moypray** [comment]
I signed it!

**Comment by keloyang** [comment]
I'm not sure if that's a problem, if you call all your register before the service ,I think there is no need to add a lock to handleStream.

**Comment by menghanl** [comment]
Correct me if I'm wrong, I think concurrent read from a map doesn't cause panic.

Also, registering new services to a server after `serve()` is called is not a valid use case.
It fatals after #828.

**Comment by moypray** [comment]
@menghanl  I found that issue in docker-containerd project link:
https://github.com/containerd/containerd/tree/v0.2.x

In containerd project, We start health check grpc server first (to make sure the health check should be first served), And then load data from disk, after all the data done, we register the grpc real service of containerd. (loading data from disk maybe cost lots of time, and docker will do health check after containerd process starts up, if 3 times health check lost, docker will kill containerd and restarted it. That's why we need start health check first.)

Yeap, this is not a standard initialization process, but it should not be panic.

And more, Maybe containerd used the old version of grpc, it does not have the #828. And it is not crashed in `grpclog.Fatalf("grpc: Server.RegisterService xxxx)` function. But in `grpc/server.go:776+0x604 fp=0xc4206a3760`,
https://github.com/containerd/containerd/blob/v0.2.x/vendor/google.golang.org/grpc/server.go#L776

This is caused by concurrent read/write map.  I think this is a golang issue. we should protect the map.


BTW, I see #828, new grpc code prohibit users registering new service after grpc server starts. Is there any issue about this?? Why not use a RWMutex to protect the map as I fixed, it won't have efficiency problem.

**Comment by moypray** [comment]
> Correct me if I'm wrong, I think concurrent read from a map doesn't cause panic.

Yes, concurrent read is not a problem, but concurrent read and write will cause panic. 
This is a golang issue. I have do some test, you could run this panic within 10 seconds:
```
fatal error: concurrent map iteration and map write

goroutine 5 [running]:
runtime.throw(0x4ab248, 0x26)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420041e38 sp=0xc420041e18
runtime.mapiternext(0xc420041f68)
        /usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc420041ee8 sp=0xc420041e38
main.main.func1(0xc420010120)
        /root/test/map/a.go:12 +0x19c fp=0xc420041fd8 sp=0xc420041ee8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420041fe0 sp=0xc420041fd8
created by main.main
        /root/test/map/a.go:17 +0x73

goroutine 1 [sleep]:
time.Sleep(0x174876e800)
        /usr/local/go/src/runtime/time.go:59 +0xf9
main.main()
        /root/test/map/a.go:27 +0xa8

goroutine 6 [runnable]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:57 +0xb8
main.main.func2(0xc420010120)
        /root/test/map/a.go:23 +0x6a
created by main.main
        /root/test/map/a.go:25 +0x95
exit status 2
root@localhost:~/test/map# cat a.go
package main

import (
        "fmt"
        "time"
)

func main() {
        mp := make(map[int]int)
        go func() {
                for {
                        for k, v := range mp {
                                fmt.Println("k=%d,v=%d", k, v)
                                time.Sleep(0 * time.Second)
                        }
                }
        }()
        go func() {
                i := 0
                for {
                        i++
                        mp[i] = i
                        time.Sleep(1 * time.Second)
                }
        }()

        time.Sleep(100 * time.Second)
}
root@localhost:~/test/map#
```

**Comment by hqhq** [comment]
@moypray The point is, if the scenario you got this panic is caused by registering grpc service after grpc server started, and it's already cached by https://github.com/grpc/grpc-go/pull/828 , and the containerd code which triggered this issue didn't include that code, I think it's not a grpc issue now. Before #828 it is an issue, but after that, grpc explicitly consider that scenario as invalid, maybe we should update grpc vendor and fix that invalid grpc use case.

**Comment by moypray** [comment]
@hqhq yeap, But I am wondering if there is any other issue about registering services after grpc.Serve?  Why not using a RWLock to protect the map? From #828 I don't  get the answer.

**Comment by menghanl** [comment]
The purpose of not support registering after `serve()` is to avoid the overhead of mutex when reading from the service handler map. We didn't see the need to register new service handlers after the server has been started.

If you have a use case where the service handler has to be installed after `serve()` is called, please file an issue, and we will consider supporting `register` after `serve()`.

**Comment by hqhq** [comment]
@menghanl Thanks for clarifying, I think we can close this PR now.

**Comment by moypray** [comment]
@menghanl OK， thanks~~ l will close this PR now.

**Pull request closed without merging**
