### PR TITLE
More flexibility in configuration of client proxy(#1446)

### LINKED ISSUE #1446: Setting proxy parameters is not flexible enough
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
bfaf0423469fc4f95e9eac7e3eec0b2abb46fcca

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
There are multiple grpc connections in my project at one time. One of them need proxy, another not. Proxy require credentials.

### What did you see?
Currently, grpc-go takes proxy settings from ENV only once at the start of binary. In addition, it is a little bit buggy. It takes only host and ignores credentials.

### What did you expect to see?
I want 
* use credentials with proxy
* possibility to change proxy in runtime. Since grpc-go takes it only once from env, so it will be enough to add optional parameter ProxyURL. If it is not exist, then use value from ENV

### PR DESCRIPTION
**Pull request by shevchenkodenis**
* ProxyURL client option
* Posibility to use credentials from proxy string

fixes #1446

### CODE REVIEW

**Comment by shevchenkodenis** [comment]
I signed it.

чт, 17 авг. 2017, 4:55 PM googlebot <notifications@github.com>:

**Comment by shevchenkodenis** [comment]
Fixed tests and added case for using custom proxy.

**Comment by menghanl** [comment]
Thanks for the contribution and sorry for the late reply.

One issue with your proposed fix is that, the new dial option `WithProxyURL` is too specific for this problem. And it would be better if we can get a more general solution.

A proxy dialer actually consists of three parts:
 - mapper from the target address to the proxy server address (for example, get proxy env variable)
 - dialer
 - handshaker

Currently, we have these three components, but they are not explicitly called out and not exported.

The proposal we make here is to make the mapper and handshaker public, so users can compose their custom proxy dialer as they want, using these components.

This includes:
 - Add a new `proxy` package
 - Move code in proxy.go to the new `proxy` package
 - Export `ProxyFromEnv` and `HTTPConnectHandshake`
   - `ProxyFromEnv` would return one more `http.Header` value for credentials
   - `HTTPConnectHandshake` would take one more `http.Header` parameter
 - Add a new function which takes a mapper, a dialer and a handshaker and returns a dialer for gRPC

With the above changes, for your particular problem, you would just need to provide your mapper (which always returns your specified `URL` and `http.Header` field containing your creds), and build a dialer with the existing handshaker.

Please let us know if you want to make the implementation as we suggested.

If you don't have time to implement all of those and want a solution for your issue, a walkaround would be to implement your own proxy dialer, which may need copying some of the function from proxy.go, and dial using [WithDialer](https://godoc.org/google.golang.org/grpc#WithDialer).

**Comment by shevchenkodenis** [comment]
@dfawley no problem. I will implement it asap.

**Comment by menghanl** [comment]
Ping. Are you still planning on implementing this?

**Comment by shevchenkodenis** [comment]
@menghanl  sorry for delay, I was on vacation. I am planning to implement this on Monday.

**Comment by menghanl** [comment]
@shevchenkodenis No worries! Thanks for implementing this!

**Comment by menghanl** [comment]
Ping. Just want to check what the status of this is.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @shevchenkodenis isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by menghanl** [comment]
Closing the PR now.
Please leave a comment if you want to revive this.

**Pull request closed without merging**
