### PR TITLE
skip wait when creating ClientConn

### PR DESCRIPTION
**Pull request by iamqizhao**

### CODE REVIEW

**Comment by dsymonds** [comment]
This is a pretty significant change in the API. Was there discussion somewhere?

I wonder if this will break existing code that is expecting Dial to actually establish a connection. As it is, I don't see any comment change on Dial that makes this clear.

**Comment by iamqizhao** [comment]
I actually thought it is mostly transparent to the users (hardly think of
any case which requires Dial to actually connect the server). Added some
comments to Dial to make this clear. This behavior will be consistent
across C, Java and Go. Sameer Bryan and I had a discussion on this long
time ago and we agreed that wait skipping should be preferred default
behavior.

**Comment by dsymonds** [comment]
It's a bit unexpected if your program is already structured to set things up first, and then serve requests by making outgoing RPCs after all that. This adds a performance hit to that first request when you otherwise had expected it to be taken care of during setup. Passing `grpc.WithBlock` will take care of that now, but it also means that every client library that builds on top of gRPC needs to have a mechanism to pass that through too.

The second aspect that makes this feel weird to me is error handling: Generally, if dialing outright fails, it is a permanent failure (e.g. malformed address), and your program can't do anything else at that point; however, an RPC failing is often not a permanent problem, and a program can keep going. Pushing the actual dial back to the first RPC means that programs need to put more thought into handling RPC errors than they would otherwise have to, which means most programs will behave poorly.

I'm not too fussed about being consistent with C and Java on every last detail. This might be a situation where it makes sense to be consistent, but just saying "C and Java also do this" isn't a trump card, because we intentionally diverge from them in many places where we judge it to be better.

@Sajmani @bcmills in case you guys want to enlighten me here.

**Comment by dsymonds** [comment]
This also makes `grpc.Dial` inconsistent with `net.Dial` in this regard. I must be missing the compelling reason for this change, since I'm only seeing downsides.

**Comment by iamqizhao** [comment]
On Mon, Jun 1, 2015 at 4:46 PM, David Symonds <notifications@github.com>
wrote:

> It's a bit unexpected if your program is already structured to set things
> up first, and then serve requests by making outgoing RPCs after all that.
> This adds a performance hit to that first request when you otherwise had
> expected it to be taken care of during setup. Passing grpc.WithBlock will
> take care of that now, but it also means that every client library that
> builds on top of gRPC needs to have a mechanism to pass that through too.
>
> The second aspect that makes this feel weird to me is error handling:
> Generally, if dialing outright fails, it is a permanent failure (e.g.
> malformed address), and your program can't do anything else at that point;
> however, an RPC failing is often not a permanent problem, and a program can
> keep going. Pushing the actual dial back to the first RPC means that
> programs need to put more thought into handling RPC errors than they would
> otherwise have to, which means most programs will behave poorly.
>
> I'm not too fussed about being consistent with C and Java on every last
> detail. This might be a situation where it makes sense to be consistent,
> but just saying "C and Java also do this" isn't a trump card, because we
> intentionally diverge from them in many places where we judge it to be
> better.
>
I did not mean I am doing this because "C and Java also do this". I was
just telling the situation. It is is a reason but not "a trump card". The
default would be the one most users choose to use. According to my
experience on google internal rpc framework in C++ and what I was told from
Bryan and Sameer regarding Go internal, it seems skip wait is the way most
ppl preferred. It saves some resources (1 fd, some mem ~8KB) and is
essential for load balance channel when it consists of a large number of
subchannels.

**Comment by dsymonds** [comment]
I have a different experience inside Google to Bryan and Sameer, but I'd still like to hear a concrete reason why a non-blocking dial is a better default. Maybe there's a good reason and I've simply forgotten it.

Saving a small amount of memory doesn't seem like a big pay-off, and most uses of `grpc.Dial` are dialing a TCP connection so load balancing is irrelevant for them (since the multiplexing happens in the single HTTP2 connection, not over multiple TCP connections).

**Comment by iamqizhao** [comment]
Moved this discussion to internal temporarily ...

**Comment by iamqizhao** [comment]
Will have a new one according to the decision via the internal discussion.

**Pull request closed without merging**
