### PR TITLE
Disallow using timeout without block option

### PR DESCRIPTION
**Pull request by gm42**
I believe explaining in a comment how the options should be used it's not enough (although I am also a strong supporter of the RTFM mantra).

I might go as far as proposing that `.WithTimeout()` always sets `.WithBlock()`, but IMO some change is necessary to prevent invalid usages of the client.

### CODE REVIEW

**Comment by gm42** [comment]
I signed it

**Comment by iamqizhao** [comment]
can you test it?

**Comment by gm42** [comment]
@iamqizhao my test with:
```
		conn, err := grpc.Dial("localhost:81", grpc.WithInsecure(), grpc.WithBlock(), grpc.WithTimeout(time.Second * 5))
		if err != nil {
			log.WithError(err).Fatalln("failed to create connection to myservice")
		}
```

gives the expected:
```
FATA[0000] failed to create connection to myservice          app=myapp error=grpc: timeout options requires block option
```

If I use instead:
```
		conn, err := grpc.Dial("localhost:81", grpc.WithInsecure(), grpc.WithBlock(), grpc.WithTimeout(time.Second * 5))
		if err != nil {
			log.WithError(err).Fatalln("failed to create connection to myservice")
		}
```

Then it works without any error.

**Comment by menghanl** [comment]
It's recommended to use DialContext instead of WithTimeout dial option.
Added doc in #1333.
Closing this PR.

**Pull request closed without merging**
