### PR TITLE
cmd/protoc-gen-go-grpc: update google.golang.org/protobuf to v1.27.1

### LINKED ISSUE #5049: protoc-gen-go-grpc: generates wrong package name on macOS
### What version of gRPC are you using?

current tip of the master branch: d35aff3c836a77e714eb1c86c8aab963560f043c

### What version of Go are you using (`go version`)?

```
go version go1.16.2 darwin/amd64
```

### What operating system (Linux, Windows, …) and version?

```
Darwin 20.6.0 x86_64
```

### What did you do?

I ran the following commands:

```shell
git clone https://github.com/grpc/grpc-go.git
cd grpc-go/examples/helloworld

sed -i 's/^option go_package.*$//' helloworld/helloworld.proto
sed -i 's/^package helloworld/package foo.bar.helloworld/' helloworld/helloworld.proto


protoc \
  --go_out=. \
  --go_opt=module=google.golang.org/grpc \
  --go_opt=Mhelloworld/helloworld.proto=google.golang.org/grpc/examples/helloworld \
  \
  --go-grpc_out=. \
  --go-grpc_opt=module=google.golang.org/grpc \
  --go-grpc_opt=Mhelloworld/helloworld.proto=google.golang.org/grpc/examples/helloworld \
  \
  ./helloworld/helloworld.proto \


go build ./examples/helloworld/
```

The first `sed` command removes the go package option from the proto file. But we later explicitly pass in our desired go package name via `--go-grpc_opt=M` in the `protoc` execution.

### What did you expect to see?

I expect the generated package ` ./examples/helloworld/` to be able to compile. In other words, I expect the `go build ./examples/helloworld/` command to succeed.

### What did you see instead?

`go build ./examples/helloworld/` fails with:

```
found packages helloworld (helloworld.pb.go) and foo_bar_helloworld (helloworld_grpc.pb.go) in /Users/sding/go/src/grpc-go/examples/helloworld/examples/helloworld
```

This is due to ` ./examples/helloworld/helloworld_grpc.pb.go` having a wrong package name of `foo_bar_helloworld`, which differs from the correct package name `helloworld`.

` ./examples/helloworld/helloworld.pb.go`, on the other hand, has the correct package name of `helloworld`.

This impacts macOS. I cannot reproduce this issue on Linux.

### PR DESCRIPTION
**Pull request by sding3**
fixes #5049

Upgrade `google.golang.org/protobuf` from `v1.23.0` to `v1.27.1`

RELEASE NOTES: N/A

### CODE REVIEW

**Review by menghanl — APPROVED** [review]

**Comment by menghanl** [comment]
proto generation is failing because of https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0#user-content-v1.26-require-import-path
Package is required now, but some of our protos don't specify them?

```
 ./regenerate.sh
remove existing generated files
go install google.golang.org/protobuf/cmd/protoc-gen-go
go install cmd/protoc-gen-go-grpc
git clone https://github.com/grpc/grpc-proto
git clone https://github.com/protocolbuffers/protobuf
curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/rpc/code.proto
protoc examples/features/proto/echo/echo.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc examples/helloworld/helloworld/helloworld.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc examples/route_guide/routeguide/route_guide.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc reflection/grpc_testing/proto2.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc reflection/grpc_testing/proto2_ext.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc reflection/grpc_testing/proto2_ext2.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc reflection/grpc_testing/test.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc reflection/grpc_testingv3/testv3.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc stress/grpc_testing/metrics.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc test/codec_perf/perf.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc test/grpc_testing/test.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc /tmp/tmp.ngPqribxfm/grpc-proto/grpc/gcp/altscontext.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc /tmp/tmp.ngPqribxfm/grpc-proto/grpc/gcp/handshaker.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc /tmp/tmp.ngPqribxfm/grpc-proto/grpc/gcp/transport_security_common.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc /tmp/tmp.ngPqribxfm/grpc-proto/grpc/lookup/v1/rls.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc /tmp/tmp.ngPqribxfm/grpc-proto/grpc/lookup/v1/rls_config.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc /tmp/tmp.ngPqribxfm/grpc-proto/grpc/service_config/service_config.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
protoc /tmp/tmp.ngPqribxfm/grpc-proto/grpc/testing/benchmark_service.proto
/tmp/tmp.ngPqribxfm/istio: warning: directory does not exist.
2021/12/10 10:12:19 WARNING: Missing 'go_package' option in "grpc/testing/messages.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:12:19 WARNING: Missing 'go_package' option in "grpc/testing/benchmark_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc-gen-go-grpc: unable to determine Go import path for "grpc/testing/messages.proto"

Please specify either:
	• a "go_package" option in the .proto source file, or
	• a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go-grpc_out: protoc-gen-go-grpc: Plugin failed with status code 1.
```

**Comment by menghanl** [comment]
This is the output of a successful run on master, with the old proto generator.
It seems many of the protos from the grpc-proto repo don't have packages.

```
$  ./regenerate.sh
remove existing generated files
go install google.golang.org/protobuf/cmd/protoc-gen-go
go install cmd/protoc-gen-go-grpc
git clone https://github.com/grpc/grpc-proto
git clone https://github.com/protocolbuffers/protobuf
curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/rpc/code.proto
protoc examples/features/proto/echo/echo.proto
protoc examples/helloworld/helloworld/helloworld.proto
protoc examples/route_guide/routeguide/route_guide.proto
protoc reflection/grpc_testing/proto2.proto
protoc reflection/grpc_testing/proto2_ext.proto
protoc reflection/grpc_testing/proto2_ext2.proto
protoc reflection/grpc_testing/test.proto
protoc reflection/grpc_testingv3/testv3.proto
protoc stress/grpc_testing/metrics.proto
protoc test/codec_perf/perf.proto
protoc test/grpc_testing/test.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/gcp/altscontext.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/gcp/handshaker.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/gcp/transport_security_common.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/lookup/v1/rls.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/lookup/v1/rls_config.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/service_config/service_config.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/benchmark_service.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/messages.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/benchmark_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/messages.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/benchmark_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/control.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/control.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/control.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/empty.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/empty.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/empty.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/messages.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/messages.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/messages.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/payloads.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/report_qps_scenario_service.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/control.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/report_qps_scenario_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/control.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/report_qps_scenario_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/stats.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/test.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/empty.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/messages.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/test.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/empty.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/messages.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/test.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/testing/worker_service.proto
2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/control.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/worker_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/payloads.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/stats.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/control.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2021/12/10 10:30:40 WARNING: Missing 'go_package' option in "grpc/testing/worker_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/core/stats.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/binlog/v1/binarylog.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/channelz/v1/channelz.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/health/v1/health.proto
protoc /tmp/tmp.eLWOVbIMJE/grpc-proto/grpc/lb/v1/load_balancer.proto
protoc profiling/proto/service.proto
protoc reflection/grpc_reflection_v1alpha/reflection.proto
```

**Comment by menghanl** [comment]
I pushed a commit to this PR, to fix the proto regenerating script.

**Comment by sding3** [comment]
Thanks for fixing that.

**Review by dfawley — APPROVED** [review]

**Pull request merged**
