### PR TITLE
.*: fix revive lint issues `unused-parameter`

### PR DESCRIPTION
**Pull request by janardhanvissa**
Addresses: https://github.com/grpc/grpc-go/issues/7444

RELEASE NOTES: None

### CODE REVIEW

**Comment by purnesh42H** [comment]
There are still some `unused-parameter` left https://github.com/grpc/grpc-go/actions/runs/10641877632/job/29503596628?pr=7580. Please fix

**Comment by janardhanvissa** [comment]
@purnesh42H Fixed all the unused-parameter linter issues.

**Review by purnesh42H — APPROVED** [review]
lgtm

**Comment by purnesh42H** [comment]
@arvindbr8 for another review

**Review by arvindbr8 — APPROVED** [review]

**Pull request merged**
