### PR TITLE
xds: split routing balancer into config selector + cluster manager

### PR DESCRIPTION
**Pull request by dfawley**
Also contains #4082.

Still TBD: add some system-level tests.  But this seems to be complete enough to at least start the review process.  I'd recommend filtering out the first commit, then start with the clustermanager LB policy, then the resolver changes.

Unfortunately, this is hard to make smaller.  I could add the cluster manager LB policy in a separate PR + keep the routing LB policy, and then make the resolver changes + delete the routing LB policy.  But this way seems better as it allows git to recognize some of the files that were moved to reduce the diffs a bit.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)

### CODE REVIEW

**Review by menghanl — CHANGES_REQUESTED** [review]
> Reviewed 19 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: 19 of 35 files reviewed, 7 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[xds/internal/balancer/balancer.go, line 26 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzJKffEg9mCcxcd6Cg:-MNzJKffEg9mCcxcd6Ch:b-8513re) ([raw file](https://github.com/grpc/grpc-go/blob/0d6a24f68a5f9a38c64be00364587becb0e40518/xds/internal/balancer/balancer.go#L26)):*
> ```Go
> 	_ "google.golang.org/grpc/xds/internal/balancer/edsbalancer"    // Register the EDS balancer
> 	_ "google.golang.org/grpc/xds/internal/balancer/weightedtarget" // Register the weighted_target balancer
> 	_ "google.golang.org/grpc/xds/internal/balancer/xdsrouting"     // Register the xds_routing balancer
> ```

Do you not need to register the new balancer?
___
*[xds/internal/balancer/clustermanager/clustermanager.go, line 91 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzXdRzCbaU0Q7p62Sa:-MNzXdS-8ngHvki2fQ3Z:bn8pj57) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/clustermanager.go#L91)):*
> ```Go
> 	for name, newT := range newConfig.Children {
> 		if _, ok := b.children[name]; !ok {
> 			// If this is a new sub-balancer, add weights to the picker map.
> ```

No `weights`
___
*[xds/internal/balancer/clustermanager/config_test.go, line 39 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzazTI8_MqZINAXDRW:-MNzazTI8_MqZINAXDRX:boivtv5) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/config_test.go#L39)):*
> ```Go
>           }]
>         },
>         "weighted:cluster_1_cluster_2_1":{
> ```

Keeping this is OK. But in practice, all children of this balancer will be just CDS.
___
*[xds/internal/balancer/clustermanager/picker.go, line 50 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzL7XFAffvusOby2zF:-MNzL7XGAL-7dRdre2Pc:b-4ky0mc) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/picker.go#L50)):*
> ```Go
> 		return p.Pick(info)
> 	}
> 	return balancer.PickResult{}, status.Errorf(codes.Unavailable, "unknown cluster selected for RPC: %q", cluster)
> ```

Make the var for this error.
___
*[xds/internal/resolver/matcher.go, line 44 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzZ49vCytHiNnsZGx6:-MNzZ49vCytHiNnsZGx7:bmuqm1u) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/resolver/matcher.go#L44)):*
> ```Go
> 	case r.Path != nil && *r.Path != "":
> 		pathMatcher = newPathExactMatcher(*r.Path, r.CaseInsensitive)
> 	default:
> ```

It should probably default to return error?
In routing balancer, it would fail when parsing the service config.

And also routing balancer would fail if more than one of them is non-nil.
https://github.com/grpc/grpc-go/blob/bce1fdfad97e977caa8d0ff9fb7b42dbeddecd28/xds/internal/balancer/xdsrouting/routing_config.go#L164
___
*[xds/internal/resolver/matcher.go, line 70 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzZBJ_0Pr9cRBq4NtO:-MNzZBJ_0Pr9cRBq4NtP:bnqy6rr) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/resolver/matcher.go#L70)):*
> ```Go
> 		case h.RangeMatch != nil:
> 			matcherT = newHeaderRangeMatcher(h.Name, h.RangeMatch.Start, h.RangeMatch.End)
> 		default:
> ```

Same as path. Error?
___
*[xds/internal/balancer/clustermanager/clustermanager_test.go, line 181 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzbO327brWAhjiBd65:-MNzbO327brWAhjiBd66:bmlbwam) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/clustermanager_test.go#L181)):*
> ```Go
> 		{
> 			pickInfo: balancer.PickInfo{
> 				FullMethodName: "/a/1",
> ```

What's different between this and the one above?
Is this supposed to test `FullMethodName` doesn't affect the pick result?

**Review by menghanl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: 19 of 35 files reviewed, 7 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[xds/internal/resolver/matcher.go, line 44 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzZ49vCytHiNnsZGx6:-MO-hOvNANchEedVuDoP:b-vgfv4w) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/resolver/matcher.go#L44)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

It should probably default to return error?
In routing balancer, it would fail when parsing the service config.

And also routing balancer would fail if more than one of them is non-nil.
https://github.com/grpc/grpc-go/blob/bce1fdfad97e977caa8d0ff9fb7b42dbeddecd28/xds/internal/balancer/xdsrouting/routing_config.go#L164
</blockquote></details>

Actually, since this is a proto `oneof`, it can never have more than one.
But it can have none, and we should just skip this route in that case. Another question is, do we keep its action child policy (since it will never be picked)?

**Review by dfawley — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: 19 of 35 files reviewed, 7 unresolved discussions (waiting on @menghanl)

___
*[xds/internal/balancer/balancer.go, line 26 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzJKffEg9mCcxcd6Cg:-MO2pks1AE3RmmLywxdZ:b-555696) ([raw file](https://github.com/grpc/grpc-go/blob/0d6a24f68a5f9a38c64be00364587becb0e40518/xds/internal/balancer/balancer.go#L26)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Do you not need to register the new balancer?
</blockquote></details>

It's right above here ("// Register the xds_cluster_manager balancer").
___
*[xds/internal/balancer/clustermanager/clustermanager.go, line 91 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzXdRzCbaU0Q7p62Sa:-MO2qVF1A2hyeTxWx4Xz:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/clustermanager.go#L91)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

No `weights`
</blockquote></details>

Done.
___
*[xds/internal/balancer/clustermanager/config_test.go, line 39 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzazTI8_MqZINAXDRW:-MO2rDNQ1YvEO3IZ2hSV:b-nrcbr5) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/config_test.go#L39)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Keeping this is OK. But in practice, all children of this balancer will be just CDS.
</blockquote></details>

Agreed; I decided to leave this in since the design allows us to use things other than CDS.
___
*[xds/internal/balancer/clustermanager/picker.go, line 50 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzL7XFAffvusOby2zF:-MO38hUuDjVbnqTViruF:b-9o64tk) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/picker.go#L50)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Make the var for this error.
</blockquote></details>

I'm not sure what you mean here.
___
*[xds/internal/resolver/matcher.go, line 44 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzZ49vCytHiNnsZGx6:-MO35nYl2VuyJtNg2RQP:b-6po3d8) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/resolver/matcher.go#L44)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Actually, since this is a proto `oneof`, it can never have more than one.
But it can have none, and we should just skip this route in that case. Another question is, do we keep its action child policy (since it will never be picked)?
</blockquote></details>

Envoy says this is required: https://github.com/envoyproxy/envoy/blob/fa80297f80728ec96b015b3f569695ff39750427/api/envoy/api/v2/route/route_components.proto#L392

So if it's missing, we have 3 options: 1. error the config (w/nack), 2. ignore the whole config, or 3. ignore the route.  Looks like we were and are doing (3), as the xds client just skips routes without a path_matcher or without a header_match_specifier.

https://github.com/grpc/grpc-go/blob/96a834a12f8bfdf3a2c27b72e7ef0c51a795710e/xds/internal/client/client_xds.go#L273-L274

Should we nack by returning an error from there instead?
___
*[xds/internal/resolver/matcher.go, line 70 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzZBJ_0Pr9cRBq4NtO:-MO38L9908fTLKuiHK8H:b-tv12v5) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/resolver/matcher.go#L70)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Same as path. Error?
</blockquote></details>

I think this would be the same.
___
*[xds/internal/balancer/clustermanager/clustermanager_test.go, line 181 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzbO327brWAhjiBd65:-MO2qcyA9CLXfGUXDu1p:bq1vpcr) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/balancer/clustermanager/clustermanager_test.go#L181)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

What's different between this and the one above?
Is this supposed to test `FullMethodName` doesn't affect the pick result?
</blockquote></details>

True, this isn't really useful.  I just removed "FullMethodName" entirely since nothing in the code looks at it.

**Review by menghanl — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: 19 of 35 files reviewed, 2 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[xds/internal/balancer/balancer.go, line 26 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzJKffEg9mCcxcd6Cg:-MO7dq8aDcN4MSb4v7Wz:b-8bjin8) ([raw file](https://github.com/grpc/grpc-go/blob/0d6a24f68a5f9a38c64be00364587becb0e40518/xds/internal/balancer/balancer.go#L26)):*
<details><summary><i>Previously, dfawley (Doug Fawley) wrote…</i></summary><blockquote>

It's right above here ("// Register the xds_cluster_manager balancer").
</blockquote></details>

AHHHH
___
*[xds/internal/resolver/matcher.go, line 44 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzZ49vCytHiNnsZGx6:-MO7fOq26bd9RPnAdJFK:b-rjul4u) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/resolver/matcher.go#L44)):*
<details><summary><i>Previously, dfawley (Doug Fawley) wrote…</i></summary><blockquote>

Envoy says this is required: https://github.com/envoyproxy/envoy/blob/fa80297f80728ec96b015b3f569695ff39750427/api/envoy/api/v2/route/route_components.proto#L392

So if it's missing, we have 3 options: 1. error the config (w/nack), 2. ignore the whole config, or 3. ignore the route.  Looks like we were and are doing (3), as the xds client just skips routes without a path_matcher or without a header_match_specifier.

https://github.com/grpc/grpc-go/blob/96a834a12f8bfdf3a2c27b72e7ef0c51a795710e/xds/internal/client/client_xds.go#L273-L274

Should we nack by returning an error from there instead?
</blockquote></details>

`path_specifier` is required, and we do [NACK if it's missing](https://github.com/grpc/grpc-go/blob/bce1fdfad97e977caa8d0ff9fb7b42dbeddecd28/xds/internal/client/client_xds.go#L259).

But none of it's fields is required. So it could have an empty `path_specifier`.
This could be a valid case if a new `oneof` is added later. Then the client will just ignore this route, instead of NACK.
I think in general, we don't want to be too strict on this.

Ignoring this route SGTM. But confirm with the other languages?

**Review by menghanl — CHANGES_REQUESTED** [review]
> Reviewed 12 of 35 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: 32 of 35 files reviewed, 9 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[xds/internal/resolver/matcher.go, line 36 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8QZFY0LolCdLgmBbX:-MO8QZFY0LolCdLgmBbY:b-woqbzq) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/matcher.go#L36)):*
> ```Go
> 	var pathMatcher pathMatcherInterface
> 	switch {
> 	case r.Regex != nil && *r.Regex != "":
> ```

Why cannot Regex be an empty string? I think we can just check `nil` here.
___
*[xds/internal/resolver/serviceconfig.go, line 62 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8TLhZ7oKmR53Qpjse:-MO8TLh_BuEAH01yBGwK:bo3d6mf) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L62)):*
> ```Go
> // serviceConfigJSON produces a service config in JSON format representing all
> // the clusters currently referenced by RPCs and the latest config selector.
> func (r *xdsResolver) serviceConfigJSON() (string, error) {
> ```

Cover this in a test?
___
*[xds/internal/resolver/serviceconfig.go, line 125 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8uWZc5rNnVfDN9ZlR:-MO8uJ6h57S-ihDr-nY5:bdngibo) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L125)):*
> ```Go
> 		Context: clustermanager.SetPickedCluster(rpcInfo.Context, cluster),
> 		OnCommitted: func() {
> 			if v := atomic.AddInt32(ref, -1); v == 0 {
> ```

Do we have test case covering this?
___
*[xds/internal/resolver/serviceconfig.go, line 164 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8Z0I718c7Spbh0dD6:-MO8Z0I718c7Spbh0dD7:b-dr34hv) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L164)):*
> ```Go
> }
> 
> func (r *xdsResolver) serviceUpdateToCS(su serviceUpdate) (*configSelector, error) {
> ```

Add more comments to the functions around config selector and activeCluster. This part is fairly complex.
___
*[xds/internal/resolver/serviceconfig.go, line 184 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8YfS1ByZW_pVtrhir:-MO8YfS26SQKfy7KzuB7:b-kvbbbz) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L184)):*
> ```Go
> 		}
> 
> 		for cluster := range rt.Action {
> ```

Merge the `for  rt.Action` above into this?
___
*[xds/internal/resolver/xds_resolver.go, line 156 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8XDEOBqNuo5-akBBd:-MO8XDEOBqNuo5-akBBe:bnni5w6) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/xds_resolver.go#L156)):*
> ```Go
> 				var err error
> 				if cs, err = r.serviceUpdateToCS(update.su); err != nil {
> 					r.logger.Warningf("%v", err)
> ```

Does the error have enough context for this log line?
___
*[xds/internal/resolver/matcher_test.go, line 148 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8RlWI8WlzVgPV6pvV:-MO8RlWI8WlzVgPV6pvW:bldkl3w) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/matcher_test.go#L148)):*
> ```Go
> }
> 
> func (a *compositeMatcher) equal(mm *compositeMatcher) bool {
> ```

If you deleted this from non-test because the code never needs it, why do you keep it in the tests?

**Review by dfawley — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: 32 of 35 files reviewed, 9 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[xds/internal/resolver/matcher.go, line 44 at r1](https://reviewable.io/reviews/grpc/grpc-go/4083#-MNzZ49vCytHiNnsZGx6:-MOHh-293pI8KlcnXXqn:b-bx10oh) ([raw file](https://github.com/grpc/grpc-go/blob/fa6cdcc75777c58bfc607ba32c02a9df53a6107c/xds/internal/resolver/matcher.go#L44)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

`path_specifier` is required, and we do [NACK if it's missing](https://github.com/grpc/grpc-go/blob/bce1fdfad97e977caa8d0ff9fb7b42dbeddecd28/xds/internal/client/client_xds.go#L259).

But none of it's fields is required. So it could have an empty `path_specifier`.
This could be a valid case if a new `oneof` is added later. Then the client will just ignore this route, instead of NACK.
I think in general, we don't want to be too strict on this.

Ignoring this route SGTM. But confirm with the other languages?
</blockquote></details>

Confirmed that we need to nack if it has an empty path_specifier; we'll make this change later.
___
*[xds/internal/resolver/matcher.go, line 36 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8QZFY0LolCdLgmBbX:-MOHh9nK--jl-HVI-CA6:b-j2c8cf) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/matcher.go#L36)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Why cannot Regex be an empty string? I think we can just check `nil` here.
</blockquote></details>

This was as it existed before.  Should we do the same for the Path matcher?  Even though it's not likely to match since it's a full match in this case, it seems valid (i.e. shouldn't result in an error).
___
*[xds/internal/resolver/serviceconfig.go, line 62 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8TLhZ7oKmR53Qpjse:-MOHjkTc1i78IoandBNZ:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L62)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Cover this in a test?
</blockquote></details>

Done.
___
*[xds/internal/resolver/serviceconfig.go, line 125 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8uWZc5rNnVfDN9ZlR:-MOHmeIuCfMNpfNfYayc:b-8b11j9) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L125)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Do we have test case covering this?
</blockquote></details>

Added
___
*[xds/internal/resolver/serviceconfig.go, line 164 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8Z0I718c7Spbh0dD6:-MOHntut8AJEBPKx5P8B:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L164)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Add more comments to the functions around config selector and activeCluster. This part is fairly complex.
</blockquote></details>

Done.
___
*[xds/internal/resolver/serviceconfig.go, line 184 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8YfS1ByZW_pVtrhir:-MOHoAp7Ee8dllflMtZS:b-896fix) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/serviceconfig.go#L184)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Merge the `for  rt.Action` above into this?
</blockquote></details>

Done.
___
*[xds/internal/resolver/xds_resolver.go, line 156 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8XDEOBqNuo5-akBBd:-MOHok5o6mijNPpNE-j6:bubkiz5) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/xds_resolver.go#L156)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Does the error have enough context for this log line?
</blockquote></details>

Improved
___
*[xds/internal/resolver/matcher_test.go, line 148 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8RlWI8WlzVgPV6pvV:-MOHiShh7SGUK8_xGPBt:b-ut0hcd) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/matcher_test.go#L148)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

If you deleted this from non-test because the code never needs it, why do you keep it in the tests?
</blockquote></details>

Because the tests use it for correctness.

**Comment by dfawley** [comment]
I'll leave the merge conflict for now to make the PR easier to review (although reviewable does handle this more gracefully than github).

**Review by menghanl — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: all files reviewed, 4 unresolved discussions (waiting on @dfawley)

___
*[xds/internal/resolver/matcher.go, line 36 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8QZFY0LolCdLgmBbX:-MObXPkQ2BBoUJtKh79l:barf2w8) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/matcher.go#L36)):*
<details><summary><i>Previously, dfawley (Doug Fawley) wrote…</i></summary><blockquote>

This was as it existed before.  Should we do the same for the Path matcher?  Even though it's not likely to match since it's a full match in this case, it seems valid (i.e. shouldn't result in an error).
</blockquote></details>

We check for `""` because this field in the old config is not a pointer. So `""` means it's not set.
Now that this is a pointer, we should only check `nil`. And if `Regex` is the only set one, and is `""`, we should use it, though it might not match anything.

And I think we should do the same for headers.
___
*[xds/internal/resolver/serviceconfig.go, line 196 at r4](https://reviewable.io/reviews/grpc/grpc-go/4083#-MObZ7TtDq26vO8HmdNb:-MObZ7TtDq26vO8HmdNc:b-56134y) ([raw file](https://github.com/grpc/grpc-go/blob/06855e622a9e867b2f6a5b2b01516840cf295070/xds/internal/resolver/serviceconfig.go#L196)):*
> ```Go
> 
> 	for i, rt := range su.Routes {
> 		action := wrr.NewRandom()
> ```

Do we have a test to cover the WRR behavior? Do we want one? We will need to override the WRR algorithm for that.
___
*[xds/internal/resolver/serviceconfig_test.go, line 3 at r4](https://reviewable.io/reviews/grpc/grpc-go/4083#-MOb_Jwe0Run29VyS_Lw:-MOb_Jwf6cJMXAEFFZsA:bb6ht35) ([raw file](https://github.com/grpc/grpc-go/blob/06855e622a9e867b2f6a5b2b01516840cf295070/xds/internal/resolver/serviceconfig_test.go#L3)):*
> ```Go
> /*
>  *
>  * Copyright 2019 gRPC authors.
> ```

2020
___
*[xds/internal/resolver/matcher_test.go, line 148 at r2](https://reviewable.io/reviews/grpc/grpc-go/4083#-MO8RlWI8WlzVgPV6pvV:-MObY4Td9YyR2tXnfw-K:b-kntdc1) ([raw file](https://github.com/grpc/grpc-go/blob/20599fc89a241e3b8bea8a2d655c8b627b5b1f1e/xds/internal/resolver/matcher_test.go#L148)):*
<details><summary><i>Previously, dfawley (Doug Fawley) wrote…</i></summary><blockquote>

Because the tests use it for correctness.
</blockquote></details>

Which test needs this? I thought it's only called by `TestCompositeMatcherEqual`, which is testing `equal`.

**Comment by dfawley** [comment]
> we should use it, though it might not match anything.

Wouldn't a `""` regex match everything?

> And I think we should do the same for headers.

Done.

> Do we have a test to cover the WRR behavior? Do we want one? We will need to override the WRR algorithm for that.

I added a test.

> 2020

Done.

> Which test needs this? I thought it's only called by TestCompositeMatcherEqual, which is testing equal.

Yes, but `compositeMatcher.equal` needs `fractionMatcher.equal`.

**Comment by menghanl** [comment]
> > we should use it, though it might not match anything.
> 
> Wouldn't a `""` regex match everything?

I don't speak regex. Is "" a valid regex?
And even if it matches everything, we should still use it if it's set.

> 
> > Which test needs this? I thought it's only called by TestCompositeMatcherEqual, which is testing equal.
> 
> Yes, but `compositeMatcher.equal` needs `fractionMatcher.equal`.

Delete `TestCompositeMatcherEqual`? Why do we test `equal` for `compositeMatcher` if we don't need them?

**Comment by dfawley** [comment]
> I don't speak regex. Is "" a valid regex?
> And even if it matches everything, we should still use it if it's set.

Yes, and it matches everything.  Already done.

> Delete TestCompositeMatcherEqual? Why do we test equal for compositeMatcher if we don't need them?

You know..that's a really good idea.  Deleted all the `equals` since we no longer need to check for matcher equality.  I actually didn't look at the test very closely, and assumed it was testing correctness of the matchers.

**Review by menghanl — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: 34 of 35 files reviewed, 4 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[xds/internal/resolver/xds_resolver_test.go, line 380 at r5](https://reviewable.io/reviews/grpc/grpc-go/4083#-MOcI7ItDIM0nxiXWzEz:-MOcI7IuD8kzwrJIPP6f:bh8k7i2) ([raw file](https://github.com/grpc/grpc-go/blob/667d669e37c7d793a60e3f545cb088a2ee7d8517/xds/internal/resolver/xds_resolver_test.go#L380)):*
> ```Go
> 		}
> 
> 		pickedClusters := make(map[string]bool)
> ```

Where is `newWRR` replaced for this test?

Make it a `map[string]int` and check the count? Since now the wrr algorithm is reliable.
___
*[xds/internal/resolver/xds_resolver_test.go, line 434 at r5](https://reviewable.io/reviews/grpc/grpc-go/4083#-MOcIsw6CUQBvmBeblOk:-MOcIsw6CUQBvmBeblOl:b2cuvm2) ([raw file](https://github.com/grpc/grpc-go/blob/667d669e37c7d793a60e3f545cb088a2ee7d8517/xds/internal/resolver/xds_resolver_test.go#L434)):*
> ```Go
> 	waitForWatchRouteConfig(ctx, t, xdsC, routeStr)
> 
> 	fakePick := &fakeWRR{t: t, weights: map[string]int64{"A": 75, "B": 25}, ch: make(chan string, 1)}
> ```

Use this: https://github.com/grpc/grpc-go/blob/master/xds/internal/testutils/wrr.go#L27 ?

**Comment by dfawley** [comment]
> Where is newWRR replaced for this test?

It's not.  It's in the other test where I do that.

> Make it a map[string]int and check the count? Since now the wrr algorithm is reliable.

I considered that but this is fine - the other test checks that the WRR is being used correctly.

> Use this: master/xds/internal/testutils/wrr.go#L27 ?

Oh.  Done.

**Review by menghanl — APPROVED** [review]
> Reviewed 3 of 3 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4083)* status: all files reviewed, 4 unresolved discussions (waiting on @dfawley)

**Pull request merged**
