### PR TITLE
*: update all dependencies

### PR DESCRIPTION
**Pull request by dfawley**
Follow-on to #5874, but use `go get -u ./...` to update _all_ packages' dependencies, not just the dependencies of the root package of each module.

RELEASE NOTES: none

### CODE REVIEW

**Review by easwars — APPROVED** [review]
If the workspaces thingy can simplify dependency management for all modules (such that we depend on the same version of a library from all of our modules), it would be a win to do that.

**Comment by easwars** [comment]
Oops... looks like one of the dependencies isn't happy with Go1.17.

**Comment by dfawley** [comment]
> Oops... looks like one of the dependencies isn't happy with Go1.17.

Well what the heck does `-compat=1.17` mean then?!  I'll take a look.

**Comment by dfawley** [comment]
Reverted cel-go so it will work with 1.17, and update `vet.sh` to use `-compat=1.17` and ignore Go 1.16 preferences.  (I'm not entirely sure what this means; it if's better to "upgrade to the versions selected by go 1.16" then I can change it to `go mod tidy -go=1.16 && go mod tidy -go=1.17`.)

**Pull request merged**
