### PR TITLE
Fix too many ping

### PR DESCRIPTION
**Pull request by ZhiqinYang**
When concurrently call grpc client with keepalive, log print too many ping !

### CODE REVIEW

**Comment by canguler** [comment]
Hey @ZhiqinYang,

Could you please provide more context for the problem that this PR is attempting to solve?

**Comment by ZhiqinYang** [comment]
> Hey @ZhiqinYang,
> 
> Could you please provide more context for the problem that this PR is attempting to solve?



> Hey @ZhiqinYang,
> 
> Could you please provide more context for the problem that this PR is attempting to solve?
In my env, the connections will auto closed, I want to keep connection not closed, so I used the keepalive,
I have a request is  cost time more than one minutes,  I opened keepalive, the log see  too many pings.

**Comment by dfawley** [comment]
@ZhiqinYang have you configured keepalive enforcement on the server accordingly to match the client's pings?

https://godoc.org/google.golang.org/grpc/keepalive#EnforcementPolicy

**Comment by ZhiqinYang** [comment]
> @ZhiqinYang have you configured keepalive enforcement on the server accordingly to match the client's pings?
> 
> https://godoc.org/google.golang.org/grpc/keepalive#EnforcementPolicy

yes! I set like this : 
in client  side :

var DefaultKeepaliveParams = grpc.WithKeepaliveParams(keepalive.ClientParameters{
 52         Time:                20 * time.Second, 
 53         Timeout:             30 * time.Second,
 54         PermitWithoutStream: true,
 55 })`
`
in server side : 
`
KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
424                         MinTime:             10 * time.Second,
425                         PermitWithoutStream: true,
426                 }) 
`

**Comment by dfawley** [comment]
I'm not able to reproduce this with a simple test case.  The test case will send a ping every 10ms, and the server has a MinTime of 5ms.  Even with no activity and an active stream sleeping for 1 minute, the server correctly allows the pings.

Can you provide a reproduction case I can run that shows the problem you are seeing?

Note that pings are only sent every `Time + Timeout` period.  So in your parameters above, that's every 50s.  This is actually a bug and I will fix it soon.

**Comment by ZhiqinYang** [comment]
> I'm not able to reproduce this with a simple test case. The test case will send a ping every 10ms, and the server has a MinTime of 5ms. Even with no activity and an active stream sleeping for 1 minute, the server correctly allows the pings.
> 
> Can you provide a reproduction case I can run that shows the problem you are seeing?
> 
> Note that pings are only sent every `Time + Timeout` period. So in your parameters above, that's every 50s. This is actually a bug and I will fix it soon.
I thought this problem case may be by that each request with a ping req,  when the request no response (no data write to the header), the pingStrikes were not reset when keepalive sends ping req, the pingStrikes will increase!

**Comment by dfawley** [comment]
Ping strikes should always be zero if the client is respecting the server's setting (both `MinTime` and `PermitWithoutStream`).  In addition, they are reset to zero any time the server sends data.  If you can provide example code that I can run to see the problem you're seeing, that would be helpful.

**Pull request closed without merging**
