### PR TITLE
test/kokoro: apply xDS interop best practice (backport v1.39.x)

### PR DESCRIPTION
**Pull request by lidizheng**
As title. Related #5395.

This PR is generated by:
```
git cherry-pick a58adb03
git co master -- test/kokoro/xds_url_map.sh test/kokoro/xds_url_map.sh test/kokoro/xds_k8s_lb.sh test/kokoro/xds_k8s_lb.cfg
```

### CODE REVIEW

**Comment by lidizheng** [comment]
* [xds](http://sponge/cff34252-30e9-45a6-8815-5219d688b73d)
* [xds_v3](http://sponge/e1907424-7bf5-4980-9cc0-544280a70057)
* [xds_k8s_lb](http://sponge/025f3504-0750-4660-a512-00ba65af37e9)
* [xds_url_map](http://sponge/e5258cb6-5ad4-407c-8692-643d350d06a6)

**Review by dfawley — APPROVED** [review]

**Comment by lidizheng** [comment]
Deflake:

* [xds_k8s_lb](http://sponge/139a7c64-594a-497f-8af5-931829c3fb55)

**Comment by lidizheng** [comment]
The failure is very strange: https://screenshot.googleplex.com/4SJidr3EW7i4nVd

**Comment by lidizheng** [comment]
What was I thinking... Ring Hash is only available after v1.41.x: https://github.com/grpc/grpc/blob/master/doc/grpc_xds_features.md

So it's expected to fail on v1.39.x and v1.40.x.

**Comment by lidizheng** [comment]
There is a parallel issue needs to be merged before we turn the internal switch on to run all the new jobs: https://github.com/grpc/grpc/pull/29972.

This PR should be safe to merge at this moment.

@dfawley PTAL.

**Comment by lidizheng** [comment]
Also, the url-map test failure is expected, since Retry support was added in v1.41.x. The test case declared the support range correctly: https://github.com/grpc/grpc/blob/master/tools/run_tests/xds_k8s_test_driver/tests/url_map/retry_test.py

**Pull request merged**
