### PR TITLE
Add Stream.ClientTransport method

### PR DESCRIPTION
**Pull request by zombiezen**

### CODE REVIEW

**Comment by iamqizhao** [comment]
why is this needed? We should minimize the exported methods.

**Comment by zombiezen** [comment]
If you're trying to write functions that operate over any stream, then you can't write to the stream without having the `ClientTransport`.  You're forced to pass around the triple of (server transport, client transport, stream).  This would allow clients of `Stream` to only need the stream.

**Comment by iamqizhao** [comment]
On Fri, Jun 19, 2015 at 10:55 AM, Ross Light <notifications@github.com>
wrote:

> If you're trying to write functions that operate over any stream, then you
> can't write to the stream without having the ClientTransport. You're
> forced to pass around the triple of (server transport, client transport,
> stream). This would allow clients of Stream to only need the stream.
>
Yup, I thought about it too when I had to add ServerTransport for streaming
rpc. But It is a non-trivial refactoring of the current code. To me, it is
unpleasant to have what you have here as a separate PR. It will only
confuse the lib developers without the refactoring work I just mentioned
standing up.  I would suggest merging them as a single PR.

**Comment by zombiezen** [comment]
Fair enough. You're right that refactoring the `Write` method onto the Stream would be more ideal. I can wait for that.

**Pull request closed without merging**
