### PR TITLE
examples: add go.mod to make examples a separate module

### LINKED ISSUE #3539: Make examples a(n independent) module
### Use case(s) - what problem will this feature solve?

Making a copy and subsequently updating the `helloworld` example as part of the [Go Quick Start](https://grpc.io/docs/quickstart/go) is much more work than it should be.

An initial discussion with @dfawley can be found in https://github.com/grpc/grpc.io/pull/183#discussion_r407082058.

### Proposed Solution

Make then `examples` an independent module.

~Make `helloworld` an independent module.~
~While we're at it, the `route_guide` example should also be made into its own module.~

### PR DESCRIPTION
**Pull request by chalin**
Fixes #3539
Supersedes #3540

### CODE REVIEW

**Comment by dfawley** [comment]
Looks like the `examples` test doesn't like this:

https://travis-ci.org/github/grpc/grpc-go/jobs/676263348

Please also run `go mod tidy` so this creates a `go.sum` file.

**Comment by chalin** [comment]
We can't do much (including running `go mod tidy`) without either:
- A replace rule like:
  `go mod edit -replace google.golang.org/grpc@v1.29.0-dev.1=../../`
- Or an actual release `v1.29.0-dev.1` containing this PR.

I can add the replace rule for the purpose of testing, but of course we won't want to actually commit it.

Any other suggestions?

**Comment by dfawley** [comment]
> Or an actual release v1.29.0-dev.1 containing this PR.

Can we tag this commit with `v1.30.0-dev.1` (since this is `master` and it's on 1.30 now), and reference it in either the same commit -- if that works, which I think it would, even though it's a little paradoxical -- or a subsequent commit?

**Comment by chalin** [comment]
FYI, with the replace rule in the `examples/go.mod` file, all tests are passing, see https://travis-ci.org/github/grpc/grpc-go/builds/676339760:

> image

**Comment by chalin** [comment]
(I'm going to remove the replace rule now)

**Comment by chalin** [comment]
Without the replace rule, all tests pass except TESTEXTRAS, since v1.30.0-dev.1 is unknown revision: https://travis-ci.org/github/grpc/grpc-go/builds/676345662:

> image

**Comment by chalin** [comment]
How would you like to proceed? Given that all tests pass when a `grpc` package can be found (as shown earlier), maybe consider merging this, and tagging the resulting `master` branch head as `v1.30.0-dev.1`?

**Comment by dfawley** [comment]
> How would you like to proceed? Given that all tests pass when a grpc package can be found (as shown earlier), maybe consider merging this, and tagging the resulting master branch head as v1.30.0-dev.1?

Did you try tagging your commit in your branch?  I'm not sure that will work, but it might be worth a shot.  Otherwise I can force merge this and then add the tag after.

**Comment by chalin** [comment]
> Did you try tagging your commit in your branch? I'm not sure that will work, but it might be worth a shot. Otherwise I can force merge this and then add the tag after.

Ok, I've tagged the commit and pushed:

```console
$ git push origin v1.30.0-dev.1
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/chalin/grpc-go.git
 * [new tag]           v1.30.0-dev.1 -> v1.30.0-dev.1
```

Can you restart [Travis build #9802](https://travis-ci.org/github/grpc/grpc-go/builds/676345662)? (I don't have the permissions to do so.)

**Comment by dfawley** [comment]
I kicked travis; the EXTRAS run is still failing:

```
 testing: helloworld 
+go build -o /dev/null ./helloworld/greeter_server/main.go
go: google.golang.org/grpc@v1.30.0-dev.1: reading google.golang.org/grpc/go.mod at revision v1.30.0-dev.1: unknown revision v1.30.0-dev.1
```

I _think_ this is because `go` is looking for the tag on github, and it isn't there yet, since it's in this PR.  Since it passes with the replace and fails with this message without the replace, then I think we can safely merge this as-is.  If github doesn't accept your tag, I'll apply it manually on this commit afterwards.

I'll do this on Monday unless anyone raises any concerns.

**Comment by chalin** [comment]
Thanks for restarting the build. I also suspected that `go` wouldn't look for tags on anything other than the main repo's `master` branch. Monday's is good. Have a great weekend!

**Comment by chalin** [comment]
> I'll do this on Monday unless anyone raises any concerns.

Still slated to try this today?

**Comment by chalin** [comment]
@dfawley - FYI, now that this has been published, my tests work locally, w/o using the replace rule. Maybe the [latest TESTEXTRAS Travis job](https://travis-ci.org/github/grpc/grpc-go/jobs/677804978) just needs to be restarted. Could you try that?

**Comment by chalin** [comment]
Hurray, the build is green! https://travis-ci.org/github/grpc/grpc-go/builds/677804973
Thanks @dfawley for help in moving this forward!

**Comment by dfawley** [comment]
Everything does seem happy now (it took a few minutes for the go sum DB to be updated, during which time I was mildly concerned)!  @chalin will you be making updates to the quick start guide next?

**Comment by chalin** [comment]
> ... will you be making updates to the quick start guide next?

Yes, that is at the top of my to-do list!

**Pull request merged**
