### PR TITLE
Multi interceptor

### PR DESCRIPTION
**Pull request by peter-edge**
@iamqizhao I know you may hate this and I apologize if so, I promise I send this PR in goodwill and just wanted to show you what I was talking about in the hopes you would agree it's a benefit. This allows multiple interceptors, with no impact on having a single interceptor. @mwitkow

### CODE REVIEW

**Comment by peter-edge** [comment]
+cc other people discussing interceptors @maniksurtani @nictuku @zellyn @bradfitz

**Comment by chancez** [comment]
It might be useful to provide a snippet of how this is accomplished without this PRs changes. Much like `net/http` chaining multiple handlers is implemented by the user, rather than the library, and I think it might make sense to have it work that way here, but seeing a comparison would be useful I think.

**Comment by peter-edge** [comment]
Hey @chancez, I think this would just be exposing `newMultiUnaryServerInterceptor` and `newMultiStreamServerInterceptor` as public functions, right? Am I missing something?

That is another way to do it, but I would argue it would be better to embed this directly as part of the library - there's no cost to doing so (if you specify one interceptor only, the code path is the same as before), and it prevents fragmentation in regards to what end users do. I think a lot of people will expect to be able to specify multiple interceptors.

**Comment by kazegusuri** [comment]
I have implemented my own version of `NewMultiUnaryServerInterceptor` which is almost same to this PR.
I think just exposing `NewMultiUnaryServerInterceptor` is enough for simplicity, but direct handling of multi interceptor is better for users.
In either case, grpc-go should provide the functionality. Otherwise, everyone have own implementation of `MultiUnaryServerInterceptor`.

**Comment by maniksurtani** [comment]
Nice. +1 to providing this as a part of the library, as @kazegusuri pointed out, to prevent multiple implementations emerging (something I think is bound to happen if the library doesn't provide such widely useful capability).

**Comment by peter-edge** [comment]
ping, probably specifically @iamqizhao , any thoughts?

**Comment by mwitkow** [comment]
I agree, having multi-interceptor design would be great.

We're currently in the process of moving from our own internal implementation of interceptors to upstream. @iamqizhao @menghanl, can we have this multi support upstream or should we roll our own?

**Comment by iamqizhao** [comment]
Please roll your own. It is important to minimize the public API for gRPC-Go at the current stage (we already have massive public API). Otherwise I can see we would easily run into API stability and maintenance problems when more and more new feature requests pop out in the future. I also think providing multiple ways to users for a single purpose sometimes hurts the user experience.

**Comment by mwitkow** [comment]
You mentioned contrib inside grpc go, you still keen on doing that?

**Comment by iamqizhao** [comment]
I think contrib will be out soon. It is outside the library repo -- we will have a new org and multiple repos for contrib.

**Comment by mwitkow** [comment]
Awesome

**Comment by philips** [comment]
cc @xiang90 @gyuho @heyitsanthony

**Comment by philips** [comment]
+1 on having a common implementation of this so the community can interop.

**Comment by mwitkow** [comment]
It would be awesome to have a common implementation. 
We've moved our gRPC Prometheus monitoring stuff into https://github.com/mwitkow/go-grpc-prometheus, which complies to the standard single-interceptor interface.

**Comment by mwitkow** [comment]
When moving away from our "hacked" interceptor design we had for months, I realised the problems with interceptors go slightly deeper:
 - it's hard to chain (and this doesn't seem like it will be merged)
 - accessing and modifying the `ServerStream.Context` is hard, as it is read-only and not overwriteable
 - per-message access in `ServerStream` is hard, as you need to hack things together

I started https://github.com/mwitkow/go-grpc-middleware, with a chaining (basically @peter-edge's equivalent of middleware) and `WrappedServerStream` implementation that we needed so far. I'd be happy to move it into `grpc-contrib` once that lands.

**Comment by lukaszx0** [comment]
> I think contrib will be out soon. It is outside the library repo -- we will have a new org and multiple repos for contrib.

@iamqizhao was this ever released? I don't see it in https://github.com/grpc-ecosystem

**Comment by iamqizhao** [comment]
@lukaszx0 I have no idea. We are not in the loop of this effort.

**Comment by mwitkow** [comment]
@zinuga Do you think we can include https://github.com/mwitkow/go-grpc-middleware into grpc-ecosystem? :)

**Comment by pkieltyka** [comment]
I secondly, love the idea of having middleware support in grpc

**Pull request closed without merging**
