### PR TITLE
*: fix more typos

### PR DESCRIPTION
**Pull request by NathanBaulch**
Another batch of typos similar to #7487, plus a few minor grammar corrections.

FWIW, top 10 corrections are:
* existant -> existent (29)
* an -> a (13)
* a -> an (12)
* it's -> its (10)
* verificaiton -> verification (4)
* github -> GitHub (3)
* not -> no (2)
* certifcate -> certificate (2)
* unerlying underlying (1)
* panc -> panic (1)

RELEASE NOTES: none

### CODE REVIEW

**Comment by purnesh42H** [comment]
thanks @NathanBaulch. Could you add the relnotes?

**Review by purnesh42H — APPROVED** [review]

**Comment by purnesh42H** [comment]
LGTM. Adding @arvindbr8 for second review

**Review by arvindbr8 — APPROVED** [review]
Thanks for this. Looks like a very detailed review of our documentation.

**Comment by arvindbr8** [comment]
I can't seem to get Mergeable to run again. Trying a re-trigger by closing and reopening this PR

**Pull request merged**
