### PR TITLE
xds: cleanup unnecessary feature

### PR DESCRIPTION
**Pull request by menghanl**
1. stop sending metadata TRAFFICDIRECTOR_GRPC_HOSTNAME in EDS/LRS response, and send dial target in requests's ResourceNames.
1. remove receiving sub balancing policy from service config. Sub balancing policy update will be done by CDS instead
1. temporarily disable CDS
   - CDS will be enabled in a future PR. Also, in the same change, EDS will send cluster name from CDS response in ResourceNames, not user's dial target

### CODE REVIEW

**Comment by markdroth** [comment]
> remove receiving sub balancing policy from service config. Sub balancing policy update will be done by CDS instead

I haven't looked at the code, but note that the code in the current xds LB policy should not need to change the way it gets its config.  In subsequent changes, we will wind up inserting the CDS policy in between the client channel and the current xds policy, but the API used by the xds policy to get its config from its parent should not change as a result of that.  It should not matter to the policy whether its parent is the client channel or the CDS policy; the same API should be used to give it its config in both cases.

**Comment by menghanl** [comment]
@markdroth The code deleted is very service config specific. It includes the service config json string parsing, and applying the child policy from service. Because we had the code to support CDS in hybrid mode, there's a separate code path to handle child policy in CDS response.

Do xds balancer still need to support service config after CDS?
Will we use balancer config from service config for anything in the xds balancer?
Will `XdsConfig` as defined in [gRFC A24-lb-policy-config](https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md#proposal) change?

**Comment by markdroth** [comment]
> @markdroth The code deleted is very service config specific. It includes the service config json string parsing, and applying the child policy from service. Because we had the code to support CDS in hybrid mode, there's a separate code path to handle child policy in CDS response.

I don't understand why there are two different code-paths here.  There should not be.

The LB policy API should have a single `Update()` method for giving the policy updated data.  That method should accept a list of addresses and a parsed configuration object.  Here's how those arguments are represented in C-core:

https://github.com/grpc/grpc/blob/9b288b20c4e56f77e38d08b54881ece953f7c7e3/src/core/ext/filters/client_channel/lb_policy.h#L294

The LB policy *factory* API should have a method for parsing the policy's JSON config and returning a parsed config object.  In C-core, it looks like this:

https://github.com/grpc/grpc/blob/9b288b20c4e56f77e38d08b54881ece953f7c7e3/src/core/ext/filters/client_channel/lb_policy_factory.h#L39

The LB policy itself should not care how the parsed config object is constructed, so it could conceivably be generated from something other than JSON.  However, I think that in most cases, we will want to continue to use JSON as the API between different LB policies, because otherwise each LB policy will require specific knowledge of its child policies, which limits the ability to combine them in arbitrary ways.

> Do xds balancer still need to support service config after CDS?

The policy will continue to need configuration, regardless of who its parent is.  And I think that configuration should continue to be in JSON form.

In other words, I would expect that the CDS policy will construct a config in JSON form and then pass it to the xds policy factory's parsing method to generate the parsed configuration object, exactly as would be done if the JSON config came directly from the service config.

> Will we use balancer config from service config for anything in the xds balancer?

As per our recent discussion about trying to retain the fallback code for now, I think we are going to try to continue to support the case where the xds policy is triggered from a non-xds resolver.  The fallback code we have today is useless with the xds resolver, because if the xds server is unreachable, then the xds resolver would never return a config, and we would never have selected the xds LB policy in the first place.

> Will `XdsConfig` as defined in [gRFC A24-lb-policy-config](https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md#proposal) change?

We'll be removing the `balancer_name` field, since that information will now come from the bootstrap file instead.

The `child_policy` field will need to stay, at least for a while.  We may eventually wind up changing this as part of refactoring the current xds policy to add support for pluggable locality picking policies, but it's not yet clear exactly how that will shake out.

As mentioned above, we are going to try to retain the current fallback code for now, which means that we will also wind up keeping the `fallback_policy` field for now.  This could go away later if we decide to stop supporting the current fallback functionality.

**Comment by menghanl** [comment]
> I don't understand why there are two different code-paths here. There should not be.

There's one method to actually update the sub-balancing policy `HandleChildPolicy()`. It's called from two places: 1. when handling service config; 2. when handling cds response (the current xds-balancer can handle both eds and cds).

From the offline discussion, we are going to repurpose the current xds-balancer to be the new eds-balancer, and add a cds-balancer.
The right fix should be to remove the CDS related child-policy code, not the service config related code.

**Comment by menghanl** [comment]
Replaced by #3081 and #3085

**Pull request closed without merging**
