### PR TITLE
add examples/helloworld/greeter_server unit test

### PR DESCRIPTION
**Pull request by LarryRuane**
Test adapted (with a few minor corrections) from https://stackoverflow.com/questions/42102496/testing-a-grpc-service

### CODE REVIEW

**Comment by dfawley** [comment]
This is not the preferred testing methodology for servers.  For one, the context passed to the server will not contain headers set by the client unless they are manually set here, and it will not contain headers and other data set by gRPC.

For now the recommended way to test servers is to use a localhost connection and a gRPC client.  Eventually, it will be to use an in-process transport, after that is implemented (#906).

**Comment by LarryRuane** [comment]
@dfawley, that is fine, we can close this PR if you think best; I'm very new to the grpc ecosystem. I had cloned this repo and the helloworld example was extremely helpful, but it took a nontrivial amount of searching to find the stackoverflow article explaining how to do even the simplest of unit testing (that we can do today with `go test`).  Do you think perhaps adding this test, after adding a comment to the top of the file with your statements in your comment above, might fall into the category of "better than nothing?" OTOH, I'm acutely aware of the benefits of keeping things simple, and the helloworld example is as simple as possible, so it's very reasonable to not add a unit test. On the other hand, the test is of similar (minimal) complexity as the example itself. Thank you for your comments!

**Comment by dfawley** [comment]
> I'm acutely aware of the benefits of keeping things simple, and the helloworld example is as simple as possible, so it's very reasonable to not add a unit test.

I agree it would be nice to have a unit test for an example checked in to demonstrate testing methodology, but I don't think checking in a not-recommended method along with comments explaining why it's not recommended is a good idea.  If you have time to add the client and `grpc.Server` to the tests, it would be appreciated.  If not, we can close this PR and file an issue instead.  Thanks!

**Comment by LarryRuane** [comment]
@dfawley, I don't think I'll have any more time to spend on this in the short term, so I agree, I'll go ahead and close it now, thanks.

**Pull request closed without merging**
