### PR TITLE
Enhance parseDialTarget Function to Support Named Pipes

### PR DESCRIPTION
**Pull request by CharityKathure**
This update modifies the `parseDialTarget` function to support named pipes in addition to existing protocols. The function now checks for the `npipe` scheme, returning the appropriate network and address when a named pipe is specified. 
The corresponding test case for TestParseDialTarget has been updated to include scenarios for named pipe targets, ensuring correct parsing and validation of input.

**Changes made:**

- Updated the parseDialTarget function to handle the "npipe" scheme alongside the existing "unix" scheme.

- Added new test cases in TestParseDialTarget to validate the functionality for named pipes, enhancing test coverage for different address formats.

RELEASE NOTES: None

### CODE REVIEW

**Review by iankingori — COMMENTED** [review]
LGTM

**Comment by easwars** [comment]
Could you please describe your use-case a bit more?

This PR only changes the code that is executed when a connection is attempted to a resolved backend address. If your intention was to add support for a grpc client channel to be created to a server whose target URI is a windows named pipe, then these changes will not be sufficient.

So, it would help if we can have a discussion about what your use-case is and take it from there. Thanks.

**Comment by CharityKathure** [comment]
@easwars Thanks for the response. The primary goal of this PR is to ensure proper handling of Windows named pipes (npipe) in the `parseDialTarget` function.

**The use case:**
When Docker starts `containerd`, the Docker daemon uses a named pipe (`npipe:////./pipe/docker-containerd`) to communicate with `containerd` on Windows. The issue arises when Docker attempts to ping this named pipe after some idle time. The `parseDialTarget` function, which is used during this ping operation, was defaulting to a TCP network for the npipe address. As a result, the dialer expected a TCP port, leading to errors such as:

`Err: connection error: desc = \"transport: Error while dialing: dial tcp: lookup tcp/////./pipe/docker-containerd: getaddrinfow: The specified class was not found.\"" library=grpc`

To address this, I modified the function to treat `npipe` similarly to `unix`, ensuring that when a named pipe address is passed, the correct network is identified _(i.e., `npipe` instead of `tcp`)_. This change fixes the issue by preventing TCP from being mistakenly selected for `npipe` addresses.

**Comment by easwars** [comment]
Can you please clarify where and how gRPC is used in this communication between Docker and `containerd`?

> The issue arises when Docker attempts to ping this named pipe after some idle time

What sort of ping are you referring to here?

**Comment by CharityKathure** [comment]
@easwars In this context, Docker starts containerd, and a new client connection to containerd is established using gRPC. The client is configured to connect to r.GRPC.Address _(`npipe`)_. Periodic checks are then performed to ensure containerd is serving correctly by calling client.IsServing.

**Comment by easwars** [comment]
Yes, if gRPC has to fully and correctly support npipes, support for a new name resolution scheme has to added. We have two options:
- You could implement your own custom name resolver using the name resolver API found here: https://github.com/grpc/grpc-go/blob/8212cf0376831ce8b88b824128f113ae6e90b4c8/resolver/resolver.go#L314
  - You can find an example for the same here: https://github.com/grpc/grpc-go/blob/8212cf0376831ce8b88b824128f113ae6e90b4c8/examples/features/name_resolving/client/main.go#L87
  - We wouldn't be able to merge this into grpc-go though, since we would want to be consistent with other grpc language implementations. But you could maintain your custom name resolver implementation and you should be able to use it with grpc-go. 
- If you require cross language support, I'd recommend filing an issue in our proposal repository here: https://github.com/grpc/proposal

Please let us know if you have more questions. Thanks.

**Comment by easwars** [comment]
I'll close this PR at this point. But feel free to file an issue if you'd like to discuss anything further.

**Pull request closed without merging**
