### PR TITLE
config: remove retry disable via environment variable

### PR DESCRIPTION
**Pull request by dfawley**
RELEASE NOTES:
* config: remove retry disable via environment variable

### CODE REVIEW

**Review by zasweq — COMMENTED** [review]
This looks fine, but I think we should wait for #4925 to get merged and rebase this onto that master. #4925 changes behavior server side because route specifier is now required, which might (but I don't think so) break one of these tests which used to be gated by an env var.

**Comment by menghanl** [comment]
Should we just keep RBAC env var? We have other env vars older than RBAC. And RBAC adds a new requirement of the responses, which is more likely to break if the control plane isn't up-to-date (#4924)

We want to remove `retry` because of the confusion caused by two retry vars.

**Comment by dfawley** [comment]
> We have other env vars older than RBAC

The ones which are tested sufficiently should be removed, too.  I hadn't been looking at the others, but it seems like client side security and possibly ring hash should also be removed?

> We want to remove retry because of the confusion caused by two retry vars.

We want to remove retry because we believe it is sufficiently tested.  Having too many flags is not a good idea.  They are intended to be short-term testing tools, primarily.

**Comment by dfawley** [comment]
Removed the removal of RBAC control.  This just deletes the retry control now.

**Review by menghanl — APPROVED** [review]

**Pull request merged**
