### PR TITLE
examples: remove usage of WithBlock in examples

### PR DESCRIPTION
**Pull request by Hrily**
Fixes: #4851

RELEASE NOTES: none

### CODE REVIEW

**Review by dfawley — APPROVED** [review]
LGTM, but please test on MacOS before submitting, because that's something I would like to keep working.

**Comment by easwars** [comment]
> LGTM, but please test on MacOS before submitting, because that's something I would like to keep working.

Fails on MacOS because the `bash` that ships with it is an old version.
```
easwars@easwars-macbookpro:grpc-go $ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

And looks like the `declare -A` (associative arrays) is a bash 4+ feature.

**Comment by Hrily** [comment]
> > LGTM, but please test on MacOS before submitting, because that's something I would like to keep working.
> 
> Fails on MacOS because the `bash` that ships with it is an old version.
> 
> ```
> easwars@easwars-macbookpro:grpc-go $ bash --version
> GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
> Copyright (C) 2007 Free Software Foundation, Inc.
> ```
> 
> And looks like the `declare -A` (associative arrays) is a bash 4+ feature.
> 
> And since we already had usages of `declare -A` in this script, this never worked on MacOS.

Yes, I had to install bash form homebrew and use that.

Do you suggest any changes to make it work on macos out of the box?

**Comment by easwars** [comment]
Since it wasn't working on MacOS without an updated `bash`, it is OK as is.

Thank you very much for your contribution.

**Pull request merged**
