### PR TITLE
Add WithBalancerUserOptions for custom balancer build options

### LINKED ISSUE #1798: Please add WithBalancerUserOptions API
Similar to https://github.com/grpc/grpc-go/pull/1711, it would be useful to setup some balancer params at client creation time and have those passed in for more advanced balancing. (The motivating use-case is consistent hashing, we would like client to be able to specify hash function/seed)

### PR DESCRIPTION
**Pull request by menghanl**
fixes #1798

Similar to custom resolver build options (#1711).

### CODE REVIEW

**Comment by dzbarsky** [comment]
LGTM, thanks!

**Comment by dfawley** [comment]
cc @ejona86: does you have the same concerns with this as #1711?

**Comment by ejona86** [comment]
I have the same concern of "all languages or none." Balancer configuration is more up-in-the-air across languages, I think. Today, I think the Name Resolver is what's configuring the balancer (as with gRPC LB), but this unfortunately couples the resolver and the balancer at least partially.

I'm not quite clear on how the resolver and balancer communicate today in Go, for things like gRPC LB configuration. Using this for hash function/seed was the example. If that information can be provided by the name resolver, that would be the strong preference. If not and it's also not global... then I think we'll need to figure something out. Similar to name resolver, I do think it may make more sense to pass in a pre-configured balancer object to gRPC instead of side-loaded configuration. But that's arguable.

**Comment by menghanl** [comment]
Closing PR. See related discussion in #1812

**Pull request closed without merging**
