### PR TITLE
Don't call t.FailNow in goroutines started by tests.

### PR DESCRIPTION
**Pull request by bradfitz**
The docs at https://golang.org/pkg/testing/#T.FailNow say:

> FailNow must be called from the goroutine running the test or
> benchmark function, not from other goroutines created during the
> test.

(Fatalf is documented as "Fatalf is equivalent to Logf followed by
FailNow.")

This was manifesting itself as a race with two concurrently failing
goroutines in my other CL, masking whatever the real problem was.

### CODE REVIEW

**Comment by bradfitz** [comment]
/cc @iamqizhao 

I'm sending this separately from my other CL. This should be fixed regardless.

**Comment by maniksurtani** [comment]
This isn't the only test that uses `Fatalf` ... 

```
$ git grep t.Fatal | grep _test.go | sed -e 's/:.*//' | uniq
call_test.go
clientconn_test.go
metadata/metadata_test.go
picker_test.go
rpc_util_test.go
test/end2end_test.go
transport/http_util_test.go
transport/transport_test.go
```

Makes sense to fix them all?

**Comment by zellyn** [comment]
@maniksurtani Fatalf is okay (and normal) in the goroutine that runs the test function, just not in goroutines started by it.

**Comment by bradfitz** [comment]
@zellyn, correct. But it's true that I didn't audit all files outside of end2end_test.go. Doing that now and already found at least one.

**Comment by zellyn** [comment]
@bradfitz Ah, good catch.

**Comment by iamqizhao** [comment]
Thanks for the fixing. I remembered I tried to do a thorough pass on this issue. But apparently I have not completed it.

**Pull request merged**
