### PR TITLE
Support for DEFLATE/ZLIB compression

### PR DESCRIPTION
**Pull request by earies**
- deflate compressor/decompressor similar to that for gzip
- zlib format for deflate compression (RFC2616 - Section 3.5)

### CODE REVIEW

**Comment by earies** [comment]
I signed it!

**Comment by earies** [comment]
Following up if anyone can pickup review or comment on this pull - thx

**Comment by earies** [comment]
Following up again if this can be picked up for review/comment

**Comment by dfawley** [comment]
Thank you for your contribution, and sorry for the delay.

We debated this for some time, and have decided we do not want to accept this change.  Specific implementations of compressors are not a core part of gRPC, and we would prefer not to maintain a library of them.  Additionally (but not the main factor), including these directly in the grpc package adds dependencies that are not essential for grpc functionality, and that should be avoided as much as possible.

Even so, we appreciate that it's not as trivial as it should be to install a new compressor/decompressor.  We'd like to make a change in the future that removes the Compressor/Decompressor interfaces and instead is built upon the standard package's NewWriter/NewReader functions in the different compression packages directly (or possibly with very minor wrapping).  Until then, if you would like, you could add this to your own repo, and we can link to it from our grpc/grpc-contrib repo.

Thanks again for this PR.

**Comment by dfawley** [comment]
I created #1193 to track the idea expressed above.

**Pull request closed without merging**
