### PR TITLE
grpclog: remove Debugf method to avoid unnecessary evaluation

### PR DESCRIPTION
**Pull request by ryuryu08**
Fixes: https://github.com/grpc/grpc-go/issues/7154

RELEASE NOTES: none

### CODE REVIEW

**Comment by ryuryu08** [comment]
cc @aranjans @dfawley

**Comment by atollena** [comment]
There is one remaining reference in a comment:

https://github.com/grpc/grpc-go/blob/c04b085930ce33ee83cc3f92dbe7632031e127a9/xds/internal/xdsclient/transport/transport.go#L49-L52

**Comment by ryuryu08** [comment]
> There is one remaining reference in a comment:
> 
> https://github.com/grpc/grpc-go/blob/c04b085930ce33ee83cc3f92dbe7632031e127a9/xds/internal/xdsclient/transport/transport.go#L49-L52

I removed the reference in the comment and amended the changes to the initial commit.

**Review by aranjans — APPROVED** [review]
@ryuryu08  Thanks for the PR. LGTM!

**Review by dfawley — APPROVED** [review]

**Pull request merged**
