### PR TITLE
Catch invalid use of Server.RegisterService after Register.Serve

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by menghanl** [comment]
Did you encounter any problem caused by this?
By design, `s.m` should be read only after `server.start`, so this lock is not necessary here.

**Comment by petermattis** [comment]
Yes, I did encounter a problem which motivated this. I have a scenario in which I wish to register a service on a server after initiating a connection to a server. If this isn't an allowed scenario, `Server.register` should disallow it.

**Comment by petermattis** [comment]
Ah, I missed the comment above `Server.RegisterService`. Do you want me to add the protection against calling `RegisterService` after `Server.Serve` has been called or just drop this PR?

**Comment by menghanl** [comment]
I don't recall anything in `Server` indicating whether the server has started. Not sure how easy it is. Please add the protection if you find it easy to do.

**Comment by petermattis** [comment]
@menghanl This is what I was thinking of. Currently difficult to test this as there is no way to temporarily swap out the `grpclog.logger` for a single test.

**Comment by menghanl** [comment]
Sorry for the delay.
If you don't mind, can you resolve the conflict and let's get this in?

**Comment by petermattis** [comment]
@menghanl Rebased.

**Pull request merged**
