### PR TITLE
Revert "Revert "credentials/alts: defer ALTS stream creation until handshake …"

### PR DESCRIPTION
**Pull request by matthewstevenson88**
Reverts grpc/grpc-go#6148.

In #6177, we added new tests that would have caught a bug like the one that forced #6077 to be reverted.

RELEASE NOTES: N/A

### CODE REVIEW

**Comment by matthewstevenson88** [comment]
Thanks @zasweq! Yes this PR fixes the original problem with #6177: we check that `h.stream` is non-nil before calling `Close()`, and have a unit test that confirms this.

Additionally, I've already merged #6177, which adds e2e tests that would have caught the error in #6177 before import. The tests on this PR were originally failing because the e2e test was flaky: I just merged #6183, which fixes the flake. Huge thanks again to @easwars for his help on these 2 PRs. :)

**Comment by zasweq** [comment]
Ah, good to hear! Will approve then. I ran our import already this week, so this will get picked up in next weeks import :).

**Review by zasweq — APPROVED** [review]
LGTM.

**Review by easwars — APPROVED** [review]

**Comment by matthewstevenson88** [comment]
Thank you both!

**Pull request merged**
