### PR TITLE
Less mem

### LINKED ISSUE #2011: Flaky test: TestLargeMessageDelayWrite
```
--- FAIL: TestLargeMessageDelayWrite (10.03s)
	transport_test.go:1026: io.ReadFull(stream error: code = DeadlineExceeded desc = "context deadline exceeded") = _,
```

### PR DESCRIPTION
**Pull request by MakMukhi**
updates #1455 
fixes #2011

On a benchmark that makes a total of 40K RPCs, with 1 connection and 100 concurrent RPCs of 1 MB req/resp, this saves about 13% more memory.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/1987)

### CODE REVIEW

**Comment by dfawley** [comment]
Please rebase and ping when done.  Thanks!

**Comment by MakMukhi** [comment]
Done. PTAL

**Comment by menghanl** [comment]
Reviewed 8 of 14 files at r1, 2 of 6 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[rpc_util.go, line 423 at r1](https://reviewable.io/reviews/grpc/grpc-go/1987#-LA-ryKeChBmZbYbqF0c:-LA-ryKeChBmZbYbqF0d:b2mr5bc) ([raw file](https://github.com/grpc/grpc-go/blob/b58d5139003bda3a1283a66addbe4c0c2248b0fe/rpc_util.go#L423)):*
> ```Go
> // The caller owns the returned msg memory.
> //
> // If there is an error, possible values are:
> ```

Are those errors still true?

---

*[internal/msgdecoder/msgdecoder.go, line 19 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAy4jQd92hF5wNqTPuy:-LAy4jQd92hF5wNqTPuz:b-4r42oe) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/internal/msgdecoder/msgdecoder.go#L19)):*
> ```Go
> 
> // Package msgdecoder contains the logic to deconstruct a gRPC-message.
> package msgdecoder
> ```

This is internal to transport. I wonder if moving this to `grpc/transport/internal/msgdecoder` would still work..

---

*[internal/msgdecoder/msgdecoder.go, line 86 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAy9ygKBorzaUJWpsyp:-LAy9ygKBorzaUJWpsyq:b-b22ykw) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/internal/msgdecoder/msgdecoder.go#L86)):*
> ```Go
> 
> // Decode consumes bytes from a HTTP2 data frame to create gRPC messages.
> func (m *MessageDecoder) Decode(b []byte, padding int) {
> ```

Add some tests to cover the following cases.

---

*[internal/msgdecoder/msgdecoder.go, line 127 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAy2ZS259NBvTogchef:-LAy2ZS259NBvTogcheg:btrfjv1) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/internal/msgdecoder/msgdecoder.go#L127)):*
> ```Go
> 
> func (m *MessageDecoder) parseHeader(b []byte) {
> 	buf := getMem(b[1:5])
> ```

Nit: calculate `length := binary.BigEndian.Uint32(b[1:5])` before this line, call `getMem(length)`, and you don't need `len(buf)` later.

---

*[internal/msgdecoder/msgdecoder.go, line 155 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAy49eX8orSLlepYagh:-LAy49eX8orSLlepYagi:bxxo044) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/internal/msgdecoder/msgdecoder.go#L155)):*
> ```Go
> 
> // GetMessageHeader creates a gRPC-specific message header.
> func GetMessageHeader(l int, isCompressed bool) []byte {
> ```

Call this `BuildMessageHeader`? Or `CreateMessageHeader`?

---

*[transport/stream.go, line 3 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAykCGD-H27ReAecTez:-LAykCGD-H27ReAecTf-:bexvutd) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L3)):*
> ```Go
> /*
>  *
>  * Copyright 2014 gRPC authors.
> ```

2018? Not sure.

---

*[transport/stream.go, line 64 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAykw85EzNvDWC9Vbrd:-LAykw85EzNvDWC9Vbre:bkfxdih) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L64)):*
> ```Go
> 	t := l.tail
> 	l.tail = r
> 	t.Next = r
> ```

Using a field of an exported field from another package doesn't look like a good idea to me.
IMO, the linked list related fields/structs should be kept in the same package.

Define a `recvMagListNode` struct with a `next` pointer as a container for `*msgdecoder.RecvMsg`?

Or https://golang.org/pkg/container/list/ if you don't mind the extra type assertion.

---

*[transport/stream.go, line 107 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAymzI6-J2SKYZcwDse:-LAymzI6-J2SKYZcwDsf:bh8uamy) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L107)):*
> ```Go
> // waiting, otherwise, it writes on the chan directly.
> //
> // put must synchronize with GetNoBlock().
> ```

What does this comment mean?
`put` and `getNoBlock` are already protected by `b.mu`.

---

*[transport/stream.go, line 122 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAyngo_8-ce8mUFDcAA:-LAyngo_8-ce8mUFDcAB:b-qntn88) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L122)):*
> ```Go
> // getNoBlock returns a msgdecoder.RecvMsg and true status, if there's
> // any available.
> // If the status is false, the caller must then call
> ```

It seems the only use case now is
```
if not getNoBlock() {
  getWithBlock()...
}
```

Why not merge these two functions?

---

*[transport/stream.go, line 139 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAynYQG9NCR_ORD-Uag:-LAynYQG9NCR_ORD-Uah:b-xedz) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L139)):*
> ```Go
> }
> 
> // GetWithBlock() blocks until a complete message has been
> ```

Nit: `getWithBlock`

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/1987)*

**Comment by MakMukhi** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[rpc_util.go, line 423 at r1](https://reviewable.io/reviews/grpc/grpc-go/1987#-LA-ryKeChBmZbYbqF0c:-LB1rA2J3igTGhwulIJV:b3nhob8) ([raw file](https://github.com/grpc/grpc-go/blob/b58d5139003bda3a1283a66addbe4c0c2248b0fe/rpc_util.go#L423)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Are those errors still true?
</blockquote></details>

Yes they are.

---

*[internal/msgdecoder/msgdecoder.go, line 19 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAy4jQd92hF5wNqTPuy:-LB1rSbzBvgOiG1bUFb3:b-3jq427) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/internal/msgdecoder/msgdecoder.go#L19)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

This is internal to transport. I wonder if moving this to `grpc/transport/internal/msgdecoder` would still work..
</blockquote></details>

Actually, we'd like it to not be a transport internal, since we don't want to make the transport aware of gRPC-level encoding.

---

*[transport/stream.go, line 64 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAykw85EzNvDWC9Vbrd:-LB1uY4P0RhbLXwBndHS:b-28tqu5) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L64)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Using a field of an exported field from another package doesn't look like a good idea to me.
IMO, the linked list related fields/structs should be kept in the same package.

Define a `recvMagListNode` struct with a `next` pointer as a container for `*msgdecoder.RecvMsg`?

Or https://golang.org/pkg/container/list/ if you don't mind the extra type assertion.
</blockquote></details>

That's a good point. How about I move the linked-list to `msgdecoder` package?

---

*[transport/stream.go, line 107 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAymzI6-J2SKYZcwDse:-LB1vpcf6SBmotPUSnwD:b39u1u8) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L107)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

What does this comment mean?
`put` and `getNoBlock` are already protected by `b.mu`.
</blockquote></details>

That's right, the comment is just explicitly saying that. I'll remove it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/1987)*

**Comment by MakMukhi** [comment]
*[transport/stream.go, line 3 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAykCGD-H27ReAecTez:-LB2s-X674zg3FWRUkgY:b-esfxne) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/transport/stream.go#L3)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

2018? Not sure.
</blockquote></details>

It does contain code from 2014. So I don't really know what's the right thing either!?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/1987)*

**Comment by menghanl** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[internal/msgdecoder/msgdecoder.go, line 19 at r3](https://reviewable.io/reviews/grpc/grpc-go/1987#-LAy4jQd92hF5wNqTPuy:-LB3HCOT8NSlNuakrcWw:b-81nlyc) ([raw file](https://github.com/grpc/grpc-go/blob/50e9a863ac434756fff3a5a28cdbf2a444123a3f/internal/msgdecoder/msgdecoder.go#L19)):*
<details><summary><i>Previously, MakMukhi (mmukhi) wrote…</i></summary><blockquote>

Actually, we'd like it to not be a transport internal, since we don't want to make the transport aware of gRPC-level encoding.
</blockquote></details>

SGTM.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/1987)*

**Pull request merged**
