### PR TITLE
do not transform ErrConnClosing to rpcError

### LINKED ISSUE #530: ErrConnClosing sometimes bubbles up as an rpcError
I see stuff like this bubble up in my logs:

```
E0205 18:18:33.157609 40850 gossip/client.go:267  rpc error: code = 13 desc = "transport is closing"
```

Normally I'd expect this not to appear, since I deliberately do not log `ErrConnClosing`, and the definition of `ErrConnClosing` is the only instance of `"transport is closing"` in grpc.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #530.

### CODE REVIEW

**Comment by iamqizhao** [comment]
This seems incorrect. You want to know the reason if your rpc is failed.

**Comment by tamird** [comment]
You'll still get the reason, it just won't be wrapped in an rpcError.

**Comment by iamqizhao** [comment]
why? This is the final result of an rpc and should be an rpcError.

**Comment by tamird** [comment]
For the same reason that `ErrConnClosing` is exported and `io.EOF` is not wrapped; I closed the conn - I meant to do that, and a subsequent `Send()` failed - that's expected. I'm using context cancellation to signal to the sender goroutine that it's time to stop; that's not an RPC error.

**Comment by iamqizhao** [comment]
The principle an rpc (regardless unary or streaming) will have a final status. Unless it is okay status (nil or io.EOF), the final status is of type rpcError.

**Comment by dsymonds** [comment]
Seems like rpcError should be exported with an exported Err field (like `os.PathError`), or there should be some kind of API to "unpack" the returned error to get at the underlying thing. @iamqizhao is right that there should be a consistent error type, but I can definitely see the utility of finding out the exact (unwrapped) error.

**Comment by dfawley** [comment]
A few thoughts:

- This function must return an RPC error (now a `status` error).
- The transport package isn't intended to be used outside of grpc.  We'd want to send back a different `grpc.ErrConnClosing` or equivalent instead.  Looks like we already have such a thing, but it isn't a status error (oops):

https://github.com/grpc/grpc-go/blob/c5c761dbca07f4d0efafd3f430a40dcdf1c1163f/clientconn.go#L41

How about if we make that a status error instead (`status.Error(status.Unavailable, "grpc: the client connection is closing")`) and return it?

**Comment by tamird** [comment]
b5071124 + a3592bda22af2816dac989ab6ccab42f45223455 essentially amount to this behaviour already, so this can just be closed.

**Pull request closed without merging**
