### PR TITLE
Support proxy

### PR DESCRIPTION
**Pull request by menghanl**
Support TCP-level proxies via the HTTP CONNECT request.

Implementes gRFC A1: https://github.com/grpc/proposal/pull/4.

### CODE REVIEW

**Comment by mwitkow** [comment]
Go already has an abstraction of `net.Dialer` which can be usedto address both points of the https://github.com/grpc/proposal/pull/4/files proposal: allowing to overwrite the address and perform TCP-level operations before handing off to gRPC. Can we please use that instead to make the library more Go-canonical and just write sugar-APIs on top to make it look like gRPC C++?

We had *exactly* the same problem: dialing remote gRPC endpoints over HTTPS connect. We've built https://github.com/mwitkow/go-http-dialer and end-to-end integraiton tests gRPC plaintext and gRPC tls https://github.com/mwitkow/go-http-dialer/blob/master/test/grpc_e2e_test.go

**Comment by menghanl** [comment]
In the proposal, it's proposed that we need to kinds of mapping functions, MapName before name resolution and MapAddress after name resolution.

Custom dialer only works in the case of MapAddress.
If the name cannot be resolved, dialer won't work.

**Comment by mwitkow** [comment]
The dialer gets the hostname in single connection mode so you definitely
can mapname as well (that's what we do).

Unless you're taking of mapname before hitting grpc.Naming then you're
right. But few people would be using Grpc.Naming and grpc LB with a proxy
connection.

**Comment by menghanl** [comment]
Makes sense.
Closing this and added #1098

**Pull request closed without merging**
