### PR TITLE
xds client: Updated v3 type for http connection manager

### PR DESCRIPTION
**Pull request by pradeepmvn**
Fix for Issue #4136 
I am unable to validate the failure running unit tests for `client_lds_tests.go`

### CODE REVIEW

**Comment by menghanl** [comment]
Can you try changing https://github.com/grpc/grpc-go/blob/f4a20d2f414ffe9ca43416e6980831bde3140404/xds/internal/client/client_lds_test.go#L90-L97

To
```go
cmAny, _ := ptypes.MarshalAny(cm)

...

{
    ApiListener: cmAny,
}

```

And see if this would catch the bug? Thanks!

**Comment by pradeepmvn** [comment]
ok sure. Misunderstood it. let me test using ptypes on ConnectionManager.

**Comment by pradeepmvn** [comment]
Rolling back CM type to `type.googleapis.com/envoy.config.filter.network.http_connection_manager.v3.HttpConnectionManager `

and updating the unit test cases to ptype marshal caught the issue.

```
go test -run Test/UnmarshalListener_ClientSide

--- FAIL: Test/UnmarshalListener_ClientSide/v3_listener_resource (0.00s)
client_lds_test.go:298: UnmarshalListener([[type.googleapis.com/envoy.config.listener.v3.Listener]:{name:"lds.target.good:3333" api_listener:{api_listener:{[type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager]:{rds:{config_source:{ads:{}} route_config_name:"v3RouteConfig"}}}}}]) = (map[], xds: unexpected resource type: "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager" in LDS response) want (map[lds.target.good:3333:{v3RouteConfig <nil>}], false)
tlogger.go:99: client_xds.go:62 Resource with name: lds.target.good:2222, type: *envoy_config_listener_v3.Listener, contains: name:"lds.target.good:2222" api_listener:{api_listener:{[type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager]:{rds:{config_source:{ads:{}} route_config_name:"v2RouteConfig"}}}}  (t=+5.371401ms)
tlogger.go:99: client_xds.go:62 Resource with name: lds.target.good:3333, type: *envoy_config_listener_v3.Listener, contains: name:"lds.target.good:3333" api_listener:{api_listener:{[type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager]:{rds:{config_source:{ads:{}} route_config_name:"v3RouteConfig"}}}}  (t=+5.406124ms)

```


updating to new type `type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager` resolved unit tests and passed them

```
go test -run Test/UnmarshalListener_ClientSide
PASS
ok      google.golang.org/grpc/xds/internal/client      0.285s
```

**Review by menghanl — APPROVED** [review]
Thanks so much for the fix and the test! LGTM!

**Pull request merged**
