### PR TITLE
server: always handle streaming RPCs in separate goroutines to optimize serverWorker availability

### PR DESCRIPTION
**Pull request by pingkuan**
Streaming RPCs are typically long-lived and can monopolize the serverWorker for extended periods. To prevent this, streaming RPCs should always be handled in a separate goroutine.

### CODE REVIEW

**Comment by purnesh42H** [comment]
@pingkuan thanks for suggestion. I have asked the team for their thoughts on this change

**Comment by purnesh42H** [comment]
@pingkuan our suggestion would be to use a signal which identifies long live rpcs instead of restricting to streaming RPCs.

**Comment by pingkuan** [comment]
@purnesh42H Since the package may not be able to determine in advance whether a method will be long-lived, which is typically a decision made by the user during implementation, I recommend offering a server option that allows users to specify which methods should be treated as long-lived and, consequently, should not be handled by the server worker.

**Comment by easwars** [comment]
Is there an issue open for this? I feel that it would make sense to open an issue, discuss the options we have, finalize one, and then move on to a PR.

**Comment by dfawley** [comment]
> Is there an issue open for this? I feel that it would make sense to open an issue, discuss the options we have, finalize one, and then move on to a PR.

+1.  E.g. I wonder if we can use a `sync.Pool` to facilitate worker goroutine re-use?

**Pull request closed without merging**
