### PR TITLE
rpc_util: sync.Pool for parsing and recvMsg

### PR DESCRIPTION
**Pull request by jzelinskie**
👋 Hiya!

This could be a contentious change or maybe one that needs a lot of exhaustive testing.

I added a sync.Pool and refactored a bit to reduce allocations for []byte objects used for parsing.

This involves changing some places that were previously []byte into *bytes.Buffer in order to use some of the subtle code underlying buffer.Grow().

I'm still testing this for [SpiceDB](https://github.com/authzed/spicedb) to see if we see efficiency gains.
I'll convert from draft once it's ready for review.

### CODE REVIEW

**Comment by dfawley** [comment]
Definitely curious to see how the benchmarks look.  We have our own benchmarks, which it would be nice if you could run, too: https://github.com/grpc/grpc-go/blob/master/Documentation/benchmark.md.

Also note that the code is probably not correct in this state, as there are panics in the tests:

```
goroutine 38 [running]:
testing.tRunner.func1.2({0xb41460, 0x102cb80})
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1392 +0x5d2
panic({0xb41460, 0x102cb80})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:844 +0x258
bytes.(*Buffer).Len(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/bytes/buffer.go:73
google.golang.org/grpc.recvAndDecompress(0x50?, 0xc0001a2240, {0x0, 0x0}, 0x400000, 0xc00006ac00, {0x0, 0x0})
	/home/runner/work/grpc-go/grpc-go/rpc_util.go:709 +0xc7
google.golang.org/grpc.recv(0x0?, {0x7f3ec002a898, 0x1072ad8}, 0x4a[199](https://github.com/grpc/grpc-go/actions/runs/3064071198/jobs/4946830947#step:8:200)7?, {0x0, 0x0}, {0xb75b20, 0xc000166de0}, 0x40?, 0xc00006ac00, ...)
	/home/runner/work/grpc-go/grpc-go/rpc_util.go:780 +0xc6
google.golang.org/grpc.(*csAttempt).recvMsg(0xc0000e4480, {0xb75b20?, 0xc000166de0}, 0xc00006ac00)
	/home/runner/work/grpc-go/grpc-go/stream.go:1000 +0x545
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0001a20ac?)
	/home/runner/work/grpc-go/grpc-go/stream.go:851 +0x57
```

**Comment by jzelinskie** [comment]
Just a status update: I'm pretty preoccupied with other things right now, but do plan to get back to this or coordinate with someone that wants it take it over. I saw you added it to a release milestone and I don't want to block any releases.

**Comment by dfawley** [comment]
> I saw you added it to a release milestone and I don't want to block any releases.

No worries.  We require release milestones on all PRs for our mergeable bot to be happy, and when we do releases we bulk add everything outstanding to the next release so that if they are submitted our release notes are accurate.  The milestone doesn't imply anything about the PR's status.

**Comment by jzelinskie** [comment]
Still working on this and will re-open when it's ready.

Here's an interesting PR with functionality that could be emulated: https://go-review.googlesource.com/c/go/+/455236

**Pull request closed without merging**
