### PR TITLE
Use Type() method for OAuth tokens instead of accessing field directly.

### PR DESCRIPTION
**Pull request by wallaceicy06**

### CODE REVIEW

**Comment by wallaceicy06** [comment]
#1524

**Comment by dfawley** [comment]
Thanks.  This needs gofmt run on it, and it may need a rebase to fix some code for a new golint check.

**Comment by wallaceicy06** [comment]
Sorry for the delay; took me a bit to figure out the build process. Should be good now.

**Comment by dfawley** [comment]
I'm not sure how you did your merge, but there are way more diffs in here than what you changed yourself.  Can you fix that, or if you're having trouble, maybe start from a new branch (sync'd to our latest upstream/master).

FWIW, I recommend rebasing your branch instead of merging the master commits on top: https://www.atlassian.com/git/tutorials/merging-vs-rebasing.  The commit log in github gets a little weird when you do that, but it keeps things more sane in the diffs themselves IMO.

**Comment by wallaceicy06** [comment]
Closing this PR in favor of a new, cleaner PR: #1537

**Pull request closed without merging**
