### PR TITLE
Changing license to Apache v2.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Implements #1085.

### CODE REVIEW

**Comment by menghanl** [comment]
Thanks a lot!

There are some unrelated changes though...

- 2 lines of comments removed in benchmark/grpc_testing/control.pb.go
- 2 lines of comments removed in benchmark/grpc_testing/control.proto
- 1 line of TODO removed in benchmark/worker/benchmark_client.go

**Comment by hsaliak** [comment]
The same 2 lines are removed from control.pb.go and control.proto, perhaps they are good test cases to run the script against and identify why there are false positives?

**Comment by dfawley** [comment]
@nicolasnoble, what is the status of this?  We noticed the counterpart changes in c and java are also pending. If it's OK to move forward with this change, can you please update it to include all the new/moved files?  We will prioritize the approval then.  If it's not appropriate, I would like to close it until it's ready.  Thanks!

**Comment by hsaliak** [comment]
The gRFC has been approved so we are committed to changing the license.
While it's ideal to switch everything over at the same time, I am not aware
of any requirement to actually do this in lockstep. If it's more
convenient, this can be done whenever a repository wants to.

**Comment by menghanl** [comment]
fixed by #1290

**Pull request closed without merging**
