### PR TITLE
Make non-failfast RPC get new transport instead of waiting

### PR DESCRIPTION
**Pull request by menghanl**
updates #810

### CODE REVIEW

**Comment by menghanl** [comment]
cc @heyitsanthony @xiang90

**Comment by heyitsanthony** [comment]
@menghanl OK, this passes the etcd balancer failover test that was failing before. Thanks!

**Comment by iamqizhao** [comment]
LGTM

**Comment by tamird** [comment]
Does this need a test?

**Comment by menghanl** [comment]
Added a test. There are two connections, one of them is down, but the other one is up. All non-failfast RPCs should not block.

**Pull request merged**
