### PR TITLE
Add ability to deregister service

### PR DESCRIPTION
**Pull request by vlad-alexandru-ionescu**
This is useful to adjust dynamically which services are being served.

### CODE REVIEW

**Comment by vlad-alexandru-ionescu** [comment]
I signed it!

**Comment by iamqizhao** [comment]
We do not plan to support dynamic server so far.  For now, once s.m is created, it is read-only so that no mutex lock is needed to dispatch an inbound RPC. 

BTW, your PR does not add the lock on that code path and hence introduces race condition.

**Comment by vlad-alexandru-ionescu** [comment]
Ah right, perhaps a `RWMutex` would be needed just for that map.
Thanks for having a look anyway.

**Comment by vlad-alexandru-ionescu** [comment]
We'll be maintaining a [fork with these changes](https://github.com/leveros/grpc-go/commit/e863a4715f6c066fb0a3baaefb834984475cd3ad) (with race condition fixed). If you ever plan on dynamic services I'd be happy to fix this PR and maybe add a test as well. Otherwise, feel free to close.

**Comment by iamqizhao** [comment]
I am closing this PR now. We can revisit when it raises enough interest.

**Comment by iamqizhao** [comment]
BTW, in this way you introduced a major contention point for all the RPCs on this server. I expect it will slow down your RPCs a lot when you have a number of in-flight RPCs.

**Comment by vlad-alexandru-ionescu** [comment]
Not sure why you say that, I'm using a `RWMutex.RLock()` for the hot path (shared read).

**Comment by iamqizhao** [comment]
RLock is lighter than Lock but it is not free. I just tried to remind you the potential performance impact you might run into.

**Comment by iamqizhao** [comment]
https://golang.org/src/sync/rwmutex.go

**Pull request closed without merging**
