### PR TITLE
add GracefulStop to ClientConn

### LINKED ISSUE #1104: Graceful shutdown for clients in Go
Coming from Mixpanel.

### PR DESCRIPTION
**Pull request by jadekler**
This CL adds GracefulStop to ClientConn. GracefulStop blocks until all
inflight RPCs are complete, then closes the clientconn and continues to
block until all connections are closed. After GracefulStop has been
called, all RPCs performed on the ClientConn will return an error
(including while GracefulStop is in a blocked state).

Fixes #1104

### CODE REVIEW

**Comment by jadekler** [comment]
Open questions: 

- Does it seem correct to wait for RPCs?
- Do you reckon there's a way to get around using waitgroup to track RPCs?
- Does it seem correct to wait for addrconns to close? Way back when we talked about this that was the idea, but now that I've actually done it it seems like waiting for RPCs + calling close is enough. After all, clientconn.Close doesn't wait for addrconns to close

**Comment by dfawley** [comment]
> Does it seem correct to wait for RPCs?

Yes - that is the important difference between `GracefulStop` (should that be `GracefulClose`?) and `Close`.

> Do you reckon there's a way to get around using waitgroup to track RPCs?
>
> Does it seem correct to wait for addrconns to close? Way back when we talked about this that was the idea, but now that I've actually done it it seems like waiting for RPCs + calling close is enough. After all, clientconn.Close doesn't wait for addrconns to close

You're right there's no need for both, but we should be checking for the transports, not the RPCs.  Transports will close themselves automagically when they are in draining mode and there are no active streams.

**Comment by jadekler** [comment]
SG, thanks. I'm going to rewrite this to keep track of open addrConns and when GracefulStop is called iterate over the list/map and addrConn.GracefulStop each of them.

**Comment by jadekler** [comment]
@dfawley I went and looked into not tracking RPCs, but I don't think we can do that. The thinking is that as long as there are RPCs active, the transport should be allowed to spin up / down connections as long as it needs to accomplish those RPCs. It seems like it would be disingenuous to say that "GracefulClose allows existing RPCs to finish [...]" but actually they are allowed to finish with only whatever existing connections are around. That is, the ClientConn would enter a sort of crippled draining state wherein one has to cross their fingers that it has enough underlying transports to finish the remaining work. Seems weird heh.

The current impl halts new RPCs from being created and waits for existing RPCs, after which it closes all transports and waits for them to shutdown before returning.

WDYT?

**Comment by dfawley** [comment]
@jadekler that's a good point, but it's not entirely clear what the user should expect when they do:

```go
c, _ := grpc.Dial(...) // non-blocking
go func() { res, err := c.Invoke(...); ... }()
c.GracefulClose()
```

There is an inherent race in the code above, and the user should not expect `Invoke` to succeed in the face of the `GracefulClose` call.  The other place where this could be an issue is with retry:

```go
c, _ := grpc.Dial(...) // non-blocking
s, _ := c.NewStream(...)
c.GracefulClose()
// s may fail the first attempt and need a retry including a reconnect to eventually succeed
```

We could say that `GracefulClose` allows current RPC _attempts_ to complete, and that no new RPC or retry attempts will be started.  In this case, we don't need to track in-flight RPCs.  My biggest worry is about adding synchronization code to the critical RPC path, which could impact performance.

**Comment by jadekler** [comment]
For posterity: the plan is let's come up with rationale about whether users care about the "diminished draining" state or not. If we can go that route it's better from the impl side: less things mucked about with streams.

**Pull request closed without merging**
