### PR TITLE
fmt code style

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by dfawley** [comment]
Thanks for the PR.

What is the motivation for the change in the switches?  I believe the existing style is more preferred to avoid an extra level of nesting.

**Comment by thinkerou** [comment]
I use the same as https://github.com/grpc/grpc-go/blob/master/go16.go#L60.

**Comment by dfawley** [comment]
I see, thanks.  If you're going for consistency, how about changing the other ones to this style instead?  IMO and as I understand Go style, it's better to avoid unnecessary indentation.

**Comment by thinkerou** [comment]
@dfawley Got it, thanks. Now I only adjust import order.

**Comment by dfawley** [comment]
Thank you for the cleanup PR.

**Pull request merged**
