### PR TITLE
 channelz: stage 4 - add security and socket option info

### PR DESCRIPTION
**Pull request by lyuxuan**
fix the build tags that previously break users.
Socketoption is only supported on linux system, as `GetsockoptTCPInfo` is only defined for linux environment.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2098)

### CODE REVIEW

**Comment by menghanl** [comment]
Review status: 0 of 19 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[channelz/types_nonlinux.go, line 1 at r1](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDD9W8E0cyqYNyjzZJn:-LDD9W8E0cyqYNyjzZJo:b-gurr59) ([raw file](https://github.com/grpc/grpc-go/blob/8e142ac9578bbb7c3d0cecbe7a66a3b6383a3bd6/channelz/types_nonlinux.go#L1)):*
> ```Go
> // +build !linux
> ```

Add an `init()` to log something.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2098)*

**Comment by menghanl** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[channelz/util_test.go, line 2 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDmyhocEQVIoZ75Lxi3:-LDmyhocEQVIoZ75Lxi4:b-1lzihy) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/channelz/util_test.go#L2)):*
> ```Go
> // +build linux
> // +build go1.10
> ```

Why is this 1.10?

---

*[channelz/service/service_test.go, line 1 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDmzV3J73Bs9obZKWad:-LDmzV3KBgflWbEcelvS:b-6oq6z4) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/channelz/service/service_test.go#L1)):*
> ```Go
> // +build linux
> ```

Only the socket related tests are platform specific, other tests should cover all platforms.

---

*[test/channelz_linux_go19_test.go, line 1 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDn-PK2B-INrBmlCD5L:-LDn-PK2B-INrBmlCD5M:b-zg756j) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/test/channelz_linux_go19_test.go#L1)):*
> ```Go
> // +build go1.10,linux
> ```

The file name is `go19`.

And why is this go1.10 and above only?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2098)*

**Comment by lyuxuan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[channelz/util_test.go, line 2 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDmyhocEQVIoZ75Lxi3:-LDnI8p3-GLm9uMyeLoW:b-lp2xqz) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/channelz/util_test.go#L2)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Why is this 1.10?
</blockquote></details>

This is because SyscallConn() function for net.TCPListener is added after go1.10. https://github.com/golang/go/commit/eed308de31e32a42012fd916d70cfed19280bbe7

---

*[channelz/service/service_test.go, line 1 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDmzV3J73Bs9obZKWad:-LDnIXgQAHhmOhqRzLP5:b3rn32l) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/channelz/service/service_test.go#L1)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Only the socket related tests are platform specific, other tests should cover all platforms.
</blockquote></details>

yeah, make sense. I split the test into 3 files, the base service_test.go which contains all the shared tests, service_linux_test.go, which contains linux necessary helper functions and tests, service_nonlinux_test.go, which contains nonlinux helper functions.

---

*[test/channelz_linux_go19_test.go, line 1 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDn-PK2B-INrBmlCD5L:-LDnJHhqEzVkjrEs-Sa8:blqc1xh) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/test/channelz_linux_go19_test.go#L1)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

The file name is `go19`.

And why is this go1.10 and above only?
</blockquote></details>

Wrong file name, should be go1.10. Good catch.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2098)*

**Comment by menghanl** [comment]
Review status: 19 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[channelz/util_test.go, line 2 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDmyhocEQVIoZ75Lxi3:-LDx019N3Zvq2kQaI2SX:brfx813) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/channelz/util_test.go#L2)):*
<details><summary><i>Previously, lyuxuan wrote…</i></summary><blockquote>

This is because SyscallConn() function for net.TCPListener is added after go1.10. https://github.com/golang/go/commit/eed308de31e32a42012fd916d70cfed19280bbe7
</blockquote></details>

Add comment to explain this.

---

*[channelz/service/service_linux_test.go, line 20 at r4](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDx0sdE7t5MBboSFuoq:-LDx0sdE7t5MBboSFuor:brcqv9m) ([raw file](https://github.com/grpc/grpc-go/blob/5d5baf6009ea45895c77c5c09816dc46b7dbf209/channelz/service/service_linux_test.go#L20)):*
> ```Go
>  *
>  */
> ```

Add file level comment for what's different between this and non-linux.

---

*[test/channelz_linux_go19_test.go, line 1 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDn-PK2B-INrBmlCD5L:-LDx0Hdo19FQfeAX-B1m:b-cgfl97) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/test/channelz_linux_go19_test.go#L1)):*
<details><summary><i>Previously, lyuxuan wrote…</i></summary><blockquote>

Wrong file name, should be go1.10. Good catch.
</blockquote></details>

Is this 1.10 the same reason as above? Add a comment as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2098)*

**Comment by lyuxuan** [comment]
Review status: 19 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[channelz/util_test.go, line 2 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDmyhocEQVIoZ75Lxi3:-LDxo8joBAtbpJOsm0xx:bb7f2mf) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/channelz/util_test.go#L2)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Add comment to explain this.
</blockquote></details>

done

---

*[channelz/service/service_linux_test.go, line 20 at r4](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDx0sdE7t5MBboSFuoq:-LDxo9sNEcNgK6v7mhjH:bb7f2mf) ([raw file](https://github.com/grpc/grpc-go/blob/5d5baf6009ea45895c77c5c09816dc46b7dbf209/channelz/service/service_linux_test.go#L20)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Add file level comment for what's different between this and non-linux.
</blockquote></details>

done

---

*[test/channelz_linux_go19_test.go, line 1 at r3](https://reviewable.io/reviews/grpc/grpc-go/2098#-LDn-PK2B-INrBmlCD5L:-LDxoBTXETOnRpXW_lb6:b-4i6fey) ([raw file](https://github.com/grpc/grpc-go/blob/e63f688da5e866c6c319f9b1ebe59df29b9b96ea/test/channelz_linux_go19_test.go#L1)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

Is this 1.10 the same reason as above? Add a comment as well.
</blockquote></details>

yes. done

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-go/2098)*

**Pull request merged**
