### PR TITLE
status: optimize GRPCStatus() calls

### PR DESCRIPTION
**Pull request by ash2k**
RELEASE NOTES: none

### CODE REVIEW

**Comment by arvindbr8** [comment]
Hi @ash2k, seems like the `GRPCStatus()` is only a getter and side effects (if any) arent obvious to me now. I'm curious how did you find this? Has this caused some sort of regression in callsites?

**Comment by ash2k** [comment]
Hi. It's a getter on gRPC's implementations, but it might be don't something in other implementations. It shouldn't have any side effects, but it may be allocating extra memory (e.g. to construct the object its returning), which is not required to do twice.

It didn't cause any problems, I was just looking at the gRPC code while working on my project and spotted this.

**Review by arvindbr8 — APPROVED** [review]
diff lgtm. 

I'm less concerned about the double calls since `gs.GRPCStatus()` is only a getter and does not have other side-effects (for eg, incrementing a counter).

cc: @easwars for another look

**Comment by arvindbr8** [comment]
closing and opening to re-run new tests

**Comment by ash2k** [comment]
I don't know why vet-proto job is failing. I've just rebased the branch but it didn't help.

**Comment by easwars** [comment]
> I don't know why the vet-proto job is failing. I've just rebased the branch but it didn't help.

vet-proto does not block merge. I've sent https://github.com/grpc/grpc-go/pull/6551 to fix the failure in the meantime.

**Review by easwars — APPROVED** [review]

**Pull request merged**
