### PR TITLE
docs: fix debugging README typo

### PR DESCRIPTION
**Pull request by adtac**
Testing PR access and stuff :)

### CODE REVIEW

**Comment by adtac** [comment]
test comment post-CLA

**Comment by adtac** [comment]
test comment

**Comment by adtac** [comment]
@jpalmerLinuxFoundation not sure if you fixed the CLA issue, but if you did, thanks!

Out of curiosity, may I know what the issue was? I've pretty much done everything the grpc docs asked me to (I think), so it'd be good to add to the documentation if it's missing something for future hires.

**Comment by jpalmerLinuxFoundation** [comment]
> @jpalmerLinuxFoundation not sure if you fixed the CLA issue, but if you did, thanks!
> 
> Out of curiosity, may I know what the issue was? I've pretty much done everything the grpc docs asked me to (I think), so it'd be good to add to the documentation if it's missing something for future hires.

@adtac, Hi Adhityaa, thank you for your patience.
     There does seem to be a defect in EasyCLA. It appears that you tried to sign an ICLA then left, then came back in to sign again. It appears that the app was only looking at your first ICLA record which indicated a `signed`: `false` status. 
     For employees of contributing companies, we request that you use your corporate email account  when using GitHub and follow these steps: https://github.com/communitybridge/easycla/blob/master/docs/Contribute-to-a-GitHub-Company-Project.md

**Pull request merged**
