### PR TITLE
Cherry pick pr 7571

### PR DESCRIPTION
**Pull request by purnesh42H**
Fixes: https://github.com/grpc/grpc-go/issues/7572

RELEASE NOTES: None

### CODE REVIEW

**Comment by arjan-bal** [comment]
Please update the version in the release branch to 1.66.2-dev before merging.

**Comment by easwars** [comment]
Also, please change the PR title to include the release branch into which we are cherry picking. See here for an example: https://github.com/grpc/grpc-go/pull/7019

**Comment by purnesh42H** [comment]
> Is there a reason to include the commit to change the version along with the other commit that you are cherry picking?

yeah that was a mistake of checking out from previous patch release branch. I have created a separate PR

**Comment by arjan-bal** [comment]
FYI: This is the PR that will be merged: https://github.com/grpc/grpc-go/pull/7616

**Pull request closed without merging**
