### PR TITLE
syscall: remove logging in init().

### PR DESCRIPTION
**Pull request by yangminzhu**
The same as https://github.com/grpc/grpc-go/pull/2373.

@dfawley Could you help review this? Thank you.

Signed-off-by: Yangmin Zhu <ymzhu@google.com>

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @yangminzhu isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @yangminzhu isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by yangminzhu** [comment]
I signed it

**Comment by menghanl** [comment]
Thanks for the fix!

**Pull request merged**
