### PR TITLE
envconfig: Make it easier to find env vars in grok tools

### PR DESCRIPTION
**Pull request by easwars**

### CODE REVIEW

**Review by dfawley — COMMENTED** [review]
The exact string matches in the comments immediately below weren't sufficient?

Any reason to keep the consts, even?

**Comment by easwars** [comment]
> The exact string matches in the comments immediately below weren't sufficient?
> 
> Any reason to keep the consts, even?

I have deleted the consts. But I don't remember exactly the reason why started on this PR. I don't mind closing. Let me know.

**Comment by easwars** [comment]
> > The exact string matches in the comments immediately below weren't sufficient?
> > Any reason to keep the consts, even?
> 
> I have deleted the consts. But I don't remember exactly the reason why started on this PR. I don't mind closing. Let me know.

I think we should move the logging related environment variables to this package. Having one place where all environment variables are declared would make it nice.

I *think* that was the reason why I started out on this, saying all environment variables should be defined in one place. But then I forgot about the real reason, and only changed stuff in this package.

**Comment by dfawley** [comment]
> But I don't remember exactly the reason why started on this PR.

If we don't have a good reason for making a change, I'd prefer to leave things alone to minimize churn (merge conflicts, commit history, etc).  If you remember why you wanted to do this, then we can always reopen/redo it.

**Pull request closed without merging**
