### PR TITLE
Insecure ClientConn made explicit

### LINKED ISSUE #307: Make insecure ClientConn as explicit
Requested by our security team, I will make some change to change the default security setting of ClientConn to TLS. If users need insecure ClientConn, they have to request it explicitly via a dialOption. 

This change will probably lead to breakage. Sorry about the inconvenience. But this will provide better protection for your service and customers.

### PR DESCRIPTION
**Pull request by iamqizhao**
users have to set grpc.WithInsecure() DialOption when they want an insecure ClientConn. Fixes #307

### CODE REVIEW

**Comment by tsuna** [comment]
This causes runtime problems in existing code.  The code still compiles fine, but existing tests for instance now fail with `	foo_test.go:88: Failed to connect to [::]:58898: grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)`.

Not cool :(

**Comment by iamqizhao** [comment]
Sorry for the breakage. We have to do some API breaking changes in Alpha to
minimize the future risk which is harder to address in beta and GA.

**Comment by tsuna** [comment]
If the API changes break compilation, that's fine, it's easier to catch.  Runtime breaks are trickier ;o

**Comment by iamqizhao** [comment]
understood. Unfortunately I did not find a good way to generate a
compilation failure for this change unless I rename grpc.Dial which is not
acceptable.

**Pull request merged**
