### PR TITLE
xdsclient: improve authority watchers test

### PR DESCRIPTION
**Pull request by easwars**
Improve authority watchers test by moving to an e2e style test which verifies functionality without relying on any internal state.

This PR is similar to how the LDS watchers test was cleaned up in https://github.com/grpc/grpc-go/pull/5506.

#resource-agnostic-xdsclient-api

RELEASE NOTES: n/a

### CODE REVIEW

**Comment by easwars** [comment]
Ping @dfawley

**Review by dfawley — APPROVED** [review]
LGTM. I'm a bit concerned about the classification of these as "end to end tests", since they don't actually test gRPC servers or clients, or anything we expose externally to the user for that matter.  These are really system level tests for the xdsclient package, right?  (And as such, probably belong under the xdsclient directory somewhere instead, as they were before.)

**Comment by easwars** [comment]
> LGTM. I'm a bit concerned about the classification of these as "end to end tests", since they don't actually test gRPC servers or clients, or anything we expose externally to the user for that matter. These are really system level tests for the xdsclient package, right? (And as such, probably belong under the xdsclient directory somewhere instead, as they were before.)

These are e2e tests from the point of view of the xds client, since it uses only exported APIs (and creates a new client and tests the scenarios being tested). The main reason I want these tests in a separate package is because our previous tests lived in the same package and ended up relying too much on internal state and being over-specified. I could have put them in the same directory, but in an `xdsclient_test` package (but I thought being in a separate directory helps a little since there is a lot of code in this directory).

**Comment by dfawley** [comment]
That's fine, but I do think a package named `e2e` should be reserved for _gRPC_ end to end tests, not tests done at the API level for a single package.  Using a separate directory is OK, but I think it should be a different one, ideally under the `xdsclient` directory, e.g. `xdsclient/test`.

**Comment by easwars** [comment]
Fair point. I can change that once the last test PR (in this round) is in.

**Pull request merged**
