### PR TITLE
Fix typo in encoding.md

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by easwars** [comment]
Could you please sign the CLA.

**Comment by fenollp** [comment]
Hi @easwars I did sign this already and EasyCLA's CI job passes. Am I doing something wrong?

**Comment by fenollp** [comment]
I've signed it again with a different email address but am unsure that has changed anything.

**Comment by easwars** [comment]
> I've signed it again with a different email address but am unsure that has changed anything.

Thanks. The CLA seems to be signed and is good.

**Review by easwars — APPROVED** [review]

**Comment by easwars** [comment]
Hmm ... not sure why the tests aren't running.

**Comment by dfawley** [comment]
Interesting. I have an exclusion in the workflow for `Documentation/**`, so it makes sense that it's not running.  But, it seems the PR merging requirements don't understand that.  We can force merge this, but I wonder if there's some way to make these tests either auto-pass in this case or not be required for a normal merge.

**Pull request merged**
