### PR TITLE
Clarify newCCResolverWrapper documentation.

### PR DESCRIPTION
**Pull request by gnoack**
I think the goroutine does not get started any more (this used to be the case in an earlier version).

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @gnoack isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by gnoack** [comment]
Hmm, the LinuxFoundation page says "You are already authorized to contribute code to this project through your membership with Google." Not sure why this is still red. I'll give it another day or so, in case it's a propagation delay.

**Comment by gnoack** [comment]
Ah, it worked :)

**Comment by menghanl** [comment]
Thanks!

**Pull request merged**
