### PR TITLE
*: fix typos

### PR DESCRIPTION
**Pull request by hakusai22**
fix typo

RELEASE NOTES: none

### CODE REVIEW

**Comment by dfawley** [comment]
Thanks for the PR.

Please revert the generated code (*.pb.go) as those are just copied from the source .proto file.  If you want to fix those, too, they are in http://github.com/grpc/grpc-proto.

Also, what tool are you using for this?  We may want to add it to our presubmit checks.

**Comment by hakusai22** [comment]
> Thanks for the PR.
> 
> Please revert the generated code (*.pb.go) as those are just copied from the source .proto file. If you want to fix those, too, they are in [http://github.com/grpc/grpc-proto](https://github.com/grpc/grpc-proto).
> 
> Also, what tool are you using for this? We may want to add it to our presubmit checks.

done. Thanks for the reply, I am using this tool https://github.com/crate-ci/typos

**Review by dfawley — APPROVED** [review]
Thank you for the PR.

**Review by arvindbr8 — APPROVED** [review]

**Comment by arvindbr8** [comment]
Thanks. Very wholesome

**Pull request merged**
