### PR TITLE
Add doc.go to grpc_lb_v1 for 1.7.x branch

### PR DESCRIPTION
**Pull request by jpbetz**
Replaces https://github.com/grpc/grpc-go/pull/1743

### CODE REVIEW

**Comment by jpbetz** [comment]
@dfawley

**Comment by jpbetz** [comment]
Test failure:

```
grpclb/grpc_lb_v1/doc.go:21:1: don't use an underscore in package name
```

**Comment by jpbetz** [comment]
Added an list of ignored golint files.

**Comment by menghanl** [comment]
FYI, just did [`1.7.5` release](https://github.com/grpc/grpc-go/releases/tag/v1.7.5).

**Comment by jpbetz** [comment]
Thanks @menghanl ! Applying 1.7.5 to kubernetes now. Tests are passing locally and I expect https://github.com/kubernetes/kubernetes/pull/57160 once e2e tests pass.

**Pull request merged**
