### PR TITLE
changes to support flatbuffers

### PR DESCRIPTION
**Pull request by JRonak**
inital changes for #880

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Can't this be archieved using a custom codec? Using https://godoc.org/google.golang.org/grpc#WithCodec and https://godoc.org/google.golang.org/grpc#CustomCodec.

Otherwise people not using flatbuffers still import the package.

**Comment by JRonak** [comment]
@Thomasdezeeuw flatbuffers code foot print is very small. 
If we go ahead with the custom codec, codec has to be generated for every struct by flatbuffers compiler

**Comment by Thomasdezeeuw** [comment]
And what about adding Cap 'n Proto? And after that Apache Avro, then Apache Thrift, etc. Then we'll need to import 5 more packages, without even using them. My point is that this can already be achieved without adding code to gRPC, so I don't think this needs to be added to gRPC. But that is just my opinion.

**Comment by iamqizhao** [comment]
As @Thomasdezeeuw pointed out, this should not be in grpc package. I actually do not get your point on flatbuffer compiler (haven't got time to look into that) and why putting it into grpc package can address the issue.

**Comment by JRonak** [comment]
@Thomasdezeeuw got it.
@iamqizhao Let me explain
If we do not implement the Codec interface for flatbuffers here, then it has to be written in every package generated by flatbuffers compiler for grpc service, though it would solve the problem pointed out above.

**Comment by iamqizhao** [comment]
grpc-go itself won't take this unnecessary dependency. You can put that into https://github.com/grpc/grpc-contrib so other people can use that.

**Pull request closed without merging**
