### PR TITLE
Add ServerStream.SetContextMetadata method

### PR DESCRIPTION
**Pull request by shaxbee**
To add feature parity between StreamServerInterceptor and UnaryInterceptor way of passing additional metadata to the handler for stream method is needed.

I've added ServerStream.SetContextMetadata which delegates to transport.Stream.SetContextMetadata method to set the metadata.

In my case i use it in custom interceptor to pass decoded JWT Subject information to handler.

### CODE REVIEW

**Comment by iamqizhao** [comment]
You can use Context() on grpc.ServerStream object directly.

**Comment by iamqizhao** [comment]
a bit more elaboration: you can call Context() to get the context object and attach your data onto that. And then have a new grpc.ServerStream impl whose Context() returns your modified context object. You should use this new ServerStream to call the StreamHandler.

**Comment by shaxbee** [comment]
@iamqizhao I think you misunderstood intention of this PR - the idea here is to modify context metadata in interceptor and make those changes visible to Handler by updating ServerStream context.

**Comment by iamqizhao** [comment]
I think I did not. I described the way to get the ctx and feed it back to the handler with the modifications without adding any API.

**Comment by shaxbee** [comment]
Sorry, I haven't seen your 2nd reply as we posted at roughly same time.
Context injection for Stream methods is much harder right now compared to Unary methods.
Would adding `func ServerStreamWithContext(ss ServerStream, ctx Context) ServerStream` be a better solution then?

**Comment by iamqizhao** [comment]
I agree it is a bit harder than the unary case. I am pretty strict on adding any new public API to the lib though. It seems you can define and impl this function in your own code base?

**Comment by shaxbee** [comment]
I completely understand that adding new public API is not a lighthearted decision. It his highly likely though that users of library will be looking for a way to inject metadata into context which is easy in unary case, but quite tricky for stream, having library support for such operation will make it much less 'hacky' too. Can we at least leave this PR open for discussion in case someone else tries to solve same problem?

**Comment by iamqizhao** [comment]
It is not hard to add a simple wrapper to make this work simple. We will have a contrib repo to host the contributions from our users and I think you can make one for ppl having the same requirements there.

**Comment by shaxbee** [comment]
Created Gist for reference: [sscontext.go](https://gist.github.com/shaxbee/a87e2c028a21c60e5aace593a23b27a1)

**Pull request closed without merging**
