### PR TITLE
Behavior change: Transport connection errors should have code Unavail…

### PR DESCRIPTION
**Pull request by MakMukhi**
…able
#1086

### CODE REVIEW

**Comment by adelez** [comment]
@dgquintas. Based on an email discussion, it seems that the solution is still undecided.

**Comment by xoebus** [comment]
`Unavailable` is an error that the `codes` package claims can be retried. How should a `credentials.TransportCredentials` implementation return a fatal error to stop any unnecessary retries?

**Comment by menghanl** [comment]
@xoebus gRPC won't retry if `credentials.TransportCredentials` returns non-temporary errors. It doesn't depend on the error code returned.

**Comment by xoebus** [comment]
@menghanl Great, thanks.

**Comment by garye** [comment]
Can we submit this now that https://github.com/grpc/grpc/pull/9748 has landed?

**Comment by MakMukhi** [comment]
Closing with #1307

**Pull request closed without merging**
