### PR TITLE
resolver: move dns and passthrough to internal

### PR DESCRIPTION
**Pull request by dfawley**
Nobody should directly need to reference these packages.

This is technically a breaking change.  However:

- Package dns was exporting a `NewBuilder` method.  This should never have been necessary to use, but if so, it can be replaced by importing the "grpc" package and then using `resolver.Get("dns")`.
- Package passthrough was not exporting any symbols and there was never a need to even blank-import it.

### CODE REVIEW

**Comment by easwars** [comment]
Would it be better to move the files to `internal/resolver/dns` and `internal/resolver/passthrough` directories?

**Comment by dfawley** [comment]
> Would it be better to move the files to internal/resolver/dns and internal/resolver/passthrough directories?

I'm not too bothered either way.  We can rearrange it now or later if we want since it's all internal.  What are the pros and cons?

**Comment by easwars** [comment]
> > Would it be better to move the files to internal/resolver/dns and internal/resolver/passthrough directories?
> 
> I'm not too bothered either way. We can rearrange it now or later if we want since it's all internal. What are the pros and cons?

I guess it's just a matter of preference :)
Although, both of them being resolvers, might be logical to put them under a parent `resolver`directory.

**Comment by dfawley** [comment]
Both seem equally fine to me.  `passthrough` is a bit of a weird name by itself, and @menghanl also preferred `resolver/` so I moved them.

**Comment by owend** [comment]
Just curious, but does this change make it impossible to build older versions of any packages which might still depend on older versions of grpc which then recursively require the resolver/dns and resolver/passthrough packages being at the old location?  

Oh, while I was typing this up I noticed there's a new bug open #3157 

This change was released in 1.25.0 two days ago and now I am seeing build failures:

Solving failure: No versions of go.etcd.io/etcd met constraints:
	v3.4.3: Could not introduce go.etcd.io/etcd@v3.4.3, as it requires problematic packages from google.golang.org/grpc (current version v1.25.0):
google.golang.org/grpc/resolver/dns is missing.	
google.golang.org/grpc/resolver/passthrough is missing.

**Pull request merged**
