### PR TITLE
Introduce PickerBuilderV2 that can take address weight into account.

### PR DESCRIPTION
**Pull request by alazarev**
To make code backward compatible Weight is added to new struct resolver.WeightedAddress having old Address untouched.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by alazarev** [comment]
resolved

**Comment by alazarev** [comment]
CLA signed

**Comment by menghanl** [comment]
Is this PR mainly to add weight support to package `balancer/base`?
Note that `balancer/base` and `PickerBuilder` are not part of the official balancer API (which lives in package `balancer`). They are more like convenience utilities for users to create "simple" balancers.

---

If the answer is yes, we are mainly dealing with `balancer/base`, we can actually put the weights in address's metadata field. We just need to remember to clear the weight field before using the address as map keys.

What I think would work:
1. Add a struct `balancer/base.AddrInfo`
1. In your resolver implementation where weight is known, set weight field in `base.AddrInfo`, and add it to address's metadata
1. In base balancer, once address list is received, clear weights in each address and store them somewhere else
1. We can still do `PickerBuilderV2` to extend the builder API

Let us know what you think of this.

---

(Another thing to mention is that for xds balancer, weights are retrieved in the balancer, so this info doesn't need to be passed from resolver.)

**Comment by euroelessar** [comment]
I guess the main point is that we want to have an ability to use the same XDS control plane for performing per-endpoint weighting decisions for both gRPC and Envoy stacks.

So the primary initial goal is to somehow expose weights from XDS balancer to the next tier.
All other changes (in base balancer, introduction of new API, etc) are for backward compatibility only, to not break existing balancer implementations if used in conjunction with XDS.

It's worthwhile to note, that "reconnecting on weight changes" is considered as breakage as it leads to significant extra cpu cost.

**Comment by euroelessar** [comment]
> If the answer is yes, we are mainly dealing with `balancer/base`, we can actually put the weights in address's metadata field. 

Wouldn't it break existing balancer implementations if used together with xds?
Instead of just ignoring weights they will ignore weights _and_ recreate all connections on every update.

**Comment by menghanl** [comment]
Right, to support passing weights from xds to sub-balancers, the change has to be generic. And can almost certainly only be done at the resolver/balancer API level.
Also, we cannot simply add fields to the address type, as it could trigger unnecessary reconnecting on weight changes.

I can think of two options:

1. Wrap `resolver.Address` into another struct (as what's done in this PR)
   - Note that it's an API change. All balancer implementations will need to change their methods to accept the new AddressWithWeight type.
   - We can add another set of APIs, so we don't break existing users

1. We keep `resolver.Address` as is, and add another field to [`resolver.State`](https://github.com/grpc/grpc-go/blob/120728e1f775e40a2a764341939b78d666b08260/resolver/resolver.go#L106), which can be a map from address to weight (or another struct so we can add more fields in to future).
   - This adds a field, so it doesn't affect existing implementations.
   - If a balancer doesn't support weights, it can simply ignore this new field, as all the existing balancers will do.
     - But this also means the old balancers won't even know about the new information, and if we expect them to honer the weights, the behavior will be wrong. This might be acceptable though.

I currently prefer option 2, mainly because it doesn't change the API. Let me know what you think.

cc @dfawley

**Comment by alazarev** [comment]
But option 2 will still require API change for balancer (PickerBuilderV2 and AddrInfo structs in PR). Having that I don't see much difference between options 1 and 2 (just a way how resolver.State is organized internally). Can change PR to option 2 if you believe it is cleaner.

**Comment by menghanl** [comment]
The difference is, changing types in package `resolver` will affect all users of `resolver`/`balancer`, while changing `balancer/base` will only affect users of `base`.
And if the users don't care about weight, they can keep using `PickerBuilder`, it's just that they won't know about the address weights.
(An immediate difference for the changes in this PR is, you won't need to make any changes to the balancer implementations like `balancer/grpclb` and `balancer/xds`, because they don't need to handle the weights).

---

Thinking more about the option to add a field to type address (which will affect hashing).
It will cause unnecessary reconnecting only in the case that the balancer doesn't understand weights. If the balancer knows this field is for weights, it can remove it before hashing, and things will work as normal.

Then the question is, what does a balancer do if it doesn't understand weights but gets passed weights? And will we ever give addresses with weights to balancers that don't understand them?

**Comment by alazarev** [comment]
Tried to implement option 2 (extra map in resolver.State). What I don't like about this option we should always remember to copy/check weights when we access Addresses. It will be really easy to forget in new code.

>Then the question is, what does a balancer do if it doesn't understand weights but gets passed weights? And will we ever give addresses with weights to balancers that don't understand them?

Potentially yes. But I agree that chances are pretty low. Are you fine with breaking backward compatibility in such rare cases? (having in mind that change will not break code, it can only potentially increase number of reconnects),

**Comment by menghanl** [comment]
>> Then the question is, what does a balancer do if it doesn't understand weights but gets passed weights? And will we ever give addresses with weights to balancers that don't understand them?

> Potentially yes. But I agree that chances are pretty low. Are you fine with breaking backward compatibility in such rare cases? (having in mind that change will not break code, it can only potentially increase number of reconnects),

This actually sounds OK I think.
Assuming that the client will have the correct config, and that we will pick a specific weighted round robin balancer explicitly.

To support weight round robin, what will happen is, the xds balancer (or ClientConn if it's not sub-balancer of xds) will get the balancer registered with name `"weighted_round_robin"` (or something similar). A default weighted round robin balancer will be registered, and users can override it with another one if they want. All weighted round robin balancers should know how to handle weights. 
Unless the client explicitly registers a balancer that cannot handle weights under this name, I think nothing will be broken.

We may need to define a common struct (like `wrr.Info` in a `wrr` package`) to be put in address's metadata field so all weighted round robin implementations can understand the same inputs.

**Comment by alazarev** [comment]
Created https://github.com/grpc/grpc-go/pull/2944 just to show how change with map in resolver.State will look like.

**Comment by alazarev** [comment]
>We may need to define a common struct (like wrr.Info in a wrr package`) to be put in address's metadata field so all weighted round robin implementations can understand the same inputs

Can we use entire metadata field for wrr? Or should we introduce some kind of map here and wrr will be just one of the fields?
Do you expect other use cases for Address metadata?

**Comment by alazarev** [comment]
https://github.com/grpc/grpc-go/pull/2945 for Weight in wrr.Info stored as metadata.

**Comment by alazarev** [comment]
@menghanl Does #2945 look like right direction? If yes, I can clean up code and add tests?

**Comment by menghanl** [comment]
#2945 in general looks good. I will comment in that PR.
And I will close this now.

**Pull request closed without merging**
