### PR TITLE
add an etcd client for grpc name resolution

### PR DESCRIPTION
**Pull request by yangzhouhan**

### CODE REVIEW

**Comment by dsymonds** [comment]
Why does this belong here rather than in some etcd repo?

**Comment by iamqizhao** [comment]
etcd does have a client to achieve this. We only need a couple of very thin functions here. @yangzhouhan Please revise.

**Comment by dsymonds** [comment]
I'm still not sure I understand why something etcd-specific is needed in the grpc repo. Shouldn't grpc instead provide a general API for name resolution such that *any* scheme can plug into it?

**Comment by iamqizhao** [comment]
Without adding an additional general API, we will still use grpc.Dial to do connection but the param could be a custom name, and grpc.Dial should take an DialOption to define how to do name resolution for that custom name. And we will provide a DialOption impl for etcd-based name service. What Zhouhan is doing is to provide some convenience functions to implement this etcd-based DialOption. I think it is equavelant to what you think of. Any better idea is welcome.

**Comment by dsymonds** [comment]
That approach seems fine; I'm just suggesting that the etcd implementation of that doesn't need to live here but should live in the etcd repo. Otherwise, are we going to collect a dozen different implementations of this here?

**Comment by iamqizhao** [comment]
I would like to provide an example using a popular open-sourced kv store solution as a showcase on how to do custom name resolution. zookeeper and etcd are only well-accepted solutions in open-source world. zookeeper does not have go client and does not support http-based operations. So I would say the etcd-based example will be the only one in grpc-go repo in the foreseeable future (grpc-C++ will have both.).  We will have another Google-internal one though.

**Pull request closed without merging**
