### PR TITLE
protoc-gen-go-grpc: Fixed option typo in README.md file

### PR DESCRIPTION
**Pull request by eko**
RELEASE NOTES: N/A

### CODE REVIEW

**Review by menghanl — APPROVED** [review]
Thanks for the fix. LGTM.

**Review by dfawley — CHANGES_REQUESTED** [review]
I think this is wrong.  The `opt` flag doesn't accept `:<output_location>` at the end, does it?  What error are you getting when you use it as documented?

**Comment by eko** [comment]
Hi,

You're right, I didn't see the `.` at the end, I just updated the command :)

Thank you

**Comment by dfawley** [comment]
Was there something wrong with the previous command for you?  This is [how we run it](https://github.com/grpc/grpc-go/blob/9cb411380883ddbf69467b4ba1099817c0fe6c61/regenerate.sh#L107) and it works fine.

**Comment by eko** [comment]
You're right again  @dfawley, it seems to also work as it is so I close this PR :)

I've seen that Protobuf also supports a `_opt` suffix to specify options (see: https://github.com/protocolbuffers/protobuf/pull/6999) so I'm using it in my projects but passing options using `,` separator to `_out` suffix is also working correctly.

Thank for your time.

**Pull request closed without merging**
