### PR TITLE
Fix err handling of malformed http2

### PR DESCRIPTION
**Pull request by iamqizhao**

### CODE REVIEW

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://go-review.googlesource.com/20077 (at git rev fe861cb)

**Comment by bradfitz** [comment]
Comments in https://go-review.googlesource.com/#/c/20077/1

**Comment by iamqizhao** [comment]
how to push a patch set to gerrit?

**Comment by LetsUseGerrit** [comment]
Head d614b8ab18d51bcba04f5e2dc6f5d564e2f296ec has 2 commits. Please squash your commits into one. @LetsUseGerrit only supports syncing a pull request with a single commit, as that is how Gerrit is typically used.

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://go-review.googlesource.com/20077 (at git rev f3c6dc5)

**Pull request merged**
