### PR TITLE
transport: use http2.Framer's MetaHeadersFrame functionality

### PR DESCRIPTION
**Pull request by bradfitz**
The Framer now has support for merging HEADERS+CONTINUATION frames.
This remove the frame merging & hpack state machine from grpc.

In addition to being more compliant with the spec, this also means
gRPC enforces the header list size, removing a DoS vector.

### CODE REVIEW

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://go-review.googlesource.com/19903 (at git rev a1adcd4)

**Comment by bradfitz** [comment]
Whoops, I forgot to run all the tests. Fixing...

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://go-review.googlesource.com/19903 (at git rev 15de328)

**Comment by bradfitz** [comment]
PTAL. The `TestInvokeLargeErr` test is fixed now. It wasn't speaking valid http2 before but it wasn't being detected until now.

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://go-review.googlesource.com/19903 (at git rev 8241265)

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://go-review.googlesource.com/19903 (at git rev ac5c8d7)

**Pull request merged**
