### PR TITLE
Use codes.Code.String() rather than logging integers

### PR DESCRIPTION
**Pull request by tamird**
This produces better human-readable error messages.

### CODE REVIEW

**Comment by tamird** [comment]
This is green. Who's the maintainer of this project now? Please have a look.

**Comment by tamird** [comment]
@menghanl?

**Comment by menghanl** [comment]
This is actually a behavior change.
Is this very necessary?

**Comment by tamird** [comment]
Yeah, it's a minor behaviour change, but the current errors are quite difficult to deal with. Do you think someone is depending on the string representation of this error?

**Comment by menghanl** [comment]
I don't know of anyone depending on the string.

**Comment by tamird** [comment]
@menghanl so, is this good to go?

**Comment by menghanl** [comment]
Merging this because I depending on the string doesn't look like the right thing.

**Comment by tamird** [comment]
Thanks!

**Pull request merged**
