### PR TITLE
grpc: rename request trace family from "Sent" and "Recv" to "grpc.Sent" and "grpc.Recv"

### PR DESCRIPTION
**Pull request by Sajmani**

### CODE REVIEW

**Comment by dsymonds** [comment]
what about the "Recv" family?

I think you should split out the rename from the addition of `trace.EventLog`. The first is a lot less controversial.

**Comment by Sajmani** [comment]
Strange, I thought I *did* create a separate PR for just the rename of the family.  I pushed the second commit *after* I created this PR.  I'm still new to this stuff.  I'm happy to split out the renames into their own PR, if I can figure out how to do it :-)

As for Recv, I didn't realize it was present in gRPC (I thought only Sent was supported so far).  Certainly they should both be changed together.  I'll update it in another commit (then somehow figure out how to create a PR with just the rename commits).

**Comment by dsymonds** [comment]
A pull request applies to the whole series of commits that you stack on each other (unlike Gerrit, which will make a new change for each commit). You'll need to make separate branches for independent changes.

**Comment by Sajmani** [comment]
Hmm, I did the renamings in branch "tracename" and the event log change in branch "events".  But I guess when I did "git push" to my fork, they all got collapsed back into "master".

**Comment by Sajmani** [comment]
Ok, reverted the clientconn changes for now.  I'll figure out how to push them to a different branch tomorrow.

**Comment by dsymonds** [comment]
current state LGTM.

**Comment by iamqizhao** [comment]
@Sajmani Thanks for the contribution. :)

**Pull request merged**
