### PR TITLE
xdsclient: handle race with watch timer handling

### PR DESCRIPTION
**Pull request by easwars**
This PR handles a race wrt to timer expiry which can occur if the management server responds to a resource (for which a watch has been registered), but a request has not yet been sent.

Release notes are not required for this, since the A57 changes have not yet made it to any release.

Fixes https://github.com/grpc/grpc-go/issues/6069.

RELEASE NOTES: none

### CODE REVIEW

**Comment by arvindbr8** [comment]
Can the mgmt server send response for a resource for which we didnt send a request yet IRL? or do you think this is because the tests dont replicate an actual scenario?

**Comment by easwars** [comment]
> Can the mgmt server send response for a resource for which we didnt send a request yet IRL? or do you think this is because the tests dont replicate an actual scenario?

Management server is free to send whatever resources it deems fit. If we receive a resource which we haven't requested, we are supposed to drop it on the floor without making any noise.

In this case though, when we receive the resource from the management server, we think that it is a resource that we have requested (because we have an entry in the `resourceState` map). But the resource has not been actually requested, since the state is `started` and not `requested`. We might have to think a little more about this to see if we require more of a design change. 

Feel free to push back on this PR if you think that the changes in this PR aren't what we want in the long run, and that we should think about design changes first.

**Comment by arvindbr8** [comment]
This makes sense to me. Which also means we are adding a new transition to the watch state machine (from started to received). Although the fussiness in the test is forcing this transition, should we also add a unit so that we explicitly test it?

**Review by arvindbr8 — APPROVED** [review]

**Comment by easwars** [comment]
> This makes sense to me. Which also means we are adding a new transition to the watch state machine (from started to received). Although the fussiness in the test is forcing this transition, should we also add a unit so that we explicitly test it?

Yes, we should write one after the redesign.

**Pull request merged**
