### PR TITLE
fix context import

### PR DESCRIPTION
**Pull request by dreambo8563**
cleanup: replace "x/net/context" import with "context" (#2439)

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @dreambo8563 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by dreambo8563** [comment]
signed

**Comment by dreambo8563** [comment]
sign again

**Comment by menghanl** [comment]
This file is generated, and shouldn't be manually edited.
Also, if you use go1.9 and above, this shouldn't be a problem because "golang.org/x/net/context" is just a type alias.

The [codegen change](https://github.com/golang/protobuf/pull/742) is already submitted upstream. We are waiting for a new release to update out dependencies.

**Pull request closed without merging**
