### PR TITLE
cleanup: fix typo in grpclib_remote_balancer.go

### PR DESCRIPTION
**Pull request by jamesxuhaozhe**
Minor typo fix in grpclib_remote_balancer.go.

change balaner with balancer

### CODE REVIEW

**Comment by menghanl** [comment]
Hmm, travis state is still pending. But it seems the tests finished and passed: https://travis-ci.org/github/grpc/grpc-go/builds/668893833

Closing and reopening didn't help...

**Comment by jamesxuhaozhe** [comment]
thanks for reviewing, but is there a way to get travis to finish ?

**Comment by menghanl** [comment]
There's not much we can do other than close/reopen. This is also happening on other PRs, so it might be a github or travis problem. We will merge this later once the travis status turns green.

**Comment by jamesxuhaozhe** [comment]
> There's not much we can do other than close/reopen. This is also happening on other PRs, so it might be a github or travis problem. We will merge this later once the travis status turns green.

got it. Thank you !

**Pull request merged**
