### PR TITLE
lint: fix some unused parameter issues

### PR DESCRIPTION
**Pull request by rleungx**
Remove some unused parameters.

RELEASE NOTES: None

### CODE REVIEW

**Comment by zasweq** [comment]
This doesn't feel right. Assigning to file owner Ashitha to take a look. This looks like it creates functional change as well. Also, our vet didn't seem to complain around these files.

**Comment by ashithasantosh** [comment]
> This doesn't feel right. Assigning to file owner Ashitha to take a look. This looks like it creates functional change as well. Also, our vet didn't seem to complain around these files.

I only own rbac_translator.go, and the changes there LGTM. Thanks for doing this.
You may want to add other file owners to reviewer list.

**Comment by dfawley** [comment]
@zasweq you said you may have noticed a behavior change somewhere?  If so, please comment the line.  I quickly reviewed and everything seemed correct, but I didn't look super closely, either.

**Comment by zasweq** [comment]
LGTM, outside of the vet failure. Thanks for this. I had an unused testing.T parameter in my cluster handler test that I based off other tests in the codebase (both of which got removed), which I thought was required for testing haha.

**Comment by dfawley** [comment]
`vet-proto` is not required to pass to submit; this appears to be unrelated.  I'll merge this now.

**Review by dfawley — APPROVED** [review]

**Pull request merged**
