### PR TITLE
allow storing alternate transport.ServerStream implementations in context

### LINKED ISSUE #1802: Unary RPCs in server cannot set metadata with alternate transports
There is currently an API deficiency in that alternate transports (such as in-process dispatch or other custom mechanisms) cannot support the server sending metadata from unary RPCs.

The issue is that the API for sending metadata from a unary RPC handler is to call `grpc.SetHeader` and `grpc.SetTrailer`. However, these methods *require* that there be an active `*transport.Stream` in [the](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/server.go#L1275) [given](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/server.go#L1285) [context](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/server.go#L1305).

If this API instead expected an interface that provided these three methods (as opposed to the concrete type `*transport.Stream`), then an alternate transport could store its own stream interface in the context, allowing it to receive the metadata and ensure they are delivered to the client.

This would also require making a public API for injecting the stream into a context. Currently, there is only an [unexported method](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/transport/transport.go#L440) which puts a `*transport.Stream` into the context (the associated context key is, of course, also unexported).

(Note that, even if this is fixed, there is a client-side problem with receiving the metadata, too: see #1494 and #1495.)

### PR DESCRIPTION
**Pull request by jhump**
Fixes #1802.

This allows handlers to be run from tests without requiring the entirety of the gRPC server machinery: a test can store a mock `transport.ServerStream` into the context and then call the handler.

It also enables alternate transport implementations.

### CODE REVIEW

**Comment by jhump** [comment]
@dfawley, might you have some time today or later this week to take a look at this (and at #1902)?

**Comment by jhump** [comment]
Ping?

**Comment by dfawley** [comment]
A couple observations/quesitons:

- The transport package is supposed to be grpc-internal-only; this would presumably expose an API for users?
- If grpc-go natively had an in-process transport, would this still be useful?

**Comment by jhump** [comment]
> The transport package is supposed to be grpc-internal-only; this would presumably expose an API for users?

In it's current form, it does -- the mechanism for storing a transport stream into context. But I think I can move stuff around so that is not the case (so that new exported API is in the main `grpc` package, not in `transport`).

> If grpc-go natively had an in-process transport, would this still be useful?

I suppose it depends. If, in the process of creating an alternate transport, the gRPC library gained better abstractions that de-couple the interfaces from the existing singular implementations, then maybe! But if there were no additional abstractions provided for custom transports, then that would only help so much.

We also want this for an HTTP 1.1 transport implementation. And, generally, abstracting these details so that custom transports can be used is IMO very empowering to users.

Another argument for something like this is to resolve #1494, to make the interceptor model generally more coherent. As is, only streaming interceptors can actually intercept response metadata (both client and server sides). But this change makes it possible for a unary interceptor to do so -- by installing its own "transport stream" implementation in context that can intercept metadata and forward to the real stream. (Similarly, #1902 enables intercepting metadata for unary RPCs on the client side.)

**Comment by jhump** [comment]
I pushed a change so that new API is in the main `grpc` package (not in `transport`). This results in a change to the exported API of the `transport` package: no more `StreamFromContext` method. (If that package were not meant to be used by anything other than gRPC internals, I expect that is okay.)

@dfawley: Does this seem better?

**Comment by jhump** [comment]
ping

**Comment by jhump** [comment]
Thank you @dfawley! I understand that it is not ideal. I do appreciate you merging it anyway.

**Comment by trusktr** [comment]
For anyone stumbling on this, this commit perfectly describes how to fix `undefined: transport.StreamFromContext` (or why there's no bin file after go install): https://github.com/jfyne/docker-grpcwebproxy/commit/da712301bde103014e7becbac0fa298384bf622f

For example, I had this problem with http://github.com/improbable-eng/grpc-web, and the following worked:

```js
go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
cd $GOPATH/src/github.com/improbable-eng/grpc-web
brew install dep # install golang/dep somehow
dep ensure
go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
```

After that `$GOPATH/bin/grpcwebproxy` was available.

**Pull request merged**
