### PR TITLE
Add middleware support in gRPC Server and in the service

### PR DESCRIPTION
**Pull request by vladshub**
The idea is to add a small layer of middleware to allow adding business/system logic and functionality in the middle of the gRPC service and Server.

### CODE REVIEW

**Comment by vladshub** [comment]
I signed it!

**Comment by iamqizhao** [comment]
1) This deserves a simple design proposal before we proceed. If we really want to do that, we need a solution for both unary and streaming rpcs instead of unary only in this PR;
2) somehow this broken coverage test (https://travis-ci.org/grpc/grpc-go/builds/89182097).

**Comment by peter-edge** [comment]
This seems really similar to https://github.com/grpc/grpc-go/pull/349 - can we have a bigger overall discussion about this?

**Comment by iamqizhao** [comment]
Yes, we should. And we should involve @dsymonds in the discussion since it could change the generated code.

**Comment by iamqizhao** [comment]
This has been supported by the server interceptor. close.

**Pull request closed without merging**
