### PR TITLE
Remove single-entry var blocks

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @thinkerou isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by thinkerou** [comment]
I signed it.

**Comment by thinkerou** [comment]
I signed it.

**Comment by dfawley** [comment]
Thanks for the cleanup change!

**Pull request merged**
