### PR TITLE
proxy: add support for digest auth

### PR DESCRIPTION
**Pull request by alban**
This adds client-side support for digest authentication against an http proxy.

MD5, SHA-512-256 and SHA-256 are supported ([rfc7616](https://tools.ietf.org/html/rfc7616)).

It could be tested in different ways:
- Unit tests have been updated to check both basic auth and digest auth.
- If you already have a http proxy configured and a grpc server, you can try:
```
export http_proxy='http://user:password@1.2.3.4:3128'
go run examples/helloworld/greeter_client/main.go -address 5.6.7.8:50052
```
- You can also locally test with apache configured. See `test/http-proxy-digest-auth/README.md` for more instructions.

Part of the implementation is based on [bobziuchkovski/digest](https://github.com/bobziuchkovski/digest) (Apache-2.0 license), with adaptation for HTTP proxies. The copyright headers are updated in relevant files.

Fixes https://github.com/grpc/grpc-go/issues/2440

### CODE REVIEW

**Comment by alban** [comment]
Travis CI tests previously failed when checking the Copyright message: the regexp in `vet.sh` is `Copyright [0-9]\{4,\} gRPC authors`. I fixed the date to match the regexp. Note that I still have the additional copyright header entry as explained in the PR. `vet.sh` seems fine with it now.

I also fixed other `vet.sh` complains:
- comment describing public API
- tests using the `func (s) TestXYZ` format (for leakcheck)

**Comment by menghanl** [comment]
The copyright issue is tricky to deal with.

I'm thinking maybe we can avoid it by doing the following:
1. add an API for proxy auth (in a subpackage like `proxy/httpconnect`)
2. move the implementation to another repo
   a. keep it in it's original repo, and add an implementation of the auth API
   b. or, move to a repo in https://github.com/grpc-ecosystem

Let us know if what you think. Thanks!

**Comment by alban** [comment]
Moving the code to a subpackage `proxy/httpconnect` should be possible and is probably the easiest in your list. I am not sure what that changes for the copyright though but I'm not an expert in that. The files that has the additional copyright line are `digest.go` and `digest_test.go` and they would still be have that copyright in a subpackage. That might be clearer though.

**Comment by menghanl** [comment]
The suggestion I got from license expert is to keep the code with difference copyright isolated, in a `third_party` directory.
To me, I would prefer to keep it in another repo (best in its original repo) rather than copying it to a `grpc/third_party` folder.

We can add an auth API to grpc. This API can support digest, and other future auth methods if desired.

**Pull request closed without merging**
