### PR TITLE
remove a sanity check to give more flexibility to host a service. It …

### PR DESCRIPTION
**Pull request by iamqizhao**
…loses some safety though.

### CODE REVIEW

**Comment by dsymonds** [comment]
What's the use case for this? The sanity check is really quite important: it stops a panic upon receipt of an RPC at some arbitrary time later.

**Comment by iamqizhao** [comment]
This is no-op if users use protobuf as IDL because it already guarantees the success of this sanity check. This change is for people who wants to call Server.RegisterService directly without a proto file. One use case is that we are making health check mechanism which is treated as an internal service hosted by a gRPC server. It is a rpc service but does not use codegen plugin to generate code. I found that by removing this check we can significantly reduce the complexity of the code (because the generated code introduces a lot of unnecessary indirection in this case). This is probably just a short term solution (to speed up the dev of my intern). I will figure out safer way to do this when all the pieces are on the spot.

**Comment by dsymonds** [comment]
Subverting a safety mechanism for short term velocity is almost always the wrong tradeoff.

**Comment by iamqizhao** [comment]
I would claim that it is the responsibility of the caller of
RegisterService to pass a working server instance. RegisterService function
itself does not have obligation to check for the caller.
i) if the user uses protobuf as IDL, this is guaranteed by protobuf codegen;
ii) if the user uses some other IDL, that IDL should guarantee that too;
iii) if the user wants to call RegisterService directly without any IDL,
the user himself should make sure.

Otherwise, the program could be panic. The difference between the existing
code and this PR is just when to fatal/panic.

**Comment by dsymonds** [comment]
It is indeed the responsibility of the caller to ensure they have a well-formed server value, but the point of this safety check is to help them get that right up front rather than them making a mistake and having a ticking time bomb in their server. The IDL turns the up front dynamic check into a static check as an additional layer.

**Comment by iamqizhao** [comment]
okay, we agree that this is optional and I agreed that this check brings
some goodness as I wrote in the PR desc. I think I probably have a way to
keep this check. Actually what I want to do (not in this PR) is that if the
user calls RegisterService and passes a server with method A, B only (in
proto file , A, B, C are defined) and grpc client sends a request to C, the
client will get a "not implemented" error instead of the failure on this
sanity check in the first place.

**Pull request merged**
