### PR TITLE
renamed server and client binaries

### PR DESCRIPTION
**Pull request by awalterschulze**
Fixes https://github.com/grpc/grpc-go/issues/368#issuecomment-144132820

### CODE REVIEW

**Comment by awalterschulze** [comment]
I signed it!

**Comment by awalterschulze** [comment]
I don't see how coverage could have dropped?

I also don't see where the server and client binaries were ever called.

**Comment by iamqizhao** [comment]
Please keep interop dir and files intact? Otherwise we need redo quite a bit work on our interop framework (jenkins, docker, some google internal frameworks).

**Comment by awalterschulze** [comment]
I can revert the interop dir, but then those will probably conflict with some other binary called client or server in another project in future.  
This is a problem with generic binary names.
Are you sure you want me to revert the interop dir?

**Comment by iamqizhao** [comment]
This sounds problematic. These should be isolated.  If the thing is like this, there is no way for a dev of a very popular library to name anything in his code because there is always a chance it will conflict with some of its users...

**Comment by awalterschulze** [comment]
I guess the likelihood of a parallel build building a name conflicting binary at the same time goes down as it crosses package boundaries, since there is still some kind of order.

But if you do not have unique binary names these files will always overwrite themselves as part of a go install ./..., since the binaries are all installed into the same location.
Another conflict can happen even if the other binary is not a go binary.  For example if you name one of your binaries "grep" and it is go installed and your go bin folder is in your $PATH then the OS is going to have choose which grep you are referring to when you try to call grep from the command line.  This is actually a case study and has caused a small bit of frustration.

So I am still happy to revert the interp folder, since it should still solve my problem with parallel builds, but I just want you to reconsider given all the information.

**Comment by dfawley** [comment]
Closing stale PR.

**Pull request closed without merging**
