### PR TITLE
Fix http2 spec document link

### PR DESCRIPTION
**Pull request by jronak**
Spec is now available at https://httpwg.org/specs/rfc7540.html.

RELEASE NOTES: n/a

### CODE REVIEW

**Review by zasweq — APPROVED** [review]
LGTM.

**Comment by zasweq** [comment]
This looks fine. You can go ahead and merge this.

**Comment by jronak** [comment]
@zasweq I don't have permission to merge PR as I can't see the merge pull request button

**Comment by zasweq** [comment]
Merged.

**Pull request merged**
