### PR TITLE
interop: use credentials.NewTLS() when possible

### PR DESCRIPTION
**Pull request by easwars**
Fixes: https://github.com/grpc/grpc-go/issues/2743
#fixit

### CODE REVIEW

**Comment by dfawley** [comment]
The hard part: did you test this with the interop framework manually to make sure it actually works?  Or is this something that's mostly only testable by checking it in and hoping for the best?  @jtattermusch or @ejona86 may be able to advise.

**Comment by easwars** [comment]
> The hard part: did you test this with the interop framework manually to make sure it actually works? Or is this something that's mostly only testable by checking it in and hoping for the best? @jtattermusch or @ejona86 may be able to advise.

I looked around for a fair bit, but couldn't figure out how to run the interop tests manually. So, I had convinced myself that checking it in and hoping for the best was the best strategy.
But will wait for @ejona or @jtattermusch to reply.

**Comment by ejona86** [comment]
Nah, I can't help you; I'm unable to run it and don't understand the various "its." I can run individual client/server pairs sorta okay when I need to by invoking docker or the scripts at `tools/interop_matrix/testcases/`. There's also the I-can-never-find documentation at https://github.com/grpc/grpc/blob/master/tools/run_tests/README.md#interop-tests-run_interop_testspy . But run_interop_tests.py won't run for me currently, and I've never been able to understand differences between the different scripts/pieces. It's only by reading the code of `tools/interop_matrix/run_interop_matrix_tests.py` that I ever figure out "it isn't what I'm looking for" and then generally have no clue where to look next (the answer being "run_tests", I think).

**Review by dfawley — APPROVED** [review]
I'll approve this PR, but please want for @jtattermusch.  If he thinks it's best to just merge it and see what happens, then go for it.  Otherwise please run whatever to test it first.

**Comment by jtattermusch** [comment]
These are the steps I took to run interop tests locally.

1.  clone this PR under `~/workspace/grpc-go`
2. clone grpc/grpc under `~/workspace/grpc` (so that the grpc-go and grpc are cloned side by side, and they are both at versions the commit you wish to test).
3. under ~/workspace/grpc, run `DOCKERHUB_ORGANIZATION=grpctesting python2 tools/run_tests/run_interop_tests.py -l go -s c++ --use_docker` (these are the interop tests with go as client and c++ as a server).

that gave me the output
```
START: Building interop docker images.
PASSED: build_docker_go [time=22.6sec, retries=0:0]
PASSED: build_docker_c++ [time=376.0sec, retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_c++
PASSED: cloud_to_cloud:go:c++_server:ping_pong:tls [time=3.2sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:client_streaming:tls [time=3.3sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:empty_stream:tls [time=3.3sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:cancel_after_begin:tls [time=3.3sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:custom_metadata:tls [time=3.3sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:server_streaming:tls [time=3.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:cancel_after_first_response:tls [time=3.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:large_unary:tls [time=3.5sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:unimplemented_method:tls [time=3.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:empty_unary:tls [time=3.5sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:status_code_and_message:tls [time=3.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:timeout_on_sleeping_server:tls [time=3.5sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:special_status_message:tls [time=1.8sec, retries=0:0]
PASSED: cloud_to_cloud:go:c++_server:unimplemented_service:tls [time=1.9sec, retries=0:0]
SUCCESS: All tests passed
```

4. under ~/workspace/grpc, run `DOCKERHUB_ORGANIZATION=grpctesting python2 tools/run_tests/run_interop_tests.py -l go --cloud_to_prod --use_docker` (these are the "cloud to prod" interop tests against google backend).

These also passed (except the tests that require running on GCE to get the auth token from metadata server).

So I think this is safe to merge.

**Comment by easwars** [comment]
Thank you very much @jtattermusch

**Pull request merged**
