### PR TITLE
xds/internal: rename to LocalityID

### PR DESCRIPTION
**Pull request by zouyee**
rename to LocalityID

Signed-off-by: Zou Nengren <zouyee1989@gmail.com>

### CODE REVIEW

**Comment by easwars** [comment]
@zouyee : Thanks for the fix.

@menghanl : I saw this TODO sometime last week and planning to get to it. Do you have any objections here?

**Comment by easwars** [comment]
@zouyee : Travis seems to be unhappy. Could you please make sure you change builds and that all tests pass.

**Comment by menghanl** [comment]
This LGTM. And thanks for the fix.
Travis seems to be failing because some usages are not updated.

**Comment by zouyee** [comment]
`make testappengine` flaky failure

**Pull request merged**
