### PR TITLE
Allow customizing the context per-method on invoke

### PR DESCRIPTION
**Pull request by ilius**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @ilius isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by menghanl** [comment]
I believe interceptor does what you want.
For unary RPCs, see https://godoc.org/google.golang.org/grpc#WithUnaryInterceptor

**Comment by ilius** [comment]
Thanks for the answer.

But `UnaryClientInterceptor` does not return a context, so how can i modify the context and add timeout?

Also DialOption is only for dial, right? Even if I modify the context for dial, I don't think it effects every request.

**Comment by ilius** [comment]
I signed the CLA

**Comment by menghanl** [comment]
If interceptor is set, the generated code calls interceptor, and the interceptor will call the real `invoke` function.

For example, to modify the context:
```go
func fooUnaryInterceptor(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
	ctx = PrepareContextFunc(ctx, method)
	return invoker(ctx, method, r, reply, cc, opts...)
}
```

**Comment by ilius** [comment]
@menghanl That worked, thank you very much

**Pull request closed without merging**
