### PR TITLE
Use Protobuf JSON formatting for routeguide example.

### PR DESCRIPTION
**Pull request by kyleconroy**
The grpc-java repository now uses protobuf's JSON support to load the
feature database. https://github.com/grpc/grpc-java/pull/1505/files

Fixes https://github.com/grpc/grpc/issues/5533

### CODE REVIEW

**Comment by kyleconroy** [comment]
I signed it!

**Comment by dfawley** [comment]
Closing stale PR.

**Comment by kjc-stripe** [comment]
@dfawley How is this stale? I've been waiting for a year to get a review

**Comment by kyleconroy** [comment]
@dfawley How is this stale? I've been waiting for a year to get a review

**Comment by dfawley** [comment]
@kyleconroy That's exactly why it was considered stale.  It was significantly old and would not merge cleanly.  The team is spending some time each week to go through old PRs in an effort to get the backlog either merged or closed.

In the case of this PR specifically, I'm not really sure why the change was requested in the first place; it appears to be attempting to show off a feature of proto, not grpc, so the team agreed that it wasn't a required change.  We do appreciate your effort, regardless.  Please bear with us while we try to get the open PRs and issues whittled down appropriately over the next few weeks.

**Pull request closed without merging**
