### PR TITLE
client: add a WithNoProxy dialoption

### PR DESCRIPTION
**Pull request by pdbogen**
Hullo! I'm working with a system that talks to some things via grpc and some things not via grpc. (actually, talking over a UNIX domain socket via grpc :grimacing:).

The non-grpc things are mostly HTTP requests that we do need to proxy. The grpc things, as noted, as via local sockets, which _can't_ and shouldn't be proxied.

Providing our own dialer is an option, but this seems a little cleaner and like other folks might also find it useful.

### CODE REVIEW

**Comment by easwars** [comment]
ping @pdbogen

**Comment by pdbogen** [comment]
Thanks for the ping, and for your patience! The original requests for change came in while I was on vacation, so I'd forgotten about them.

**Comment by thaJeztah** [comment]
https://github.com/grpc/grpc-go/pull/3411#discussion_r388589421

> Can you make this withProxy, and set it to true in defaultDialOptions()? So we don't have "if not without proxy".

@menghanl Isn't that a breaking change? I saw this feature in the changelog (knowing that we did something similar in https://github.com/docker/swarmkit/pull/2802), but if consumers of this package setup their own `grpc.ClientConn` (not using the `defaultDialOptions()`), they'll end up with a change in behavior?

I think `withoutProxy` was the better choice, so that the default for the bool (`false`) is also the default to use.

**Comment by thaJeztah** [comment]
Ehm, ignore my comment, had my wires crossed; blame it on "commenting before enough coffee"

**Pull request merged**
