### PR TITLE
Proto buf per conn pool

### PR DESCRIPTION
**Pull request by apolcyn**
Redo of https://github.com/grpc/grpc-go/pull/939

Cuts down on memory usage a lot and seems to improve QPS around 15-20% on protobuf streaming benchmarks.

main changes:
Moved Codec interface, and some Codec specific code including pools, to "codec.go"
Changes around transport and stream initialization, in order to setup per-connection pools for the protoCodecs.
Attaching Codec object to "transport.Stream", where it's initialized.

cc @ctiller @carl-mastrangelo

### CODE REVIEW

**Comment by iamqizhao** [comment]
Some errors with gofmt and goimports on travis. Please fix.

**Comment by iamqizhao** [comment]
Can you rebase to address all the conflicts?

**Comment by apolcyn** [comment]
New tests picked up when rebasing revealed a bug in the initial slice reuse used in this PR - after marshaling, the byte slice was held onto and put back into the pool, and the marshalled byte slice result could be stomped on by a subsequent marshal from the same pool. Noticeable when marshals that use the same pool use *different* protos. Added a new test in codec_test.go to cover this.

The latest commits revert the slice caching that was causing this, but the main benefit of this change still seems to be just in the `proto.Buffer` use - saw a small improvement with the slice reuse, but just pooling and using `proto.Buffer` causes the bulk of the cut in memory use. (in experimental setup, QPS still goes from ~560K QPS to ~650K QPS).

total allocated memory profile, with the latest commit, turns into:
```
7295.77MB of 7331.49MB total (99.51%)
Dropped 64 nodes (cum <= 36.66MB)
      flat  flat%   sum%        cum   cum%
 1093.05MB 14.91% 14.91%  1093.05MB 14.91%  golang.org/x/net/http2.parseDataFrame
 1090.05MB 14.87% 29.78%  1090.05MB 14.87%  google.golang.org/grpc/transport.(*Stream).write
 1071.05MB 14.61% 44.39%  1071.05MB 14.61%  google.golang.org/grpc/transport.(*recvBufferReader).Read
 1056.55MB 14.41% 58.80%  4933.67MB 67.29%  google.golang.org/grpc/benchmark.(*testServer).StreamingCall
  713.52MB  9.73% 68.53%  2466.59MB 33.64%  google.golang.org/grpc/benchmark/grpc_testing.(*benchmarkServiceStreamingCallServer).Recv
  693.52MB  9.46% 77.99%   693.52MB  9.46%  google.golang.org/grpc/benchmark.newPayload
  681.52MB  9.30% 87.28%   681.52MB  9.30%  reflect.unsafe_New
  362.01MB  4.94% 92.22%   362.01MB  4.94%  github.com/golang/protobuf/proto.(*Buffer).enc_len_thing
  346.51MB  4.73% 96.95%   714.01MB  9.74%  google.golang.org/grpc.encode
  180.50MB  2.46% 99.41%  1270.55MB 17.33%  google.golang.org/grpc/transport.(*http2Server).handleData
    5.50MB 0.075% 99.49%   367.51MB  5.01%  google.golang.org/grpc.protoCodec.Marshal
    1.50MB  0.02% 99.51%  4935.17MB 67.31%  google.golang.org/grpc.(*Server).processStreamingRPC
    0.50MB 0.0068% 99.51%  1071.55MB 14.62%  google.golang.org/grpc.(*parser).recvMsg
         0     0% 99.51%   362.01MB  4.94%  github.com/golang/protobuf/proto.(*Buffer).Marshal
         0     0% 99.51%   681.52MB  9.30%  github.com/golang/protobuf/proto.(*Buffer).Unmarshal
         0     0% 99.51%   681.52MB  9.30%  github.com/golang/protobuf/proto.(*Buffer).dec_struct_message
         0     0% 99.51%   362.01MB  4.94%  github.com/golang/protobuf/proto.(*Buffer).enc_len_struct
         0     0% 99.51%   362.01MB  4.94%  github.com/golang/protobuf/proto.(*Buffer).enc_struct
         0     0% 99.51%   362.01MB  4.94%  github.com/golang/protobuf/proto.(*Buffer).enc_struct_message
         0     0% 99.51%   681.52MB  9.30%  
```

The latest change that reverts the slice reuse shows up in 
`5.50MB 0.075% 99.49%   367.51MB  5.01%  google.golang.org/grpc.protoCodec.Marshal`, but the overall total allocated space still reduces about 50%

**Comment by apolcyn** [comment]
this shouldn't have to affect the transport layer like it currently is, moved to https://github.com/grpc/grpc-go/pull/1010

**Pull request closed without merging**
