### PR TITLE
Experimental: Add grpc-web HTTP client

### PR DESCRIPTION
**Pull request by johanbrandhorst**
This client is only enabled when gRPC-Go is built with GOARCH=WASM and GOOS=js. It is a spec-compliant gRPC-Web client.

I have been experimenting with a gRPC-web client written with Go and WASM, which culminated in https://github.com/johanbrandhorst/grpc-wasm, but I thought I could do one better. The idea is to have a program that works both when compiled normally _and_ when compiled to WASM. This client is HTTP based and uses the WASM specific Fetch API based `http.RoundTripper` added in https://github.com/golang/go/pull/25550.

I realise this will probably never be merged, but it's been a fun experiment, and in my testing both unary and server side streaming requests work. I've created a repo for testing this which can be found here: https://github.com/johanbrandhorst/wasm-experiments/tree/master/grpc. The demo showcases 2 unary request responses and 1 server streaming request response stream. It shows the successful parsing of gRPC status errors.

I mentioned this experiment to @jadekler on the Gophers Slack, and also this could probably be implemented much easier if #2112 was fixed.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
I tested this against an Improbable gRPC-Web proxy with https://github.com/improbable-eng/grpc-web/pull/213 applied.

**Comment by johanbrandhorst** [comment]
This can be built using the fresh-off-the-presses go1.11beta1: https://golang.org/dl/#go1.11beta1. See https://github.com/johanbrandhorst/wasm-experiments/blob/1bb4e7fb1e3081fa807f5f22a46f79f07520f2c3/grpc/frontend/frontend.go#L19.

**Comment by johanbrandhorst** [comment]
I made this a little bit easier with a separate repo: https://github.com/johanbrandhorst/grpcweb-wasm-example.

**Comment by dfawley** [comment]
Thanks, this is very cool!  However, I don't think we want to merge something like this in its current form, but rather wait for the redesign mentioned in #2112 and then implement something using that system instead.  I'm working on that right now and hope to have something to share in the next couple weeks.  I will close this PR in the meantime, but thank you again for sharing it.

**Comment by johanbrandhorst** [comment]
Cool, I eagerly await updates on #2112 then :).

**Pull request closed without merging**
