### PR TITLE
Include idempotency level in UnaryServerInfo

### PR DESCRIPTION
**Pull request by keelerh**
Adding idempotency level information to the `UnaryServerInfo` allows idempotency level to be used in server interceptors.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits was unable to be associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by menghanl** [comment]
Can you explain a bit more on the purpose of this change?
Also, `IdempotencyLevel` is never set to non-default value in the change.

**Comment by keelerh** [comment]
Protoc now has support for a new `idempotency_level`method option: https://github.com/google/protobuf/blob/9e745f7/src/google/protobuf/descriptor.proto#L630. The method option can be used to mark the idempotency of a gRPC method.

```
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}
```

`IdempotencyLevel` would be set to a non-default value by explicitly setting the `idempotency_level` method option for a given service.

The purpose of the change is to include this `idempotency_level` information with the previously defined `UnaryServerInfo` such that it can be used at a later point, e.g. by server-side gRPC interceptors designed to ensure that services marked as idempotent do not suddenly become non-idempotent by calling a non-idempotent method.

**Comment by keelerh** [comment]
I signed it!

**Comment by keelerh** [comment]
I signed it!

**Comment by dfawley** [comment]
Thanks for the PR.  We would prefer to implement this by making the entire proto file descriptor available to interceptors, which would include this information.  (#1526)  Unfortunately, that requires changes to generated code, which means it's blocked on us (this PR would have the same constraint).  We hope to get to this early next quarter.  Please let us know if you have any concerns with this.

**Pull request closed without merging**
