### PR TITLE
delete useless code

### PR DESCRIPTION
**Pull request by Arbusz**
Keeping this code may cause some misunderstanding.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @Arbusz isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by menghanl** [comment]
`helloworld.pb.go` needs to be regenerated. Please run `make proto` and try again.

Also, can you sign the CLA? Thanks.

**Comment by menghanl** [comment]
@Arbusz can you rebase the code and also sign the CLA? Thanks!

**Comment by dfawley** [comment]
Closing; if you would like to complete this, let us know and we will reopen.

**Pull request closed without merging**
