### PR TITLE
xdsclient: Flush LRS stream before its context is cancelled

### LINKED ISSUE #6104: xdsclient: flush any unsent loads when the LRS stream is closed
The LRS implementation in the xDS client transport can be found here: https://github.com/grpc/grpc-go/blob/55d8783479c7cc1a72a435340432702a67d809aa/xds/internal/xdsclient/transport/loadreport.go#L47

The `ReportLoad()` API returns a cancel func which is plumbed all the way to the user of the `XDSClient` API here: https://github.com/grpc/grpc-go/blob/55d8783479c7cc1a72a435340432702a67d809aa/xds/internal/xdsclient/client.go#L56

The current implementation of this cancel function simply cancels the context passed to the LRS stream, which results in the stream getting closed. But what we really want is for unsent loads to be flushed on the stream before it is closed.

The xDS client transport spawns the `lrsRunner` goroutine https://github.com/grpc/grpc-go/blob/55d8783479c7cc1a72a435340432702a67d809aa/xds/internal/xdsclient/transport/loadreport.go#L95 which (in a backoff loop) sends the first LRS request, receives the first response and then calls `sendLoads` to periodically send out load reports https://github.com/grpc/grpc-go/blob/55d8783479c7cc1a72a435340432702a67d809aa/xds/internal/xdsclient/transport/loadreport.go#L153

What we want is for the cancel function to synchronize with `sendLoads` so that when the cancel function is invoked, it results in unsent loads being flushed before the stream context is cancelled.

### PR DESCRIPTION
**Pull request by Aditya-Sood**
Fixes #6104

RELEASE NOTES: none

### CODE REVIEW

**Comment by Aditya-Sood** [comment]
hi @easwars,
as I understand from the initial comment on #6104, we want to flush the pending data loads for the last created LRS stream before the `lrsRunner` context is cancelled

I tried synchronising the func `sendLoads()` calls using a WaitGroup, which forces the cancel func call of the `xdsClient` user to wait for any possible ongoing run of `sendLoads()` to return before cancelling the context

however on running the tests I learnt that func `sendLoads()` actually relies on the context being cancelled by the user to stop/exit, and will keep running continuously otherwise

as a result I am not sure what exactly we mean by "flushing" here, because it is possible that there is no data load to "flush" from the stream even though `sendLoads()` is still running

could you please clarify?

**Comment by zasweq** [comment]
Can you please fix tests before I take a look?

**Comment by Aditya-Sood** [comment]
hi @zasweq, actually the previous comment is about my lack of clarity regarding the expected solution

would you be able to clarify it?

**Comment by Aditya-Sood** [comment]
hi @zasweq, wanted to ask if you got a chance to look at the query?
thanks

**Comment by zasweq** [comment]
To flush simply means to finish processing any data needed to be sent to the load reporting server before the lrsRunner goroutine exits. I.e. the cancel function cancels the context, but it should really also block until the lrsRunner goroutine finishes processing any data needed to be sent to upstream.

**Comment by zasweq** [comment]
This attempted fix makes some sense to me though, I think it's along the right track. If you can get the fix + tests to work I'd be happy to review and think about it more technically :). Thank you for the contribution.

**Comment by Aditya-Sood** [comment]
hi @zasweq 
so I've removed the WaitGroup in the latest commit - since it is the context cancellation that causes the `sendLoads()` method to stop, I have added a check on the length of the last received data load to decide whether the stream is in use or not:
```
case <-ctx.Done():
	if len(loads) == 0 { // return only if data load is empty, to flush the stream
		return
	}
	continue
```

few callouts:
1. this works on the assumption that the `(*load.Store).Stats()` method returns an empty `[]*load.Data` idempotently after all the required data has been returned in previous calls

2. since `len(loads)` checks length of result of the last `(*load.Store).Stats()` call, and the `ctx.Done()` channel has already closed, it may take a couple of for-loop cycles before control is yielded to the ticker, to make the final `(*load.Store).Stats()` call whose result will be an empty `loads` slice

3. this is slightly different from @easwars's [original suggestion](https://github.com/grpc/grpc-go/issues/6104#issue-1617887277), as the unsent loads are flushed AFTER the stream context has been cancelled

other than point (1) I think this approach is sound (few extra for-loop cycles due to an unyielding `ctx.Done()` closed channel notwithstanding)

kindly let me know what you think
thanks

**Comment by Aditya-Sood** [comment]
also is the failing test due to my changes or a certificate-related error?

**Comment by zasweq** [comment]
Reran your failing test.

**Comment by zasweq** [comment]
I don't think this fix is correct. In the scenario that there are still loads to be reported, when the load is actually reported, how does this scale down the slice you use for the conditional to exit. Also, I think that we want to synchronize the cancel function synchronizing load reports being flushed *before the stream context is cancelled*. This PR waits for the load reports to be sent (incorrectly) *after the stream context is cancelled*. Thus, I think this fix is wrong, and I will close this PR. Feel free to send out another PR with the synchronization described in the issue. Also, if you do, could you please add a sanity check test for the fix please. Thank you for the contribution :)!

**Comment by Aditya-Sood** [comment]
hi @zasweq 
I didn't follow the statement about "scenario that there are still loads to be reported" - are you saying that `(*load.Store).Stats()` can return `nil` when there are still loads to be reported?
If so could you tell me how to check that no loads are left?

and regarding loads being sent after the stream context has been cancelled, currently the `sendLoads()` function depends on the context to be cancelled in order to exit.
I'll replace that with:
1. a channel to signal the pending cancellation to `sendLoads()`
2. have `sendLoads()` finish sending the pending loads (based on your clarification above), and signal back
3. proceed with context cancellation after receiving `sendLoads()` signal

kindly let me know if you would like any changes to this
thank you

cc: @easwars

**Comment by zasweq** [comment]
Yes please, Easwar describes the synchronization needed in his issue :). Thank you!

**Comment by Aditya-Sood** [comment]
> I didn't follow the statement about "scenario that there are still loads to be reported" - are you saying that (*load.Store).Stats() can return nil when there are still loads to be reported?
If so could you tell me how to check that no loads are left?

@zasweq, could you please clarify on this?

**Comment by Aditya-Sood** [comment]
> I didn't follow the statement about "scenario that there are still loads to be reported" - are you saying that (*load.Store).Stats() can return nil when there are still loads to be reported?
> If so could you tell me how to check that no loads are left?

hi @easwars, would you be able to clarify this?

**Pull request closed without merging**
