### PR TITLE
multiple: update dependencies after 1.57 branch cut

### PR DESCRIPTION
**Pull request by easwars**
Ran the following commands:
```
for x in $(find . -name 'go.mod'); do
  pushd "$(dirname $x)"
  go get -u ./...
  go mod tidy -compat=1.17
  popd
done
```

RELEASE NOTES: none

### CODE REVIEW

**Comment by easwars** [comment]
The `vet-proto` failures seem to be on expected lines since this PR updates the `protoc-gen-go` version to `v1.31.0`.

**Comment by dfawley** [comment]
> The vet-proto failures seem to be on expected lines since this PR updates the protoc-gen-go version to v1.31.0.

Can you update the pb.gos in this PR too, then, please?

**Comment by easwars** [comment]
> > The vet-proto failures seem to be on expected lines since this PR updates the protoc-gen-go version to v1.31.0.
> 
> Can you update the pb.gos in this PR too, then, please?

Done.

But now I see a different error which does seem related to protoc-gen-go.

```
# github.com/golang/glog
Error: ../../../go/pkg/mod/github.com/golang/glog@v1.1.1/glog_file_other.go:27:6: abortProcess redeclared in this block
Error: 	../../../go/pkg/mod/github.com/golang/glog@v1.1.1/glog_file_linux.go:33:6: other declaration of abortProcess
note: module requires Go 1.19
```

It is interesting that the `go get -u` command updated `glog` to a version that requires Go 1.19 while our `go.mod` says Go version is 1.17.

**Comment by dfawley** [comment]
> It is interesting that the go get -u command updated glog to a version that requires Go 1.19 while our go.mod says Go version is 1.17.

I don't think this field means what you think it does.  Or it didn't, anyway, before Go 1.21:

https://go.dev/doc/modules/gomod-ref#go

IIUC it used to only indicate the version of Go whose rules should be applied when parsing that `go.mod` file.

Now it seems like it means what everyone (including me) always assumed.  In the meantime, we'll need to manually `go get` an older version of `glog`. :(

**Review by dfawley — APPROVED** [review]

**Pull request merged**
