### PR TITLE
go.mod: update all dependencies after 1.54 branch cut

### PR DESCRIPTION
**Pull request by easwars**
RELEASE NOTES: none

### CODE REVIEW

**Review by dfawley — APPROVED** [review]

**Review by dfawley — CHANGES_REQUESTED** [review]
Actually, vet seems to be unhappy for non-external dependency reasons.. PTAL

**Comment by easwars** [comment]
This is good for another look. Thanks.

**Comment by dfawley** [comment]
Unfortunately vet-proto is still failing due to a version difference.

**Comment by easwars** [comment]
> Unfortunately vet-proto is still failing due to a version difference.

Isn't that's expected because we have changed the version of `google.golang.org/protobuf` package to `v1.30.0`? And this package is the one which provides `protoc-gen-go`.

**Comment by easwars** [comment]
@dfawley : Gentle ping ...

**Comment by dfawley** [comment]
> Isn't that's expected because we have changed the version of google.golang.org/protobuf package to v1.30.0? And this package is the one which provides protoc-gen-go.

Vet should never fail. You'll need to regenerate all the proto files with the new version of protoc-gen-go and include them in this PR.

**Comment by easwars** [comment]
> > Isn't that's expected because we have changed the version of google.golang.org/protobuf package to v1.30.0? And this package is the one which provides protoc-gen-go.
> 
> Vet should never fail. You'll need to regenerate all the proto files with the new version of protoc-gen-go and include them in this PR.

This is good to be looked at now. Tests passed except a flake which I have started a re-run for.

**Pull request merged**
